// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: bridgr_supported_job_boards.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSupportedJobBoard = `-- name: CreateSupportedJobBoard :one

INSERT INTO bridgr.supported_job_boards (
    board_id,
    display_name,
    engine,
    site_type,
    region,
    is_active,
    config,
    sort_order
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING uuid, id, board_id, display_name, engine, site_type, region, is_active, config, sort_order, created_at, updated_at
`

type CreateSupportedJobBoardParams struct {
	BoardID     string `db:"board_id"`
	DisplayName string `db:"display_name"`
	Engine      string `db:"engine"`
	SiteType    string `db:"site_type"`
	Region      string `db:"region"`
	IsActive    bool   `db:"is_active"`
	Config      []byte `db:"config"`
	SortOrder   int32  `db:"sort_order"`
}

// =============================================================================
// BRIDGR — SUPPORTED JOB BOARDS
// Canonical Radar board catalog. Unique board_id.
// =============================================================================
func (q *Queries) CreateSupportedJobBoard(ctx context.Context, arg CreateSupportedJobBoardParams) (BridgrSupportedJobBoard, error) {
	row := q.db.QueryRow(ctx, createSupportedJobBoard,
		arg.BoardID,
		arg.DisplayName,
		arg.Engine,
		arg.SiteType,
		arg.Region,
		arg.IsActive,
		arg.Config,
		arg.SortOrder,
	)
	var i BridgrSupportedJobBoard
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.BoardID,
		&i.DisplayName,
		&i.Engine,
		&i.SiteType,
		&i.Region,
		&i.IsActive,
		&i.Config,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSupportedJobBoardByID = `-- name: DeleteSupportedJobBoardByID :exec
DELETE FROM bridgr.supported_job_boards
WHERE id = $1
`

func (q *Queries) DeleteSupportedJobBoardByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSupportedJobBoardByID, id)
	return err
}

const deleteSupportedJobBoardByUUID = `-- name: DeleteSupportedJobBoardByUUID :exec
DELETE FROM bridgr.supported_job_boards
WHERE uuid = $1
`

func (q *Queries) DeleteSupportedJobBoardByUUID(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSupportedJobBoardByUUID, uuid)
	return err
}

const getSupportedJobBoardByBoardID = `-- name: GetSupportedJobBoardByBoardID :one
SELECT uuid, id, board_id, display_name, engine, site_type, region, is_active, config, sort_order, created_at, updated_at FROM bridgr.supported_job_boards
WHERE board_id = $1
`

func (q *Queries) GetSupportedJobBoardByBoardID(ctx context.Context, boardID string) (BridgrSupportedJobBoard, error) {
	row := q.db.QueryRow(ctx, getSupportedJobBoardByBoardID, boardID)
	var i BridgrSupportedJobBoard
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.BoardID,
		&i.DisplayName,
		&i.Engine,
		&i.SiteType,
		&i.Region,
		&i.IsActive,
		&i.Config,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupportedJobBoardByID = `-- name: GetSupportedJobBoardByID :one
SELECT uuid, id, board_id, display_name, engine, site_type, region, is_active, config, sort_order, created_at, updated_at FROM bridgr.supported_job_boards
WHERE id = $1
`

func (q *Queries) GetSupportedJobBoardByID(ctx context.Context, id int64) (BridgrSupportedJobBoard, error) {
	row := q.db.QueryRow(ctx, getSupportedJobBoardByID, id)
	var i BridgrSupportedJobBoard
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.BoardID,
		&i.DisplayName,
		&i.Engine,
		&i.SiteType,
		&i.Region,
		&i.IsActive,
		&i.Config,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupportedJobBoardByUUID = `-- name: GetSupportedJobBoardByUUID :one
SELECT uuid, id, board_id, display_name, engine, site_type, region, is_active, config, sort_order, created_at, updated_at FROM bridgr.supported_job_boards
WHERE uuid = $1
`

func (q *Queries) GetSupportedJobBoardByUUID(ctx context.Context, uuid pgtype.UUID) (BridgrSupportedJobBoard, error) {
	row := q.db.QueryRow(ctx, getSupportedJobBoardByUUID, uuid)
	var i BridgrSupportedJobBoard
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.BoardID,
		&i.DisplayName,
		&i.Engine,
		&i.SiteType,
		&i.Region,
		&i.IsActive,
		&i.Config,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSupportedJobBoards = `-- name: ListActiveSupportedJobBoards :many
SELECT uuid, id, board_id, display_name, engine, site_type, region, is_active, config, sort_order, created_at, updated_at FROM bridgr.supported_job_boards
WHERE is_active = true
ORDER BY sort_order ASC, display_name ASC
`

func (q *Queries) ListActiveSupportedJobBoards(ctx context.Context) ([]BridgrSupportedJobBoard, error) {
	rows, err := q.db.Query(ctx, listActiveSupportedJobBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrSupportedJobBoard
	for rows.Next() {
		var i BridgrSupportedJobBoard
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.BoardID,
			&i.DisplayName,
			&i.Engine,
			&i.SiteType,
			&i.Region,
			&i.IsActive,
			&i.Config,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupportedJobBoards = `-- name: ListSupportedJobBoards :many
SELECT uuid, id, board_id, display_name, engine, site_type, region, is_active, config, sort_order, created_at, updated_at FROM bridgr.supported_job_boards
ORDER BY sort_order ASC, display_name ASC
`

func (q *Queries) ListSupportedJobBoards(ctx context.Context) ([]BridgrSupportedJobBoard, error) {
	rows, err := q.db.Query(ctx, listSupportedJobBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrSupportedJobBoard
	for rows.Next() {
		var i BridgrSupportedJobBoard
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.BoardID,
			&i.DisplayName,
			&i.Engine,
			&i.SiteType,
			&i.Region,
			&i.IsActive,
			&i.Config,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSupportedJobBoardByID = `-- name: UpdateSupportedJobBoardByID :one
UPDATE bridgr.supported_job_boards
SET
    board_id = $2,
    display_name = $3,
    engine = $4,
    site_type = $5,
    region = $6,
    is_active = $7,
    config = $8,
    sort_order = $9
WHERE id = $1
RETURNING uuid, id, board_id, display_name, engine, site_type, region, is_active, config, sort_order, created_at, updated_at
`

type UpdateSupportedJobBoardByIDParams struct {
	ID          int64  `db:"id"`
	BoardID     string `db:"board_id"`
	DisplayName string `db:"display_name"`
	Engine      string `db:"engine"`
	SiteType    string `db:"site_type"`
	Region      string `db:"region"`
	IsActive    bool   `db:"is_active"`
	Config      []byte `db:"config"`
	SortOrder   int32  `db:"sort_order"`
}

func (q *Queries) UpdateSupportedJobBoardByID(ctx context.Context, arg UpdateSupportedJobBoardByIDParams) (BridgrSupportedJobBoard, error) {
	row := q.db.QueryRow(ctx, updateSupportedJobBoardByID,
		arg.ID,
		arg.BoardID,
		arg.DisplayName,
		arg.Engine,
		arg.SiteType,
		arg.Region,
		arg.IsActive,
		arg.Config,
		arg.SortOrder,
	)
	var i BridgrSupportedJobBoard
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.BoardID,
		&i.DisplayName,
		&i.Engine,
		&i.SiteType,
		&i.Region,
		&i.IsActive,
		&i.Config,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
