// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: bridgr_job_search_profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJobSearchProfile = `-- name: CreateJobSearchProfile :one

INSERT INTO bridgr.job_search_profiles (
    user_id,
    target_roles,
    locations,
    boards_enabled,
    matching,
    canonical_cv_analysis_uuid,
    max_surfaced_jobs
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING uuid, id, user_id, target_roles, locations, boards_enabled, matching, canonical_cv_analysis_uuid, max_surfaced_jobs, created_at, updated_at
`

type CreateJobSearchProfileParams struct {
	UserID                  int32       `db:"user_id"`
	TargetRoles             []byte      `db:"target_roles"`
	Locations               []byte      `db:"locations"`
	BoardsEnabled           []byte      `db:"boards_enabled"`
	Matching                []byte      `db:"matching"`
	CanonicalCvAnalysisUuid pgtype.UUID `db:"canonical_cv_analysis_uuid"`
	MaxSurfacedJobs         int32       `db:"max_surfaced_jobs"`
}

// =============================================================================
// BRIDGR JOB DISCOVERY — JOB SEARCH PROFILES
// Per-user Radar/search preferences. user_id app-enforced FK to users.id.
// =============================================================================
func (q *Queries) CreateJobSearchProfile(ctx context.Context, arg CreateJobSearchProfileParams) (BridgrJobSearchProfile, error) {
	row := q.db.QueryRow(ctx, createJobSearchProfile,
		arg.UserID,
		arg.TargetRoles,
		arg.Locations,
		arg.BoardsEnabled,
		arg.Matching,
		arg.CanonicalCvAnalysisUuid,
		arg.MaxSurfacedJobs,
	)
	var i BridgrJobSearchProfile
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.TargetRoles,
		&i.Locations,
		&i.BoardsEnabled,
		&i.Matching,
		&i.CanonicalCvAnalysisUuid,
		&i.MaxSurfacedJobs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJobSearchProfileByID = `-- name: DeleteJobSearchProfileByID :exec
DELETE FROM bridgr.job_search_profiles
WHERE id = $1
`

func (q *Queries) DeleteJobSearchProfileByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteJobSearchProfileByID, id)
	return err
}

const deleteJobSearchProfileByUserID = `-- name: DeleteJobSearchProfileByUserID :exec
DELETE FROM bridgr.job_search_profiles
WHERE user_id = $1
`

func (q *Queries) DeleteJobSearchProfileByUserID(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteJobSearchProfileByUserID, userID)
	return err
}

const getJobSearchProfileByID = `-- name: GetJobSearchProfileByID :one
SELECT uuid, id, user_id, target_roles, locations, boards_enabled, matching, canonical_cv_analysis_uuid, max_surfaced_jobs, created_at, updated_at FROM bridgr.job_search_profiles
WHERE id = $1
`

func (q *Queries) GetJobSearchProfileByID(ctx context.Context, id int64) (BridgrJobSearchProfile, error) {
	row := q.db.QueryRow(ctx, getJobSearchProfileByID, id)
	var i BridgrJobSearchProfile
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.TargetRoles,
		&i.Locations,
		&i.BoardsEnabled,
		&i.Matching,
		&i.CanonicalCvAnalysisUuid,
		&i.MaxSurfacedJobs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobSearchProfileByUUID = `-- name: GetJobSearchProfileByUUID :one
SELECT uuid, id, user_id, target_roles, locations, boards_enabled, matching, canonical_cv_analysis_uuid, max_surfaced_jobs, created_at, updated_at FROM bridgr.job_search_profiles
WHERE uuid = $1
`

func (q *Queries) GetJobSearchProfileByUUID(ctx context.Context, uuid pgtype.UUID) (BridgrJobSearchProfile, error) {
	row := q.db.QueryRow(ctx, getJobSearchProfileByUUID, uuid)
	var i BridgrJobSearchProfile
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.TargetRoles,
		&i.Locations,
		&i.BoardsEnabled,
		&i.Matching,
		&i.CanonicalCvAnalysisUuid,
		&i.MaxSurfacedJobs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobSearchProfileByUserID = `-- name: GetJobSearchProfileByUserID :one
SELECT uuid, id, user_id, target_roles, locations, boards_enabled, matching, canonical_cv_analysis_uuid, max_surfaced_jobs, created_at, updated_at FROM bridgr.job_search_profiles
WHERE user_id = $1
`

func (q *Queries) GetJobSearchProfileByUserID(ctx context.Context, userID int32) (BridgrJobSearchProfile, error) {
	row := q.db.QueryRow(ctx, getJobSearchProfileByUserID, userID)
	var i BridgrJobSearchProfile
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.TargetRoles,
		&i.Locations,
		&i.BoardsEnabled,
		&i.Matching,
		&i.CanonicalCvAnalysisUuid,
		&i.MaxSurfacedJobs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobSearchProfile = `-- name: UpdateJobSearchProfile :one
UPDATE bridgr.job_search_profiles
SET
    target_roles = $2,
    locations = $3,
    boards_enabled = $4,
    matching = $5,
    canonical_cv_analysis_uuid = $6,
    max_surfaced_jobs = $7
WHERE id = $1
RETURNING uuid, id, user_id, target_roles, locations, boards_enabled, matching, canonical_cv_analysis_uuid, max_surfaced_jobs, created_at, updated_at
`

type UpdateJobSearchProfileParams struct {
	ID                      int64       `db:"id"`
	TargetRoles             []byte      `db:"target_roles"`
	Locations               []byte      `db:"locations"`
	BoardsEnabled           []byte      `db:"boards_enabled"`
	Matching                []byte      `db:"matching"`
	CanonicalCvAnalysisUuid pgtype.UUID `db:"canonical_cv_analysis_uuid"`
	MaxSurfacedJobs         int32       `db:"max_surfaced_jobs"`
}

func (q *Queries) UpdateJobSearchProfile(ctx context.Context, arg UpdateJobSearchProfileParams) (BridgrJobSearchProfile, error) {
	row := q.db.QueryRow(ctx, updateJobSearchProfile,
		arg.ID,
		arg.TargetRoles,
		arg.Locations,
		arg.BoardsEnabled,
		arg.Matching,
		arg.CanonicalCvAnalysisUuid,
		arg.MaxSurfacedJobs,
	)
	var i BridgrJobSearchProfile
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.TargetRoles,
		&i.Locations,
		&i.BoardsEnabled,
		&i.Matching,
		&i.CanonicalCvAnalysisUuid,
		&i.MaxSurfacedJobs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobSearchProfileByUserID = `-- name: UpdateJobSearchProfileByUserID :one
UPDATE bridgr.job_search_profiles
SET
    target_roles = $2,
    locations = $3,
    boards_enabled = $4,
    matching = $5,
    canonical_cv_analysis_uuid = $6,
    max_surfaced_jobs = $7
WHERE user_id = $1
RETURNING uuid, id, user_id, target_roles, locations, boards_enabled, matching, canonical_cv_analysis_uuid, max_surfaced_jobs, created_at, updated_at
`

type UpdateJobSearchProfileByUserIDParams struct {
	UserID                  int32       `db:"user_id"`
	TargetRoles             []byte      `db:"target_roles"`
	Locations               []byte      `db:"locations"`
	BoardsEnabled           []byte      `db:"boards_enabled"`
	Matching                []byte      `db:"matching"`
	CanonicalCvAnalysisUuid pgtype.UUID `db:"canonical_cv_analysis_uuid"`
	MaxSurfacedJobs         int32       `db:"max_surfaced_jobs"`
}

func (q *Queries) UpdateJobSearchProfileByUserID(ctx context.Context, arg UpdateJobSearchProfileByUserIDParams) (BridgrJobSearchProfile, error) {
	row := q.db.QueryRow(ctx, updateJobSearchProfileByUserID,
		arg.UserID,
		arg.TargetRoles,
		arg.Locations,
		arg.BoardsEnabled,
		arg.Matching,
		arg.CanonicalCvAnalysisUuid,
		arg.MaxSurfacedJobs,
	)
	var i BridgrJobSearchProfile
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.TargetRoles,
		&i.Locations,
		&i.BoardsEnabled,
		&i.Matching,
		&i.CanonicalCvAnalysisUuid,
		&i.MaxSurfacedJobs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
