// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: bridgr_skill_gap_learning_paths.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSkillGapLearningPath = `-- name: CreateSkillGapLearningPath :one

INSERT INTO bridgr.skill_gap_learning_paths (
    analysis_uuid,
    path_version,
    algorithm,
    title,
    path_metadata
) VALUES ($1, $2, $3, $4, $5)
RETURNING uuid, id, analysis_uuid, path_version, algorithm, title, path_metadata, created_at, updated_at
`

type CreateSkillGapLearningPathParams struct {
	AnalysisUuid pgtype.UUID `db:"analysis_uuid"`
	PathVersion  int32       `db:"path_version"`
	Algorithm    pgtype.Text `db:"algorithm"`
	Title        pgtype.Text `db:"title"`
	PathMetadata []byte      `db:"path_metadata"`
}

// =============================================================================
// BRIDGR SKILL GAP — LEARNING PATHS
// Paths per analysis (v1 often one active path; rows versioned by path_version).
// =============================================================================
func (q *Queries) CreateSkillGapLearningPath(ctx context.Context, arg CreateSkillGapLearningPathParams) (HskipUsersBridgrSkillGapLearningPath, error) {
	row := q.db.QueryRow(ctx, createSkillGapLearningPath,
		arg.AnalysisUuid,
		arg.PathVersion,
		arg.Algorithm,
		arg.Title,
		arg.PathMetadata,
	)
	var i HskipUsersBridgrSkillGapLearningPath
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.AnalysisUuid,
		&i.PathVersion,
		&i.Algorithm,
		&i.Title,
		&i.PathMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkillGapLearningPathByAnalysis = `-- name: DeleteSkillGapLearningPathByAnalysis :exec
DELETE FROM bridgr.skill_gap_learning_paths
WHERE analysis_uuid = $1
`

func (q *Queries) DeleteSkillGapLearningPathByAnalysis(ctx context.Context, analysisUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkillGapLearningPathByAnalysis, analysisUuid)
	return err
}

const getSkillGapLearningPath = `-- name: GetSkillGapLearningPath :one
SELECT uuid, id, analysis_uuid, path_version, algorithm, title, path_metadata, created_at, updated_at FROM bridgr.skill_gap_learning_paths
WHERE id = $1
`

func (q *Queries) GetSkillGapLearningPath(ctx context.Context, id int64) (HskipUsersBridgrSkillGapLearningPath, error) {
	row := q.db.QueryRow(ctx, getSkillGapLearningPath, id)
	var i HskipUsersBridgrSkillGapLearningPath
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.AnalysisUuid,
		&i.PathVersion,
		&i.Algorithm,
		&i.Title,
		&i.PathMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillGapLearningPathByAnalysis = `-- name: GetSkillGapLearningPathByAnalysis :one
SELECT uuid, id, analysis_uuid, path_version, algorithm, title, path_metadata, created_at, updated_at FROM bridgr.skill_gap_learning_paths
WHERE analysis_uuid = $1
ORDER BY path_version DESC
LIMIT 1
`

func (q *Queries) GetSkillGapLearningPathByAnalysis(ctx context.Context, analysisUuid pgtype.UUID) (HskipUsersBridgrSkillGapLearningPath, error) {
	row := q.db.QueryRow(ctx, getSkillGapLearningPathByAnalysis, analysisUuid)
	var i HskipUsersBridgrSkillGapLearningPath
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.AnalysisUuid,
		&i.PathVersion,
		&i.Algorithm,
		&i.Title,
		&i.PathMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillGapLearningPathByUUID = `-- name: GetSkillGapLearningPathByUUID :one
SELECT uuid, id, analysis_uuid, path_version, algorithm, title, path_metadata, created_at, updated_at FROM bridgr.skill_gap_learning_paths
WHERE uuid = $1
`

func (q *Queries) GetSkillGapLearningPathByUUID(ctx context.Context, uuid pgtype.UUID) (HskipUsersBridgrSkillGapLearningPath, error) {
	row := q.db.QueryRow(ctx, getSkillGapLearningPathByUUID, uuid)
	var i HskipUsersBridgrSkillGapLearningPath
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.AnalysisUuid,
		&i.PathVersion,
		&i.Algorithm,
		&i.Title,
		&i.PathMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSkillGapLearningPathMetadata = `-- name: UpdateSkillGapLearningPathMetadata :one
UPDATE bridgr.skill_gap_learning_paths
SET path_metadata = $2
WHERE id = $1
RETURNING uuid, id, analysis_uuid, path_version, algorithm, title, path_metadata, created_at, updated_at
`

type UpdateSkillGapLearningPathMetadataParams struct {
	ID           int64  `db:"id"`
	PathMetadata []byte `db:"path_metadata"`
}

func (q *Queries) UpdateSkillGapLearningPathMetadata(ctx context.Context, arg UpdateSkillGapLearningPathMetadataParams) (HskipUsersBridgrSkillGapLearningPath, error) {
	row := q.db.QueryRow(ctx, updateSkillGapLearningPathMetadata, arg.ID, arg.PathMetadata)
	var i HskipUsersBridgrSkillGapLearningPath
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.AnalysisUuid,
		&i.PathVersion,
		&i.Algorithm,
		&i.Title,
		&i.PathMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
