// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: bridgr_analysis_job_link.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnalysisJobLink = `-- name: CreateAnalysisJobLink :one

INSERT INTO bridgr.analysis_job_link (
    user_id,
    analysis_uuid,
    job_candidate_uuid,
    link_kind
) VALUES (
    $1, $2, $3, $4
)
RETURNING uuid, id, user_id, analysis_uuid, job_candidate_uuid, link_kind, created_at, updated_at
`

type CreateAnalysisJobLinkParams struct {
	UserID           int32       `db:"user_id"`
	AnalysisUuid     pgtype.UUID `db:"analysis_uuid"`
	JobCandidateUuid pgtype.UUID `db:"job_candidate_uuid"`
	LinkKind         string      `db:"link_kind"`
}

// =============================================================================
// BRIDGR JOB DISCOVERY — ANALYSIS JOB LINK
// Junction: skill_gap_analyses.uuid ↔ job_candidates.uuid. App-enforced FKs.
// =============================================================================
func (q *Queries) CreateAnalysisJobLink(ctx context.Context, arg CreateAnalysisJobLinkParams) (BridgrAnalysisJobLink, error) {
	row := q.db.QueryRow(ctx, createAnalysisJobLink,
		arg.UserID,
		arg.AnalysisUuid,
		arg.JobCandidateUuid,
		arg.LinkKind,
	)
	var i BridgrAnalysisJobLink
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.AnalysisUuid,
		&i.JobCandidateUuid,
		&i.LinkKind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnalysisJobLinkByID = `-- name: DeleteAnalysisJobLinkByID :exec
DELETE FROM bridgr.analysis_job_link
WHERE id = $1
`

func (q *Queries) DeleteAnalysisJobLinkByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAnalysisJobLinkByID, id)
	return err
}

const deleteAnalysisJobLinkByPair = `-- name: DeleteAnalysisJobLinkByPair :exec
DELETE FROM bridgr.analysis_job_link
WHERE analysis_uuid = $1 AND job_candidate_uuid = $2
`

type DeleteAnalysisJobLinkByPairParams struct {
	AnalysisUuid     pgtype.UUID `db:"analysis_uuid"`
	JobCandidateUuid pgtype.UUID `db:"job_candidate_uuid"`
}

func (q *Queries) DeleteAnalysisJobLinkByPair(ctx context.Context, arg DeleteAnalysisJobLinkByPairParams) error {
	_, err := q.db.Exec(ctx, deleteAnalysisJobLinkByPair, arg.AnalysisUuid, arg.JobCandidateUuid)
	return err
}

const deleteAnalysisJobLinkByUUID = `-- name: DeleteAnalysisJobLinkByUUID :exec
DELETE FROM bridgr.analysis_job_link
WHERE uuid = $1
`

func (q *Queries) DeleteAnalysisJobLinkByUUID(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnalysisJobLinkByUUID, uuid)
	return err
}

const getAnalysisJobLinkByID = `-- name: GetAnalysisJobLinkByID :one
SELECT uuid, id, user_id, analysis_uuid, job_candidate_uuid, link_kind, created_at, updated_at FROM bridgr.analysis_job_link
WHERE id = $1
`

func (q *Queries) GetAnalysisJobLinkByID(ctx context.Context, id int64) (BridgrAnalysisJobLink, error) {
	row := q.db.QueryRow(ctx, getAnalysisJobLinkByID, id)
	var i BridgrAnalysisJobLink
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.AnalysisUuid,
		&i.JobCandidateUuid,
		&i.LinkKind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnalysisJobLinkByPair = `-- name: GetAnalysisJobLinkByPair :one
SELECT uuid, id, user_id, analysis_uuid, job_candidate_uuid, link_kind, created_at, updated_at FROM bridgr.analysis_job_link
WHERE analysis_uuid = $1 AND job_candidate_uuid = $2
`

type GetAnalysisJobLinkByPairParams struct {
	AnalysisUuid     pgtype.UUID `db:"analysis_uuid"`
	JobCandidateUuid pgtype.UUID `db:"job_candidate_uuid"`
}

func (q *Queries) GetAnalysisJobLinkByPair(ctx context.Context, arg GetAnalysisJobLinkByPairParams) (BridgrAnalysisJobLink, error) {
	row := q.db.QueryRow(ctx, getAnalysisJobLinkByPair, arg.AnalysisUuid, arg.JobCandidateUuid)
	var i BridgrAnalysisJobLink
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.AnalysisUuid,
		&i.JobCandidateUuid,
		&i.LinkKind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnalysisJobLinkByUUID = `-- name: GetAnalysisJobLinkByUUID :one
SELECT uuid, id, user_id, analysis_uuid, job_candidate_uuid, link_kind, created_at, updated_at FROM bridgr.analysis_job_link
WHERE uuid = $1
`

func (q *Queries) GetAnalysisJobLinkByUUID(ctx context.Context, uuid pgtype.UUID) (BridgrAnalysisJobLink, error) {
	row := q.db.QueryRow(ctx, getAnalysisJobLinkByUUID, uuid)
	var i BridgrAnalysisJobLink
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.AnalysisUuid,
		&i.JobCandidateUuid,
		&i.LinkKind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnalysisJobLinksByAnalysisUUID = `-- name: ListAnalysisJobLinksByAnalysisUUID :many
SELECT uuid, id, user_id, analysis_uuid, job_candidate_uuid, link_kind, created_at, updated_at FROM bridgr.analysis_job_link
WHERE analysis_uuid = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAnalysisJobLinksByAnalysisUUID(ctx context.Context, analysisUuid pgtype.UUID) ([]BridgrAnalysisJobLink, error) {
	rows, err := q.db.Query(ctx, listAnalysisJobLinksByAnalysisUUID, analysisUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrAnalysisJobLink
	for rows.Next() {
		var i BridgrAnalysisJobLink
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.AnalysisUuid,
			&i.JobCandidateUuid,
			&i.LinkKind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalysisJobLinksByCandidateUUID = `-- name: ListAnalysisJobLinksByCandidateUUID :many
SELECT uuid, id, user_id, analysis_uuid, job_candidate_uuid, link_kind, created_at, updated_at FROM bridgr.analysis_job_link
WHERE job_candidate_uuid = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAnalysisJobLinksByCandidateUUID(ctx context.Context, jobCandidateUuid pgtype.UUID) ([]BridgrAnalysisJobLink, error) {
	rows, err := q.db.Query(ctx, listAnalysisJobLinksByCandidateUUID, jobCandidateUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrAnalysisJobLink
	for rows.Next() {
		var i BridgrAnalysisJobLink
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.AnalysisUuid,
			&i.JobCandidateUuid,
			&i.LinkKind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalysisJobLinksByUser = `-- name: ListAnalysisJobLinksByUser :many
SELECT uuid, id, user_id, analysis_uuid, job_candidate_uuid, link_kind, created_at, updated_at FROM bridgr.analysis_job_link
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAnalysisJobLinksByUserParams struct {
	UserID int32 `db:"user_id"`
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListAnalysisJobLinksByUser(ctx context.Context, arg ListAnalysisJobLinksByUserParams) ([]BridgrAnalysisJobLink, error) {
	rows, err := q.db.Query(ctx, listAnalysisJobLinksByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrAnalysisJobLink
	for rows.Next() {
		var i BridgrAnalysisJobLink
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.AnalysisUuid,
			&i.JobCandidateUuid,
			&i.LinkKind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnalysisJobLinkKind = `-- name: UpdateAnalysisJobLinkKind :one
UPDATE bridgr.analysis_job_link
SET link_kind = $2
WHERE id = $1
RETURNING uuid, id, user_id, analysis_uuid, job_candidate_uuid, link_kind, created_at, updated_at
`

type UpdateAnalysisJobLinkKindParams struct {
	ID       int64  `db:"id"`
	LinkKind string `db:"link_kind"`
}

func (q *Queries) UpdateAnalysisJobLinkKind(ctx context.Context, arg UpdateAnalysisJobLinkKindParams) (BridgrAnalysisJobLink, error) {
	row := q.db.QueryRow(ctx, updateAnalysisJobLinkKind, arg.ID, arg.LinkKind)
	var i BridgrAnalysisJobLink
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.AnalysisUuid,
		&i.JobCandidateUuid,
		&i.LinkKind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
