// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: bridgr_skill_gap_nodes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateSkillGapNodesParams struct {
	GraphUuid       pgtype.UUID `db:"graph_uuid"`
	NodeKey         string      `db:"node_key"`
	DisplayName     string      `db:"display_name"`
	Description     pgtype.Text `db:"description"`
	ProficiencyHint pgtype.Text `db:"proficiency_hint"`
	Source          pgtype.Text `db:"source"`
	Evidence        []byte      `db:"evidence"`
	Metadata        []byte      `db:"metadata"`
	PositionX       pgtype.Int4 `db:"position_x"`
	PositionY       pgtype.Int4 `db:"position_y"`
}

const createSkillGapNode = `-- name: CreateSkillGapNode :one

INSERT INTO hskip_users.bridgr_skill_gap_nodes (
    graph_uuid,
    node_key,
    display_name,
    description,
    proficiency_hint,
    source,
    evidence,
    metadata,
    position_x,
    position_y
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING uuid, id, graph_uuid, node_key, display_name, description, proficiency_hint, source, evidence, metadata, position_x, position_y, created_at, updated_at
`

type CreateSkillGapNodeParams struct {
	GraphUuid       pgtype.UUID `db:"graph_uuid"`
	NodeKey         string      `db:"node_key"`
	DisplayName     string      `db:"display_name"`
	Description     pgtype.Text `db:"description"`
	ProficiencyHint pgtype.Text `db:"proficiency_hint"`
	Source          pgtype.Text `db:"source"`
	Evidence        []byte      `db:"evidence"`
	Metadata        []byte      `db:"metadata"`
	PositionX       pgtype.Int4 `db:"position_x"`
	PositionY       pgtype.Int4 `db:"position_y"`
}

// =============================================================================
// BRIDGR SKILL GAP — NODES
// Skill/concept nodes per graph. graph_uuid app-enforced FK.
// =============================================================================
func (q *Queries) CreateSkillGapNode(ctx context.Context, arg CreateSkillGapNodeParams) (HskipUsersBridgrSkillGapNode, error) {
	row := q.db.QueryRow(ctx, createSkillGapNode,
		arg.GraphUuid,
		arg.NodeKey,
		arg.DisplayName,
		arg.Description,
		arg.ProficiencyHint,
		arg.Source,
		arg.Evidence,
		arg.Metadata,
		arg.PositionX,
		arg.PositionY,
	)
	var i HskipUsersBridgrSkillGapNode
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.GraphUuid,
		&i.NodeKey,
		&i.DisplayName,
		&i.Description,
		&i.ProficiencyHint,
		&i.Source,
		&i.Evidence,
		&i.Metadata,
		&i.PositionX,
		&i.PositionY,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkillGapNodesByGraph = `-- name: DeleteSkillGapNodesByGraph :exec
DELETE FROM hskip_users.bridgr_skill_gap_nodes
WHERE graph_uuid = $1
`

func (q *Queries) DeleteSkillGapNodesByGraph(ctx context.Context, graphUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkillGapNodesByGraph, graphUuid)
	return err
}

const getSkillGapNode = `-- name: GetSkillGapNode :one
SELECT uuid, id, graph_uuid, node_key, display_name, description, proficiency_hint, source, evidence, metadata, position_x, position_y, created_at, updated_at FROM hskip_users.bridgr_skill_gap_nodes
WHERE id = $1
`

func (q *Queries) GetSkillGapNode(ctx context.Context, id int64) (HskipUsersBridgrSkillGapNode, error) {
	row := q.db.QueryRow(ctx, getSkillGapNode, id)
	var i HskipUsersBridgrSkillGapNode
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.GraphUuid,
		&i.NodeKey,
		&i.DisplayName,
		&i.Description,
		&i.ProficiencyHint,
		&i.Source,
		&i.Evidence,
		&i.Metadata,
		&i.PositionX,
		&i.PositionY,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillGapNodeByKey = `-- name: GetSkillGapNodeByKey :one
SELECT uuid, id, graph_uuid, node_key, display_name, description, proficiency_hint, source, evidence, metadata, position_x, position_y, created_at, updated_at FROM hskip_users.bridgr_skill_gap_nodes
WHERE graph_uuid = $1 AND node_key = $2
`

type GetSkillGapNodeByKeyParams struct {
	GraphUuid pgtype.UUID `db:"graph_uuid"`
	NodeKey   string      `db:"node_key"`
}

func (q *Queries) GetSkillGapNodeByKey(ctx context.Context, arg GetSkillGapNodeByKeyParams) (HskipUsersBridgrSkillGapNode, error) {
	row := q.db.QueryRow(ctx, getSkillGapNodeByKey, arg.GraphUuid, arg.NodeKey)
	var i HskipUsersBridgrSkillGapNode
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.GraphUuid,
		&i.NodeKey,
		&i.DisplayName,
		&i.Description,
		&i.ProficiencyHint,
		&i.Source,
		&i.Evidence,
		&i.Metadata,
		&i.PositionX,
		&i.PositionY,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMatchedNodes = `-- name: ListMatchedNodes :many
SELECT rn.uuid, rn.id, rn.graph_uuid, rn.node_key, rn.display_name, rn.description, rn.proficiency_hint, rn.source, rn.evidence, rn.metadata, rn.position_x, rn.position_y, rn.created_at, rn.updated_at FROM hskip_users.bridgr_skill_gap_nodes rn
INNER JOIN hskip_users.bridgr_skill_gap_graphs rg
    ON rg.uuid = rn.graph_uuid AND rg.kind = 'role_requirement'
INNER JOIN hskip_users.bridgr_skill_gap_graphs cg
    ON cg.analysis_uuid = rg.analysis_uuid AND cg.kind = 'candidate'
INNER JOIN hskip_users.bridgr_skill_gap_nodes cn
    ON cn.graph_uuid = cg.uuid AND cn.node_key = rn.node_key
WHERE rg.analysis_uuid = $1
ORDER BY rn.node_key ASC
`

// Role-requirement nodes whose node_key also exists on the candidate graph for the same analysis.
func (q *Queries) ListMatchedNodes(ctx context.Context, analysisUuid pgtype.UUID) ([]HskipUsersBridgrSkillGapNode, error) {
	rows, err := q.db.Query(ctx, listMatchedNodes, analysisUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HskipUsersBridgrSkillGapNode
	for rows.Next() {
		var i HskipUsersBridgrSkillGapNode
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.GraphUuid,
			&i.NodeKey,
			&i.DisplayName,
			&i.Description,
			&i.ProficiencyHint,
			&i.Source,
			&i.Evidence,
			&i.Metadata,
			&i.PositionX,
			&i.PositionY,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillGapNodesByGraph = `-- name: ListSkillGapNodesByGraph :many
SELECT uuid, id, graph_uuid, node_key, display_name, description, proficiency_hint, source, evidence, metadata, position_x, position_y, created_at, updated_at FROM hskip_users.bridgr_skill_gap_nodes
WHERE graph_uuid = $1
ORDER BY node_key ASC
`

func (q *Queries) ListSkillGapNodesByGraph(ctx context.Context, graphUuid pgtype.UUID) ([]HskipUsersBridgrSkillGapNode, error) {
	rows, err := q.db.Query(ctx, listSkillGapNodesByGraph, graphUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HskipUsersBridgrSkillGapNode
	for rows.Next() {
		var i HskipUsersBridgrSkillGapNode
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.GraphUuid,
			&i.NodeKey,
			&i.DisplayName,
			&i.Description,
			&i.ProficiencyHint,
			&i.Source,
			&i.Evidence,
			&i.Metadata,
			&i.PositionX,
			&i.PositionY,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnmatchedNodes = `-- name: ListUnmatchedNodes :many
SELECT rn.uuid, rn.id, rn.graph_uuid, rn.node_key, rn.display_name, rn.description, rn.proficiency_hint, rn.source, rn.evidence, rn.metadata, rn.position_x, rn.position_y, rn.created_at, rn.updated_at FROM hskip_users.bridgr_skill_gap_nodes rn
INNER JOIN hskip_users.bridgr_skill_gap_graphs rg
    ON rg.uuid = rn.graph_uuid AND rg.kind = 'role_requirement'
WHERE rg.analysis_uuid = $1
  AND NOT EXISTS (
    SELECT 1 FROM hskip_users.bridgr_skill_gap_graphs cg
    INNER JOIN hskip_users.bridgr_skill_gap_nodes cn ON cn.graph_uuid = cg.uuid
    WHERE cg.analysis_uuid = rg.analysis_uuid
      AND cg.kind = 'candidate'
      AND cn.node_key = rn.node_key
  )
ORDER BY rn.node_key ASC
`

// Role-requirement nodes with no candidate node sharing the same node_key (skill gaps).
func (q *Queries) ListUnmatchedNodes(ctx context.Context, analysisUuid pgtype.UUID) ([]HskipUsersBridgrSkillGapNode, error) {
	rows, err := q.db.Query(ctx, listUnmatchedNodes, analysisUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HskipUsersBridgrSkillGapNode
	for rows.Next() {
		var i HskipUsersBridgrSkillGapNode
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.GraphUuid,
			&i.NodeKey,
			&i.DisplayName,
			&i.Description,
			&i.ProficiencyHint,
			&i.Source,
			&i.Evidence,
			&i.Metadata,
			&i.PositionX,
			&i.PositionY,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
