// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: bridgr_skill_gap_analyses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSkillGapAnalysis = `-- name: CreateSkillGapAnalysis :one

INSERT INTO hskip_users.bridgr_skill_gap_analyses (
    user_id,
    founder_persona_uuid,
    pursuit_uuid,
    title,
    status,
    cv_asset_uri,
    jd_asset_uri,
    cv_fingerprint,
    jd_fingerprint,
    llm_model,
    prompt_version,
    extraction_payload,
    gap_summary,
    mermaid_diagram,
    error_code,
    error_detail
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING uuid, id, user_id, founder_persona_uuid, pursuit_uuid, title, status, cv_asset_uri, jd_asset_uri, cv_fingerprint, jd_fingerprint, llm_model, prompt_version, extraction_payload, gap_summary, mermaid_diagram, error_code, error_detail, sqs_message_id, created_at, updated_at
`

type CreateSkillGapAnalysisParams struct {
	UserID             int32       `db:"user_id"`
	FounderPersonaUuid pgtype.UUID `db:"founder_persona_uuid"`
	PursuitUuid        pgtype.UUID `db:"pursuit_uuid"`
	Title              pgtype.Text `db:"title"`
	Status             string      `db:"status"`
	CvAssetUri         pgtype.Text `db:"cv_asset_uri"`
	JdAssetUri         pgtype.Text `db:"jd_asset_uri"`
	CvFingerprint      pgtype.Text `db:"cv_fingerprint"`
	JdFingerprint      pgtype.Text `db:"jd_fingerprint"`
	LlmModel           pgtype.Text `db:"llm_model"`
	PromptVersion      pgtype.Text `db:"prompt_version"`
	ExtractionPayload  []byte      `db:"extraction_payload"`
	GapSummary         []byte      `db:"gap_summary"`
	MermaidDiagram     pgtype.Text `db:"mermaid_diagram"`
	ErrorCode          pgtype.Text `db:"error_code"`
	ErrorDetail        pgtype.Text `db:"error_detail"`
}

// =============================================================================
// BRIDGR SKILL GAP — ANALYSES
// One CV+JD skill-gap analysis run. user_id / persona / pursuit are app-enforced FKs.
// =============================================================================
func (q *Queries) CreateSkillGapAnalysis(ctx context.Context, arg CreateSkillGapAnalysisParams) (HskipUsersBridgrSkillGapAnalysis, error) {
	row := q.db.QueryRow(ctx, createSkillGapAnalysis,
		arg.UserID,
		arg.FounderPersonaUuid,
		arg.PursuitUuid,
		arg.Title,
		arg.Status,
		arg.CvAssetUri,
		arg.JdAssetUri,
		arg.CvFingerprint,
		arg.JdFingerprint,
		arg.LlmModel,
		arg.PromptVersion,
		arg.ExtractionPayload,
		arg.GapSummary,
		arg.MermaidDiagram,
		arg.ErrorCode,
		arg.ErrorDetail,
	)
	var i HskipUsersBridgrSkillGapAnalysis
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.FounderPersonaUuid,
		&i.PursuitUuid,
		&i.Title,
		&i.Status,
		&i.CvAssetUri,
		&i.JdAssetUri,
		&i.CvFingerprint,
		&i.JdFingerprint,
		&i.LlmModel,
		&i.PromptVersion,
		&i.ExtractionPayload,
		&i.GapSummary,
		&i.MermaidDiagram,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.SqsMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkillGapAnalysis = `-- name: DeleteSkillGapAnalysis :exec
DELETE FROM hskip_users.bridgr_skill_gap_analyses
WHERE id = $1
`

func (q *Queries) DeleteSkillGapAnalysis(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSkillGapAnalysis, id)
	return err
}

const deleteSkillGapAnalysisByUUID = `-- name: DeleteSkillGapAnalysisByUUID :exec
DELETE FROM hskip_users.bridgr_skill_gap_analyses
WHERE uuid = $1
`

func (q *Queries) DeleteSkillGapAnalysisByUUID(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkillGapAnalysisByUUID, uuid)
	return err
}

const getSkillGapAnalysis = `-- name: GetSkillGapAnalysis :one
SELECT uuid, id, user_id, founder_persona_uuid, pursuit_uuid, title, status, cv_asset_uri, jd_asset_uri, cv_fingerprint, jd_fingerprint, llm_model, prompt_version, extraction_payload, gap_summary, mermaid_diagram, error_code, error_detail, sqs_message_id, created_at, updated_at FROM hskip_users.bridgr_skill_gap_analyses
WHERE id = $1
`

func (q *Queries) GetSkillGapAnalysis(ctx context.Context, id int64) (HskipUsersBridgrSkillGapAnalysis, error) {
	row := q.db.QueryRow(ctx, getSkillGapAnalysis, id)
	var i HskipUsersBridgrSkillGapAnalysis
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.FounderPersonaUuid,
		&i.PursuitUuid,
		&i.Title,
		&i.Status,
		&i.CvAssetUri,
		&i.JdAssetUri,
		&i.CvFingerprint,
		&i.JdFingerprint,
		&i.LlmModel,
		&i.PromptVersion,
		&i.ExtractionPayload,
		&i.GapSummary,
		&i.MermaidDiagram,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.SqsMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillGapAnalysisByFingerprint = `-- name: GetSkillGapAnalysisByFingerprint :one
SELECT uuid, id, user_id, founder_persona_uuid, pursuit_uuid, title, status, cv_asset_uri, jd_asset_uri, cv_fingerprint, jd_fingerprint, llm_model, prompt_version, extraction_payload, gap_summary, mermaid_diagram, error_code, error_detail, sqs_message_id, created_at, updated_at FROM hskip_users.bridgr_skill_gap_analyses
WHERE user_id = $1
  AND cv_fingerprint = $2
  AND jd_fingerprint = $3
ORDER BY created_at DESC
LIMIT 1
`

type GetSkillGapAnalysisByFingerprintParams struct {
	UserID        int32       `db:"user_id"`
	CvFingerprint pgtype.Text `db:"cv_fingerprint"`
	JdFingerprint pgtype.Text `db:"jd_fingerprint"`
}

func (q *Queries) GetSkillGapAnalysisByFingerprint(ctx context.Context, arg GetSkillGapAnalysisByFingerprintParams) (HskipUsersBridgrSkillGapAnalysis, error) {
	row := q.db.QueryRow(ctx, getSkillGapAnalysisByFingerprint, arg.UserID, arg.CvFingerprint, arg.JdFingerprint)
	var i HskipUsersBridgrSkillGapAnalysis
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.FounderPersonaUuid,
		&i.PursuitUuid,
		&i.Title,
		&i.Status,
		&i.CvAssetUri,
		&i.JdAssetUri,
		&i.CvFingerprint,
		&i.JdFingerprint,
		&i.LlmModel,
		&i.PromptVersion,
		&i.ExtractionPayload,
		&i.GapSummary,
		&i.MermaidDiagram,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.SqsMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillGapAnalysisByUUID = `-- name: GetSkillGapAnalysisByUUID :one
SELECT uuid, id, user_id, founder_persona_uuid, pursuit_uuid, title, status, cv_asset_uri, jd_asset_uri, cv_fingerprint, jd_fingerprint, llm_model, prompt_version, extraction_payload, gap_summary, mermaid_diagram, error_code, error_detail, sqs_message_id, created_at, updated_at FROM hskip_users.bridgr_skill_gap_analyses
WHERE uuid = $1
`

func (q *Queries) GetSkillGapAnalysisByUUID(ctx context.Context, uuid pgtype.UUID) (HskipUsersBridgrSkillGapAnalysis, error) {
	row := q.db.QueryRow(ctx, getSkillGapAnalysisByUUID, uuid)
	var i HskipUsersBridgrSkillGapAnalysis
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.FounderPersonaUuid,
		&i.PursuitUuid,
		&i.Title,
		&i.Status,
		&i.CvAssetUri,
		&i.JdAssetUri,
		&i.CvFingerprint,
		&i.JdFingerprint,
		&i.LlmModel,
		&i.PromptVersion,
		&i.ExtractionPayload,
		&i.GapSummary,
		&i.MermaidDiagram,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.SqsMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillGapAnalysisByUser = `-- name: GetSkillGapAnalysisByUser :many
SELECT uuid, id, user_id, founder_persona_uuid, pursuit_uuid, title, status, cv_asset_uri, jd_asset_uri, cv_fingerprint, jd_fingerprint, llm_model, prompt_version, extraction_payload, gap_summary, mermaid_diagram, error_code, error_detail, sqs_message_id, created_at, updated_at FROM hskip_users.bridgr_skill_gap_analyses
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetSkillGapAnalysisByUserParams struct {
	UserID int32 `db:"user_id"`
	Limit  int32 `db:"limit"`
}

func (q *Queries) GetSkillGapAnalysisByUser(ctx context.Context, arg GetSkillGapAnalysisByUserParams) ([]HskipUsersBridgrSkillGapAnalysis, error) {
	rows, err := q.db.Query(ctx, getSkillGapAnalysisByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HskipUsersBridgrSkillGapAnalysis
	for rows.Next() {
		var i HskipUsersBridgrSkillGapAnalysis
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.FounderPersonaUuid,
			&i.PursuitUuid,
			&i.Title,
			&i.Status,
			&i.CvAssetUri,
			&i.JdAssetUri,
			&i.CvFingerprint,
			&i.JdFingerprint,
			&i.LlmModel,
			&i.PromptVersion,
			&i.ExtractionPayload,
			&i.GapSummary,
			&i.MermaidDiagram,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.SqsMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillGapAnalysesByUser = `-- name: ListSkillGapAnalysesByUser :many
SELECT uuid, id, user_id, founder_persona_uuid, pursuit_uuid, title, status, cv_asset_uri, jd_asset_uri, cv_fingerprint, jd_fingerprint, llm_model, prompt_version, extraction_payload, gap_summary, mermaid_diagram, error_code, error_detail, sqs_message_id, created_at, updated_at FROM hskip_users.bridgr_skill_gap_analyses
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSkillGapAnalysesByUserParams struct {
	UserID int32 `db:"user_id"`
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListSkillGapAnalysesByUser(ctx context.Context, arg ListSkillGapAnalysesByUserParams) ([]HskipUsersBridgrSkillGapAnalysis, error) {
	rows, err := q.db.Query(ctx, listSkillGapAnalysesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HskipUsersBridgrSkillGapAnalysis
	for rows.Next() {
		var i HskipUsersBridgrSkillGapAnalysis
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.FounderPersonaUuid,
			&i.PursuitUuid,
			&i.Title,
			&i.Status,
			&i.CvAssetUri,
			&i.JdAssetUri,
			&i.CvFingerprint,
			&i.JdFingerprint,
			&i.LlmModel,
			&i.PromptVersion,
			&i.ExtractionPayload,
			&i.GapSummary,
			&i.MermaidDiagram,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.SqsMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkillGapAnalysisError = `-- name: UpdateSkillGapAnalysisError :one
UPDATE hskip_users.bridgr_skill_gap_analyses
SET error_code = $2,
    error_detail = $3,
    status = 'failed'
WHERE id = $1
RETURNING uuid, id, user_id, founder_persona_uuid, pursuit_uuid, title, status, cv_asset_uri, jd_asset_uri, cv_fingerprint, jd_fingerprint, llm_model, prompt_version, extraction_payload, gap_summary, mermaid_diagram, error_code, error_detail, sqs_message_id, created_at, updated_at
`

type UpdateSkillGapAnalysisErrorParams struct {
	ID          int64       `db:"id"`
	ErrorCode   pgtype.Text `db:"error_code"`
	ErrorDetail pgtype.Text `db:"error_detail"`
}

func (q *Queries) UpdateSkillGapAnalysisError(ctx context.Context, arg UpdateSkillGapAnalysisErrorParams) (HskipUsersBridgrSkillGapAnalysis, error) {
	row := q.db.QueryRow(ctx, updateSkillGapAnalysisError, arg.ID, arg.ErrorCode, arg.ErrorDetail)
	var i HskipUsersBridgrSkillGapAnalysis
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.FounderPersonaUuid,
		&i.PursuitUuid,
		&i.Title,
		&i.Status,
		&i.CvAssetUri,
		&i.JdAssetUri,
		&i.CvFingerprint,
		&i.JdFingerprint,
		&i.LlmModel,
		&i.PromptVersion,
		&i.ExtractionPayload,
		&i.GapSummary,
		&i.MermaidDiagram,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.SqsMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSkillGapAnalysisStatus = `-- name: UpdateSkillGapAnalysisStatus :one
UPDATE hskip_users.bridgr_skill_gap_analyses
SET status = $2
WHERE id = $1
RETURNING uuid, id, user_id, founder_persona_uuid, pursuit_uuid, title, status, cv_asset_uri, jd_asset_uri, cv_fingerprint, jd_fingerprint, llm_model, prompt_version, extraction_payload, gap_summary, mermaid_diagram, error_code, error_detail, sqs_message_id, created_at, updated_at
`

type UpdateSkillGapAnalysisStatusParams struct {
	ID     int64  `db:"id"`
	Status string `db:"status"`
}

func (q *Queries) UpdateSkillGapAnalysisStatus(ctx context.Context, arg UpdateSkillGapAnalysisStatusParams) (HskipUsersBridgrSkillGapAnalysis, error) {
	row := q.db.QueryRow(ctx, updateSkillGapAnalysisStatus, arg.ID, arg.Status)
	var i HskipUsersBridgrSkillGapAnalysis
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.FounderPersonaUuid,
		&i.PursuitUuid,
		&i.Title,
		&i.Status,
		&i.CvAssetUri,
		&i.JdAssetUri,
		&i.CvFingerprint,
		&i.JdFingerprint,
		&i.LlmModel,
		&i.PromptVersion,
		&i.ExtractionPayload,
		&i.GapSummary,
		&i.MermaidDiagram,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.SqsMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSkillGapAnalysisSummary = `-- name: UpdateSkillGapAnalysisSummary :one
UPDATE hskip_users.bridgr_skill_gap_analyses
SET gap_summary = $2,
    mermaid_diagram = $3
WHERE id = $1
RETURNING uuid, id, user_id, founder_persona_uuid, pursuit_uuid, title, status, cv_asset_uri, jd_asset_uri, cv_fingerprint, jd_fingerprint, llm_model, prompt_version, extraction_payload, gap_summary, mermaid_diagram, error_code, error_detail, sqs_message_id, created_at, updated_at
`

type UpdateSkillGapAnalysisSummaryParams struct {
	ID             int64       `db:"id"`
	GapSummary     []byte      `db:"gap_summary"`
	MermaidDiagram pgtype.Text `db:"mermaid_diagram"`
}

func (q *Queries) UpdateSkillGapAnalysisSummary(ctx context.Context, arg UpdateSkillGapAnalysisSummaryParams) (HskipUsersBridgrSkillGapAnalysis, error) {
	row := q.db.QueryRow(ctx, updateSkillGapAnalysisSummary, arg.ID, arg.GapSummary, arg.MermaidDiagram)
	var i HskipUsersBridgrSkillGapAnalysis
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.FounderPersonaUuid,
		&i.PursuitUuid,
		&i.Title,
		&i.Status,
		&i.CvAssetUri,
		&i.JdAssetUri,
		&i.CvFingerprint,
		&i.JdFingerprint,
		&i.LlmModel,
		&i.PromptVersion,
		&i.ExtractionPayload,
		&i.GapSummary,
		&i.MermaidDiagram,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.SqsMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
