// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: bridgr_job_notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJobNotification = `-- name: CreateJobNotification :one

INSERT INTO bridgr.job_notifications (
    user_id,
    job_candidate_uuid,
    channel,
    status,
    payload,
    sent_at,
    seen_at,
    error_detail
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING uuid, id, user_id, job_candidate_uuid, channel, status, payload, sent_at, seen_at, error_detail, created_at, updated_at
`

type CreateJobNotificationParams struct {
	UserID           int32            `db:"user_id"`
	JobCandidateUuid pgtype.UUID      `db:"job_candidate_uuid"`
	Channel          string           `db:"channel"`
	Status           string           `db:"status"`
	Payload          []byte           `db:"payload"`
	SentAt           pgtype.Timestamp `db:"sent_at"`
	SeenAt           pgtype.Timestamp `db:"seen_at"`
	ErrorDetail      pgtype.Text      `db:"error_detail"`
}

// =============================================================================
// BRIDGR JOB DISCOVERY — NOTIFICATIONS
// Outbox for in-app / email / push. user_id and job_candidate_uuid app-enforced.
// =============================================================================
func (q *Queries) CreateJobNotification(ctx context.Context, arg CreateJobNotificationParams) (BridgrJobNotification, error) {
	row := q.db.QueryRow(ctx, createJobNotification,
		arg.UserID,
		arg.JobCandidateUuid,
		arg.Channel,
		arg.Status,
		arg.Payload,
		arg.SentAt,
		arg.SeenAt,
		arg.ErrorDetail,
	)
	var i BridgrJobNotification
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.SentAt,
		&i.SeenAt,
		&i.ErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJobNotificationByID = `-- name: DeleteJobNotificationByID :exec
DELETE FROM bridgr.job_notifications
WHERE id = $1
`

func (q *Queries) DeleteJobNotificationByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteJobNotificationByID, id)
	return err
}

const deleteJobNotificationByUUID = `-- name: DeleteJobNotificationByUUID :exec
DELETE FROM bridgr.job_notifications
WHERE uuid = $1
`

func (q *Queries) DeleteJobNotificationByUUID(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJobNotificationByUUID, uuid)
	return err
}

const getJobNotificationByID = `-- name: GetJobNotificationByID :one
SELECT uuid, id, user_id, job_candidate_uuid, channel, status, payload, sent_at, seen_at, error_detail, created_at, updated_at FROM bridgr.job_notifications
WHERE id = $1
`

func (q *Queries) GetJobNotificationByID(ctx context.Context, id int64) (BridgrJobNotification, error) {
	row := q.db.QueryRow(ctx, getJobNotificationByID, id)
	var i BridgrJobNotification
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.SentAt,
		&i.SeenAt,
		&i.ErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobNotificationByUUID = `-- name: GetJobNotificationByUUID :one
SELECT uuid, id, user_id, job_candidate_uuid, channel, status, payload, sent_at, seen_at, error_detail, created_at, updated_at FROM bridgr.job_notifications
WHERE uuid = $1
`

func (q *Queries) GetJobNotificationByUUID(ctx context.Context, uuid pgtype.UUID) (BridgrJobNotification, error) {
	row := q.db.QueryRow(ctx, getJobNotificationByUUID, uuid)
	var i BridgrJobNotification
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.SentAt,
		&i.SeenAt,
		&i.ErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobNotificationsByUser = `-- name: ListJobNotificationsByUser :many
SELECT uuid, id, user_id, job_candidate_uuid, channel, status, payload, sent_at, seen_at, error_detail, created_at, updated_at FROM bridgr.job_notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobNotificationsByUserParams struct {
	UserID int32 `db:"user_id"`
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListJobNotificationsByUser(ctx context.Context, arg ListJobNotificationsByUserParams) ([]BridgrJobNotification, error) {
	rows, err := q.db.Query(ctx, listJobNotificationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrJobNotification
	for rows.Next() {
		var i BridgrJobNotification
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.JobCandidateUuid,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.SentAt,
			&i.SeenAt,
			&i.ErrorDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobNotificationsByUserAndStatus = `-- name: ListJobNotificationsByUserAndStatus :many
SELECT uuid, id, user_id, job_candidate_uuid, channel, status, payload, sent_at, seen_at, error_detail, created_at, updated_at FROM bridgr.job_notifications
WHERE user_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListJobNotificationsByUserAndStatusParams struct {
	UserID int32  `db:"user_id"`
	Status string `db:"status"`
	Limit  int32  `db:"limit"`
	Offset int32  `db:"offset"`
}

func (q *Queries) ListJobNotificationsByUserAndStatus(ctx context.Context, arg ListJobNotificationsByUserAndStatusParams) ([]BridgrJobNotification, error) {
	rows, err := q.db.Query(ctx, listJobNotificationsByUserAndStatus,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrJobNotification
	for rows.Next() {
		var i BridgrJobNotification
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.JobCandidateUuid,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.SentAt,
			&i.SeenAt,
			&i.ErrorDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobNotificationsByUserFiltered = `-- name: ListJobNotificationsByUserFiltered :many
SELECT uuid, id, user_id, job_candidate_uuid, channel, status, payload, sent_at, seen_at, error_detail, created_at, updated_at FROM bridgr.job_notifications AS n
WHERE n.user_id = $1
  AND ($2::timestamp IS NULL OR n.created_at > $2::timestamp)
  AND ($3::text IS NULL OR $3::text = '' OR n.status = $3::text)
ORDER BY n.created_at DESC
LIMIT $5 OFFSET $4
`

type ListJobNotificationsByUserFilteredParams struct {
	UserID int32            `db:"user_id"`
	Since  pgtype.Timestamp `db:"since"`
	Status pgtype.Text      `db:"status"`
	Offset int32            `db:"offset"`
	Limit  int32            `db:"limit"`
}

func (q *Queries) ListJobNotificationsByUserFiltered(ctx context.Context, arg ListJobNotificationsByUserFilteredParams) ([]BridgrJobNotification, error) {
	rows, err := q.db.Query(ctx, listJobNotificationsByUserFiltered,
		arg.UserID,
		arg.Since,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrJobNotification
	for rows.Next() {
		var i BridgrJobNotification
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.JobCandidateUuid,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.SentAt,
			&i.SeenAt,
			&i.ErrorDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingJobNotificationsByUser = `-- name: ListPendingJobNotificationsByUser :many
SELECT uuid, id, user_id, job_candidate_uuid, channel, status, payload, sent_at, seen_at, error_detail, created_at, updated_at FROM bridgr.job_notifications
WHERE user_id = $1 AND status = 'pending'
ORDER BY created_at ASC
LIMIT $2
`

type ListPendingJobNotificationsByUserParams struct {
	UserID int32 `db:"user_id"`
	Limit  int32 `db:"limit"`
}

func (q *Queries) ListPendingJobNotificationsByUser(ctx context.Context, arg ListPendingJobNotificationsByUserParams) ([]BridgrJobNotification, error) {
	rows, err := q.db.Query(ctx, listPendingJobNotificationsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrJobNotification
	for rows.Next() {
		var i BridgrJobNotification
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.JobCandidateUuid,
			&i.Channel,
			&i.Status,
			&i.Payload,
			&i.SentAt,
			&i.SeenAt,
			&i.ErrorDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobNotificationSeen = `-- name: UpdateJobNotificationSeen :one
UPDATE bridgr.job_notifications
SET
    status = $2,
    seen_at = $3
WHERE id = $1
RETURNING uuid, id, user_id, job_candidate_uuid, channel, status, payload, sent_at, seen_at, error_detail, created_at, updated_at
`

type UpdateJobNotificationSeenParams struct {
	ID     int64            `db:"id"`
	Status string           `db:"status"`
	SeenAt pgtype.Timestamp `db:"seen_at"`
}

func (q *Queries) UpdateJobNotificationSeen(ctx context.Context, arg UpdateJobNotificationSeenParams) (BridgrJobNotification, error) {
	row := q.db.QueryRow(ctx, updateJobNotificationSeen, arg.ID, arg.Status, arg.SeenAt)
	var i BridgrJobNotification
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.SentAt,
		&i.SeenAt,
		&i.ErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobNotificationStatus = `-- name: UpdateJobNotificationStatus :one
UPDATE bridgr.job_notifications
SET
    status = $2,
    sent_at = $3,
    error_detail = $4
WHERE id = $1
RETURNING uuid, id, user_id, job_candidate_uuid, channel, status, payload, sent_at, seen_at, error_detail, created_at, updated_at
`

type UpdateJobNotificationStatusParams struct {
	ID          int64            `db:"id"`
	Status      string           `db:"status"`
	SentAt      pgtype.Timestamp `db:"sent_at"`
	ErrorDetail pgtype.Text      `db:"error_detail"`
}

func (q *Queries) UpdateJobNotificationStatus(ctx context.Context, arg UpdateJobNotificationStatusParams) (BridgrJobNotification, error) {
	row := q.db.QueryRow(ctx, updateJobNotificationStatus,
		arg.ID,
		arg.Status,
		arg.SentAt,
		arg.ErrorDetail,
	)
	var i BridgrJobNotification
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.Channel,
		&i.Status,
		&i.Payload,
		&i.SentAt,
		&i.SeenAt,
		&i.ErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
