// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: bridgr_job_search_discovery_runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJobSearchDiscoveryRunsByUserSince = `-- name: CountJobSearchDiscoveryRunsByUserSince :one
SELECT COUNT(*)::bigint AS count FROM bridgr.job_search_discovery_runs
WHERE user_id = $1 AND created_at >= $2
`

type CountJobSearchDiscoveryRunsByUserSinceParams struct {
	UserID    int32            `db:"user_id"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
}

func (q *Queries) CountJobSearchDiscoveryRunsByUserSince(ctx context.Context, arg CountJobSearchDiscoveryRunsByUserSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJobSearchDiscoveryRunsByUserSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJobSearchDiscoveryRun = `-- name: CreateJobSearchDiscoveryRun :one

INSERT INTO bridgr.job_search_discovery_runs (
    user_id,
    status,
    request_params,
    radar_meta,
    raw_candidate_count,
    new_candidate_count,
    started_at,
    completed_at,
    error_code,
    error_detail,
    sqs_message_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING uuid, id, user_id, status, request_params, radar_meta, raw_candidate_count, new_candidate_count, started_at, completed_at, error_code, error_detail, sqs_message_id, created_at, updated_at
`

type CreateJobSearchDiscoveryRunParams struct {
	UserID            int32            `db:"user_id"`
	Status            string           `db:"status"`
	RequestParams     []byte           `db:"request_params"`
	RadarMeta         []byte           `db:"radar_meta"`
	RawCandidateCount int32            `db:"raw_candidate_count"`
	NewCandidateCount int32            `db:"new_candidate_count"`
	StartedAt         pgtype.Timestamp `db:"started_at"`
	CompletedAt       pgtype.Timestamp `db:"completed_at"`
	ErrorCode         pgtype.Text      `db:"error_code"`
	ErrorDetail       pgtype.Text      `db:"error_detail"`
	SqsMessageID      pgtype.Text      `db:"sqs_message_id"`
}

// =============================================================================
// BRIDGR JOB DISCOVERY — DISCOVERY RUNS
// One Radar sweep audit row per execution. user_id app-enforced FK to users.id.
// =============================================================================
func (q *Queries) CreateJobSearchDiscoveryRun(ctx context.Context, arg CreateJobSearchDiscoveryRunParams) (BridgrJobSearchDiscoveryRun, error) {
	row := q.db.QueryRow(ctx, createJobSearchDiscoveryRun,
		arg.UserID,
		arg.Status,
		arg.RequestParams,
		arg.RadarMeta,
		arg.RawCandidateCount,
		arg.NewCandidateCount,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ErrorCode,
		arg.ErrorDetail,
		arg.SqsMessageID,
	)
	var i BridgrJobSearchDiscoveryRun
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RequestParams,
		&i.RadarMeta,
		&i.RawCandidateCount,
		&i.NewCandidateCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.SqsMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJobSearchDiscoveryRunByID = `-- name: DeleteJobSearchDiscoveryRunByID :exec
DELETE FROM bridgr.job_search_discovery_runs
WHERE id = $1
`

func (q *Queries) DeleteJobSearchDiscoveryRunByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteJobSearchDiscoveryRunByID, id)
	return err
}

const getJobSearchDiscoveryRunByID = `-- name: GetJobSearchDiscoveryRunByID :one
SELECT uuid, id, user_id, status, request_params, radar_meta, raw_candidate_count, new_candidate_count, started_at, completed_at, error_code, error_detail, sqs_message_id, created_at, updated_at FROM bridgr.job_search_discovery_runs
WHERE id = $1
`

func (q *Queries) GetJobSearchDiscoveryRunByID(ctx context.Context, id int64) (BridgrJobSearchDiscoveryRun, error) {
	row := q.db.QueryRow(ctx, getJobSearchDiscoveryRunByID, id)
	var i BridgrJobSearchDiscoveryRun
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RequestParams,
		&i.RadarMeta,
		&i.RawCandidateCount,
		&i.NewCandidateCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.SqsMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobSearchDiscoveryRunByUUID = `-- name: GetJobSearchDiscoveryRunByUUID :one
SELECT uuid, id, user_id, status, request_params, radar_meta, raw_candidate_count, new_candidate_count, started_at, completed_at, error_code, error_detail, sqs_message_id, created_at, updated_at FROM bridgr.job_search_discovery_runs
WHERE uuid = $1
`

func (q *Queries) GetJobSearchDiscoveryRunByUUID(ctx context.Context, uuid pgtype.UUID) (BridgrJobSearchDiscoveryRun, error) {
	row := q.db.QueryRow(ctx, getJobSearchDiscoveryRunByUUID, uuid)
	var i BridgrJobSearchDiscoveryRun
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RequestParams,
		&i.RadarMeta,
		&i.RawCandidateCount,
		&i.NewCandidateCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.SqsMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobSearchDiscoveryRunsByUser = `-- name: ListJobSearchDiscoveryRunsByUser :many
SELECT uuid, id, user_id, status, request_params, radar_meta, raw_candidate_count, new_candidate_count, started_at, completed_at, error_code, error_detail, sqs_message_id, created_at, updated_at FROM bridgr.job_search_discovery_runs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobSearchDiscoveryRunsByUserParams struct {
	UserID int32 `db:"user_id"`
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListJobSearchDiscoveryRunsByUser(ctx context.Context, arg ListJobSearchDiscoveryRunsByUserParams) ([]BridgrJobSearchDiscoveryRun, error) {
	rows, err := q.db.Query(ctx, listJobSearchDiscoveryRunsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrJobSearchDiscoveryRun
	for rows.Next() {
		var i BridgrJobSearchDiscoveryRun
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.RequestParams,
			&i.RadarMeta,
			&i.RawCandidateCount,
			&i.NewCandidateCount,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.SqsMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobSearchDiscoveryRunFinished = `-- name: UpdateJobSearchDiscoveryRunFinished :one
UPDATE bridgr.job_search_discovery_runs
SET
    status = $2,
    completed_at = $3,
    raw_candidate_count = $4,
    new_candidate_count = $5,
    radar_meta = $6,
    error_code = $7,
    error_detail = $8
WHERE id = $1
RETURNING uuid, id, user_id, status, request_params, radar_meta, raw_candidate_count, new_candidate_count, started_at, completed_at, error_code, error_detail, sqs_message_id, created_at, updated_at
`

type UpdateJobSearchDiscoveryRunFinishedParams struct {
	ID                int64            `db:"id"`
	Status            string           `db:"status"`
	CompletedAt       pgtype.Timestamp `db:"completed_at"`
	RawCandidateCount int32            `db:"raw_candidate_count"`
	NewCandidateCount int32            `db:"new_candidate_count"`
	RadarMeta         []byte           `db:"radar_meta"`
	ErrorCode         pgtype.Text      `db:"error_code"`
	ErrorDetail       pgtype.Text      `db:"error_detail"`
}

func (q *Queries) UpdateJobSearchDiscoveryRunFinished(ctx context.Context, arg UpdateJobSearchDiscoveryRunFinishedParams) (BridgrJobSearchDiscoveryRun, error) {
	row := q.db.QueryRow(ctx, updateJobSearchDiscoveryRunFinished,
		arg.ID,
		arg.Status,
		arg.CompletedAt,
		arg.RawCandidateCount,
		arg.NewCandidateCount,
		arg.RadarMeta,
		arg.ErrorCode,
		arg.ErrorDetail,
	)
	var i BridgrJobSearchDiscoveryRun
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RequestParams,
		&i.RadarMeta,
		&i.RawCandidateCount,
		&i.NewCandidateCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.SqsMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobSearchDiscoveryRunProgress = `-- name: UpdateJobSearchDiscoveryRunProgress :one
UPDATE bridgr.job_search_discovery_runs
SET
    status = $2,
    raw_candidate_count = $3,
    new_candidate_count = $4,
    radar_meta = $5
WHERE id = $1
RETURNING uuid, id, user_id, status, request_params, radar_meta, raw_candidate_count, new_candidate_count, started_at, completed_at, error_code, error_detail, sqs_message_id, created_at, updated_at
`

type UpdateJobSearchDiscoveryRunProgressParams struct {
	ID                int64  `db:"id"`
	Status            string `db:"status"`
	RawCandidateCount int32  `db:"raw_candidate_count"`
	NewCandidateCount int32  `db:"new_candidate_count"`
	RadarMeta         []byte `db:"radar_meta"`
}

func (q *Queries) UpdateJobSearchDiscoveryRunProgress(ctx context.Context, arg UpdateJobSearchDiscoveryRunProgressParams) (BridgrJobSearchDiscoveryRun, error) {
	row := q.db.QueryRow(ctx, updateJobSearchDiscoveryRunProgress,
		arg.ID,
		arg.Status,
		arg.RawCandidateCount,
		arg.NewCandidateCount,
		arg.RadarMeta,
	)
	var i BridgrJobSearchDiscoveryRun
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RequestParams,
		&i.RadarMeta,
		&i.RawCandidateCount,
		&i.NewCandidateCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.SqsMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobSearchDiscoveryRunStarted = `-- name: UpdateJobSearchDiscoveryRunStarted :one
UPDATE bridgr.job_search_discovery_runs
SET
    status = $2,
    started_at = $3,
    sqs_message_id = $4
WHERE id = $1
RETURNING uuid, id, user_id, status, request_params, radar_meta, raw_candidate_count, new_candidate_count, started_at, completed_at, error_code, error_detail, sqs_message_id, created_at, updated_at
`

type UpdateJobSearchDiscoveryRunStartedParams struct {
	ID           int64            `db:"id"`
	Status       string           `db:"status"`
	StartedAt    pgtype.Timestamp `db:"started_at"`
	SqsMessageID pgtype.Text      `db:"sqs_message_id"`
}

func (q *Queries) UpdateJobSearchDiscoveryRunStarted(ctx context.Context, arg UpdateJobSearchDiscoveryRunStartedParams) (BridgrJobSearchDiscoveryRun, error) {
	row := q.db.QueryRow(ctx, updateJobSearchDiscoveryRunStarted,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.SqsMessageID,
	)
	var i BridgrJobSearchDiscoveryRun
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RequestParams,
		&i.RadarMeta,
		&i.RawCandidateCount,
		&i.NewCandidateCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.SqsMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobSearchDiscoveryRunStatus = `-- name: UpdateJobSearchDiscoveryRunStatus :one
UPDATE bridgr.job_search_discovery_runs
SET status = $2
WHERE id = $1
RETURNING uuid, id, user_id, status, request_params, radar_meta, raw_candidate_count, new_candidate_count, started_at, completed_at, error_code, error_detail, sqs_message_id, created_at, updated_at
`

type UpdateJobSearchDiscoveryRunStatusParams struct {
	ID     int64  `db:"id"`
	Status string `db:"status"`
}

func (q *Queries) UpdateJobSearchDiscoveryRunStatus(ctx context.Context, arg UpdateJobSearchDiscoveryRunStatusParams) (BridgrJobSearchDiscoveryRun, error) {
	row := q.db.QueryRow(ctx, updateJobSearchDiscoveryRunStatus, arg.ID, arg.Status)
	var i BridgrJobSearchDiscoveryRun
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RequestParams,
		&i.RadarMeta,
		&i.RawCandidateCount,
		&i.NewCandidateCount,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.SqsMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
