// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: bridgr_feed_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeedItem = `-- name: CreateFeedItem :one

INSERT INTO bridgr.feed_items (
    user_id,
    job_candidate_uuid,
    score_uuid,
    verification_uuid,
    composite_score,
    gap_severity,
    title,
    company,
    location,
    job_url,
    match_summary,
    gap_summary,
    feed_status,
    surfaced_at,
    seen_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING uuid, id, user_id, job_candidate_uuid, score_uuid, verification_uuid, composite_score, gap_severity, title, company, location, job_url, match_summary, gap_summary, feed_status, surfaced_at, seen_at, created_at, updated_at
`

type CreateFeedItemParams struct {
	UserID           int32            `db:"user_id"`
	JobCandidateUuid pgtype.UUID      `db:"job_candidate_uuid"`
	ScoreUuid        pgtype.UUID      `db:"score_uuid"`
	VerificationUuid pgtype.UUID      `db:"verification_uuid"`
	CompositeScore   float32          `db:"composite_score"`
	GapSeverity      pgtype.Text      `db:"gap_severity"`
	Title            pgtype.Text      `db:"title"`
	Company          pgtype.Text      `db:"company"`
	Location         pgtype.Text      `db:"location"`
	JobUrl           pgtype.Text      `db:"job_url"`
	MatchSummary     pgtype.Text      `db:"match_summary"`
	GapSummary       pgtype.Text      `db:"gap_summary"`
	FeedStatus       string           `db:"feed_status"`
	SurfacedAt       pgtype.Timestamp `db:"surfaced_at"`
	SeenAt           pgtype.Timestamp `db:"seen_at"`
}

// =============================================================================
// BRIDGR — FEED ITEMS
// Denormalized feed rows per (user, job_candidate). Unique (job_candidate_uuid, user_id).
// =============================================================================
func (q *Queries) CreateFeedItem(ctx context.Context, arg CreateFeedItemParams) (BridgrFeedItem, error) {
	row := q.db.QueryRow(ctx, createFeedItem,
		arg.UserID,
		arg.JobCandidateUuid,
		arg.ScoreUuid,
		arg.VerificationUuid,
		arg.CompositeScore,
		arg.GapSeverity,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.JobUrl,
		arg.MatchSummary,
		arg.GapSummary,
		arg.FeedStatus,
		arg.SurfacedAt,
		arg.SeenAt,
	)
	var i BridgrFeedItem
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.ScoreUuid,
		&i.VerificationUuid,
		&i.CompositeScore,
		&i.GapSeverity,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.JobUrl,
		&i.MatchSummary,
		&i.GapSummary,
		&i.FeedStatus,
		&i.SurfacedAt,
		&i.SeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFeedItemByID = `-- name: DeleteFeedItemByID :exec
DELETE FROM bridgr.feed_items
WHERE id = $1
`

func (q *Queries) DeleteFeedItemByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFeedItemByID, id)
	return err
}

const deleteFeedItemByUUID = `-- name: DeleteFeedItemByUUID :exec
DELETE FROM bridgr.feed_items
WHERE uuid = $1
`

func (q *Queries) DeleteFeedItemByUUID(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFeedItemByUUID, uuid)
	return err
}

const getFeedItemByID = `-- name: GetFeedItemByID :one
SELECT uuid, id, user_id, job_candidate_uuid, score_uuid, verification_uuid, composite_score, gap_severity, title, company, location, job_url, match_summary, gap_summary, feed_status, surfaced_at, seen_at, created_at, updated_at FROM bridgr.feed_items
WHERE id = $1
`

func (q *Queries) GetFeedItemByID(ctx context.Context, id int64) (BridgrFeedItem, error) {
	row := q.db.QueryRow(ctx, getFeedItemByID, id)
	var i BridgrFeedItem
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.ScoreUuid,
		&i.VerificationUuid,
		&i.CompositeScore,
		&i.GapSeverity,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.JobUrl,
		&i.MatchSummary,
		&i.GapSummary,
		&i.FeedStatus,
		&i.SurfacedAt,
		&i.SeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedItemByUUID = `-- name: GetFeedItemByUUID :one
SELECT uuid, id, user_id, job_candidate_uuid, score_uuid, verification_uuid, composite_score, gap_severity, title, company, location, job_url, match_summary, gap_summary, feed_status, surfaced_at, seen_at, created_at, updated_at FROM bridgr.feed_items
WHERE uuid = $1
`

func (q *Queries) GetFeedItemByUUID(ctx context.Context, uuid pgtype.UUID) (BridgrFeedItem, error) {
	row := q.db.QueryRow(ctx, getFeedItemByUUID, uuid)
	var i BridgrFeedItem
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.ScoreUuid,
		&i.VerificationUuid,
		&i.CompositeScore,
		&i.GapSeverity,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.JobUrl,
		&i.MatchSummary,
		&i.GapSummary,
		&i.FeedStatus,
		&i.SurfacedAt,
		&i.SeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedItemByUserAndCandidateUUID = `-- name: GetFeedItemByUserAndCandidateUUID :one
SELECT uuid, id, user_id, job_candidate_uuid, score_uuid, verification_uuid, composite_score, gap_severity, title, company, location, job_url, match_summary, gap_summary, feed_status, surfaced_at, seen_at, created_at, updated_at FROM bridgr.feed_items
WHERE user_id = $1 AND job_candidate_uuid = $2
`

type GetFeedItemByUserAndCandidateUUIDParams struct {
	UserID           int32       `db:"user_id"`
	JobCandidateUuid pgtype.UUID `db:"job_candidate_uuid"`
}

func (q *Queries) GetFeedItemByUserAndCandidateUUID(ctx context.Context, arg GetFeedItemByUserAndCandidateUUIDParams) (BridgrFeedItem, error) {
	row := q.db.QueryRow(ctx, getFeedItemByUserAndCandidateUUID, arg.UserID, arg.JobCandidateUuid)
	var i BridgrFeedItem
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.ScoreUuid,
		&i.VerificationUuid,
		&i.CompositeScore,
		&i.GapSeverity,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.JobUrl,
		&i.MatchSummary,
		&i.GapSummary,
		&i.FeedStatus,
		&i.SurfacedAt,
		&i.SeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeedItemsByUser = `-- name: ListFeedItemsByUser :many
SELECT uuid, id, user_id, job_candidate_uuid, score_uuid, verification_uuid, composite_score, gap_severity, title, company, location, job_url, match_summary, gap_summary, feed_status, surfaced_at, seen_at, created_at, updated_at FROM bridgr.feed_items
WHERE user_id = $1
ORDER BY surfaced_at DESC
LIMIT $2 OFFSET $3
`

type ListFeedItemsByUserParams struct {
	UserID int32 `db:"user_id"`
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListFeedItemsByUser(ctx context.Context, arg ListFeedItemsByUserParams) ([]BridgrFeedItem, error) {
	rows, err := q.db.Query(ctx, listFeedItemsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrFeedItem
	for rows.Next() {
		var i BridgrFeedItem
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.JobCandidateUuid,
			&i.ScoreUuid,
			&i.VerificationUuid,
			&i.CompositeScore,
			&i.GapSeverity,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.JobUrl,
			&i.MatchSummary,
			&i.GapSummary,
			&i.FeedStatus,
			&i.SurfacedAt,
			&i.SeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeedItemByID = `-- name: UpdateFeedItemByID :one
UPDATE bridgr.feed_items
SET
    score_uuid = $2,
    verification_uuid = $3,
    composite_score = $4,
    gap_severity = $5,
    title = $6,
    company = $7,
    location = $8,
    job_url = $9,
    match_summary = $10,
    gap_summary = $11,
    feed_status = $12,
    surfaced_at = $13,
    seen_at = $14
WHERE id = $1
RETURNING uuid, id, user_id, job_candidate_uuid, score_uuid, verification_uuid, composite_score, gap_severity, title, company, location, job_url, match_summary, gap_summary, feed_status, surfaced_at, seen_at, created_at, updated_at
`

type UpdateFeedItemByIDParams struct {
	ID               int64            `db:"id"`
	ScoreUuid        pgtype.UUID      `db:"score_uuid"`
	VerificationUuid pgtype.UUID      `db:"verification_uuid"`
	CompositeScore   float32          `db:"composite_score"`
	GapSeverity      pgtype.Text      `db:"gap_severity"`
	Title            pgtype.Text      `db:"title"`
	Company          pgtype.Text      `db:"company"`
	Location         pgtype.Text      `db:"location"`
	JobUrl           pgtype.Text      `db:"job_url"`
	MatchSummary     pgtype.Text      `db:"match_summary"`
	GapSummary       pgtype.Text      `db:"gap_summary"`
	FeedStatus       string           `db:"feed_status"`
	SurfacedAt       pgtype.Timestamp `db:"surfaced_at"`
	SeenAt           pgtype.Timestamp `db:"seen_at"`
}

func (q *Queries) UpdateFeedItemByID(ctx context.Context, arg UpdateFeedItemByIDParams) (BridgrFeedItem, error) {
	row := q.db.QueryRow(ctx, updateFeedItemByID,
		arg.ID,
		arg.ScoreUuid,
		arg.VerificationUuid,
		arg.CompositeScore,
		arg.GapSeverity,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.JobUrl,
		arg.MatchSummary,
		arg.GapSummary,
		arg.FeedStatus,
		arg.SurfacedAt,
		arg.SeenAt,
	)
	var i BridgrFeedItem
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.ScoreUuid,
		&i.VerificationUuid,
		&i.CompositeScore,
		&i.GapSeverity,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.JobUrl,
		&i.MatchSummary,
		&i.GapSummary,
		&i.FeedStatus,
		&i.SurfacedAt,
		&i.SeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFeedItem = `-- name: UpsertFeedItem :one
INSERT INTO bridgr.feed_items (
    user_id,
    job_candidate_uuid,
    score_uuid,
    verification_uuid,
    composite_score,
    gap_severity,
    title,
    company,
    location,
    job_url,
    match_summary,
    gap_summary,
    feed_status,
    surfaced_at,
    seen_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
ON CONFLICT (job_candidate_uuid, user_id) DO UPDATE SET
    score_uuid = EXCLUDED.score_uuid,
    verification_uuid = EXCLUDED.verification_uuid,
    composite_score = EXCLUDED.composite_score,
    gap_severity = EXCLUDED.gap_severity,
    title = EXCLUDED.title,
    company = EXCLUDED.company,
    location = EXCLUDED.location,
    job_url = EXCLUDED.job_url,
    match_summary = EXCLUDED.match_summary,
    gap_summary = EXCLUDED.gap_summary,
    feed_status = EXCLUDED.feed_status,
    surfaced_at = EXCLUDED.surfaced_at,
    seen_at = EXCLUDED.seen_at
RETURNING uuid, id, user_id, job_candidate_uuid, score_uuid, verification_uuid, composite_score, gap_severity, title, company, location, job_url, match_summary, gap_summary, feed_status, surfaced_at, seen_at, created_at, updated_at
`

type UpsertFeedItemParams struct {
	UserID           int32            `db:"user_id"`
	JobCandidateUuid pgtype.UUID      `db:"job_candidate_uuid"`
	ScoreUuid        pgtype.UUID      `db:"score_uuid"`
	VerificationUuid pgtype.UUID      `db:"verification_uuid"`
	CompositeScore   float32          `db:"composite_score"`
	GapSeverity      pgtype.Text      `db:"gap_severity"`
	Title            pgtype.Text      `db:"title"`
	Company          pgtype.Text      `db:"company"`
	Location         pgtype.Text      `db:"location"`
	JobUrl           pgtype.Text      `db:"job_url"`
	MatchSummary     pgtype.Text      `db:"match_summary"`
	GapSummary       pgtype.Text      `db:"gap_summary"`
	FeedStatus       string           `db:"feed_status"`
	SurfacedAt       pgtype.Timestamp `db:"surfaced_at"`
	SeenAt           pgtype.Timestamp `db:"seen_at"`
}

func (q *Queries) UpsertFeedItem(ctx context.Context, arg UpsertFeedItemParams) (BridgrFeedItem, error) {
	row := q.db.QueryRow(ctx, upsertFeedItem,
		arg.UserID,
		arg.JobCandidateUuid,
		arg.ScoreUuid,
		arg.VerificationUuid,
		arg.CompositeScore,
		arg.GapSeverity,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.JobUrl,
		arg.MatchSummary,
		arg.GapSummary,
		arg.FeedStatus,
		arg.SurfacedAt,
		arg.SeenAt,
	)
	var i BridgrFeedItem
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.ScoreUuid,
		&i.VerificationUuid,
		&i.CompositeScore,
		&i.GapSeverity,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.JobUrl,
		&i.MatchSummary,
		&i.GapSummary,
		&i.FeedStatus,
		&i.SurfacedAt,
		&i.SeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
