// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: bridgr_job_harvest_schedules.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJobHarvestSchedule = `-- name: CreateJobHarvestSchedule :one

INSERT INTO bridgr.job_harvest_schedules (
    user_id,
    profile_uuid,
    enabled,
    cadence_minutes,
    boards_rotation,
    last_run_at,
    next_run_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING uuid, id, user_id, profile_uuid, enabled, cadence_minutes, boards_rotation, last_run_at, next_run_at, created_at, updated_at
`

type CreateJobHarvestScheduleParams struct {
	UserID         int32            `db:"user_id"`
	ProfileUuid    pgtype.UUID      `db:"profile_uuid"`
	Enabled        bool             `db:"enabled"`
	CadenceMinutes int32            `db:"cadence_minutes"`
	BoardsRotation []byte           `db:"boards_rotation"`
	LastRunAt      pgtype.Timestamp `db:"last_run_at"`
	NextRunAt      pgtype.Timestamp `db:"next_run_at"`
}

// =============================================================================
// BRIDGR — JOB HARVEST SCHEDULES
// Per-user cadence + board rotation for a job_search_profile.
// =============================================================================
func (q *Queries) CreateJobHarvestSchedule(ctx context.Context, arg CreateJobHarvestScheduleParams) (BridgrJobHarvestSchedule, error) {
	row := q.db.QueryRow(ctx, createJobHarvestSchedule,
		arg.UserID,
		arg.ProfileUuid,
		arg.Enabled,
		arg.CadenceMinutes,
		arg.BoardsRotation,
		arg.LastRunAt,
		arg.NextRunAt,
	)
	var i BridgrJobHarvestSchedule
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.ProfileUuid,
		&i.Enabled,
		&i.CadenceMinutes,
		&i.BoardsRotation,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJobHarvestScheduleByID = `-- name: DeleteJobHarvestScheduleByID :exec
DELETE FROM bridgr.job_harvest_schedules
WHERE id = $1
`

func (q *Queries) DeleteJobHarvestScheduleByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteJobHarvestScheduleByID, id)
	return err
}

const deleteJobHarvestScheduleByUUID = `-- name: DeleteJobHarvestScheduleByUUID :exec
DELETE FROM bridgr.job_harvest_schedules
WHERE uuid = $1
`

func (q *Queries) DeleteJobHarvestScheduleByUUID(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJobHarvestScheduleByUUID, uuid)
	return err
}

const getJobHarvestScheduleByID = `-- name: GetJobHarvestScheduleByID :one
SELECT uuid, id, user_id, profile_uuid, enabled, cadence_minutes, boards_rotation, last_run_at, next_run_at, created_at, updated_at FROM bridgr.job_harvest_schedules
WHERE id = $1
`

func (q *Queries) GetJobHarvestScheduleByID(ctx context.Context, id int64) (BridgrJobHarvestSchedule, error) {
	row := q.db.QueryRow(ctx, getJobHarvestScheduleByID, id)
	var i BridgrJobHarvestSchedule
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.ProfileUuid,
		&i.Enabled,
		&i.CadenceMinutes,
		&i.BoardsRotation,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobHarvestScheduleByUUID = `-- name: GetJobHarvestScheduleByUUID :one
SELECT uuid, id, user_id, profile_uuid, enabled, cadence_minutes, boards_rotation, last_run_at, next_run_at, created_at, updated_at FROM bridgr.job_harvest_schedules
WHERE uuid = $1
`

func (q *Queries) GetJobHarvestScheduleByUUID(ctx context.Context, uuid pgtype.UUID) (BridgrJobHarvestSchedule, error) {
	row := q.db.QueryRow(ctx, getJobHarvestScheduleByUUID, uuid)
	var i BridgrJobHarvestSchedule
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.ProfileUuid,
		&i.Enabled,
		&i.CadenceMinutes,
		&i.BoardsRotation,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobHarvestScheduleByUserAndProfileUUID = `-- name: GetJobHarvestScheduleByUserAndProfileUUID :one
SELECT uuid, id, user_id, profile_uuid, enabled, cadence_minutes, boards_rotation, last_run_at, next_run_at, created_at, updated_at FROM bridgr.job_harvest_schedules
WHERE user_id = $1 AND profile_uuid = $2
`

type GetJobHarvestScheduleByUserAndProfileUUIDParams struct {
	UserID      int32       `db:"user_id"`
	ProfileUuid pgtype.UUID `db:"profile_uuid"`
}

func (q *Queries) GetJobHarvestScheduleByUserAndProfileUUID(ctx context.Context, arg GetJobHarvestScheduleByUserAndProfileUUIDParams) (BridgrJobHarvestSchedule, error) {
	row := q.db.QueryRow(ctx, getJobHarvestScheduleByUserAndProfileUUID, arg.UserID, arg.ProfileUuid)
	var i BridgrJobHarvestSchedule
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.ProfileUuid,
		&i.Enabled,
		&i.CadenceMinutes,
		&i.BoardsRotation,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobHarvestSchedulesByUser = `-- name: ListJobHarvestSchedulesByUser :many
SELECT uuid, id, user_id, profile_uuid, enabled, cadence_minutes, boards_rotation, last_run_at, next_run_at, created_at, updated_at FROM bridgr.job_harvest_schedules
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListJobHarvestSchedulesByUser(ctx context.Context, userID int32) ([]BridgrJobHarvestSchedule, error) {
	rows, err := q.db.Query(ctx, listJobHarvestSchedulesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrJobHarvestSchedule
	for rows.Next() {
		var i BridgrJobHarvestSchedule
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.ProfileUuid,
			&i.Enabled,
			&i.CadenceMinutes,
			&i.BoardsRotation,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobHarvestSchedulesDue = `-- name: ListJobHarvestSchedulesDue :many
SELECT uuid, id, user_id, profile_uuid, enabled, cadence_minutes, boards_rotation, last_run_at, next_run_at, created_at, updated_at FROM bridgr.job_harvest_schedules
WHERE enabled = true
  AND next_run_at IS NOT NULL
  AND next_run_at <= now()
ORDER BY next_run_at ASC
`

// Scheduler: enabled schedules whose next_run_at is set and not in the future.
func (q *Queries) ListJobHarvestSchedulesDue(ctx context.Context) ([]BridgrJobHarvestSchedule, error) {
	rows, err := q.db.Query(ctx, listJobHarvestSchedulesDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrJobHarvestSchedule
	for rows.Next() {
		var i BridgrJobHarvestSchedule
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.ProfileUuid,
			&i.Enabled,
			&i.CadenceMinutes,
			&i.BoardsRotation,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobHarvestScheduleByID = `-- name: UpdateJobHarvestScheduleByID :one
UPDATE bridgr.job_harvest_schedules
SET
    enabled = $2,
    cadence_minutes = $3,
    boards_rotation = $4,
    last_run_at = $5,
    next_run_at = $6
WHERE id = $1
RETURNING uuid, id, user_id, profile_uuid, enabled, cadence_minutes, boards_rotation, last_run_at, next_run_at, created_at, updated_at
`

type UpdateJobHarvestScheduleByIDParams struct {
	ID             int64            `db:"id"`
	Enabled        bool             `db:"enabled"`
	CadenceMinutes int32            `db:"cadence_minutes"`
	BoardsRotation []byte           `db:"boards_rotation"`
	LastRunAt      pgtype.Timestamp `db:"last_run_at"`
	NextRunAt      pgtype.Timestamp `db:"next_run_at"`
}

func (q *Queries) UpdateJobHarvestScheduleByID(ctx context.Context, arg UpdateJobHarvestScheduleByIDParams) (BridgrJobHarvestSchedule, error) {
	row := q.db.QueryRow(ctx, updateJobHarvestScheduleByID,
		arg.ID,
		arg.Enabled,
		arg.CadenceMinutes,
		arg.BoardsRotation,
		arg.LastRunAt,
		arg.NextRunAt,
	)
	var i BridgrJobHarvestSchedule
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.ProfileUuid,
		&i.Enabled,
		&i.CadenceMinutes,
		&i.BoardsRotation,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
