// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: bridgr_skill_gap_path_steps.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateSkillGapPathStepsParams struct {
	PathUuid                pgtype.UUID    `db:"path_uuid"`
	StepIndex               int32          `db:"step_index"`
	Title                   string         `db:"title"`
	Rationale               pgtype.Text    `db:"rationale"`
	EstimatedHours          pgtype.Numeric `db:"estimated_hours"`
	ResourceUri             pgtype.Text    `db:"resource_uri"`
	ResourceKind            pgtype.Text    `db:"resource_kind"`
	FounderLearningItemUuid pgtype.UUID    `db:"founder_learning_item_uuid"`
	CourseLessonUuid        pgtype.UUID    `db:"course_lesson_uuid"`
	LinkedNodeKeys          []byte         `db:"linked_node_keys"`
	Metadata                []byte         `db:"metadata"`
}

const createSkillGapPathStep = `-- name: CreateSkillGapPathStep :one

INSERT INTO hskip_users.bridgr_skill_gap_path_steps (
    path_uuid,
    step_index,
    title,
    rationale,
    estimated_hours,
    resource_uri,
    resource_kind,
    founder_learning_item_uuid,
    course_lesson_uuid,
    linked_node_keys,
    metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING uuid, id, path_uuid, step_index, title, rationale, estimated_hours, resource_uri, resource_kind, founder_learning_item_uuid, course_lesson_uuid, linked_node_keys, metadata, created_at, updated_at
`

type CreateSkillGapPathStepParams struct {
	PathUuid                pgtype.UUID    `db:"path_uuid"`
	StepIndex               int32          `db:"step_index"`
	Title                   string         `db:"title"`
	Rationale               pgtype.Text    `db:"rationale"`
	EstimatedHours          pgtype.Numeric `db:"estimated_hours"`
	ResourceUri             pgtype.Text    `db:"resource_uri"`
	ResourceKind            pgtype.Text    `db:"resource_kind"`
	FounderLearningItemUuid pgtype.UUID    `db:"founder_learning_item_uuid"`
	CourseLessonUuid        pgtype.UUID    `db:"course_lesson_uuid"`
	LinkedNodeKeys          []byte         `db:"linked_node_keys"`
	Metadata                []byte         `db:"metadata"`
}

// =============================================================================
// BRIDGR SKILL GAP — PATH STEPS
// Ordered steps inside a learning path.
// =============================================================================
func (q *Queries) CreateSkillGapPathStep(ctx context.Context, arg CreateSkillGapPathStepParams) (HskipUsersBridgrSkillGapPathStep, error) {
	row := q.db.QueryRow(ctx, createSkillGapPathStep,
		arg.PathUuid,
		arg.StepIndex,
		arg.Title,
		arg.Rationale,
		arg.EstimatedHours,
		arg.ResourceUri,
		arg.ResourceKind,
		arg.FounderLearningItemUuid,
		arg.CourseLessonUuid,
		arg.LinkedNodeKeys,
		arg.Metadata,
	)
	var i HskipUsersBridgrSkillGapPathStep
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.PathUuid,
		&i.StepIndex,
		&i.Title,
		&i.Rationale,
		&i.EstimatedHours,
		&i.ResourceUri,
		&i.ResourceKind,
		&i.FounderLearningItemUuid,
		&i.CourseLessonUuid,
		&i.LinkedNodeKeys,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkillGapPathStepsByPath = `-- name: DeleteSkillGapPathStepsByPath :exec
DELETE FROM hskip_users.bridgr_skill_gap_path_steps
WHERE path_uuid = $1
`

func (q *Queries) DeleteSkillGapPathStepsByPath(ctx context.Context, pathUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkillGapPathStepsByPath, pathUuid)
	return err
}

const getSkillGapPathStep = `-- name: GetSkillGapPathStep :one
SELECT uuid, id, path_uuid, step_index, title, rationale, estimated_hours, resource_uri, resource_kind, founder_learning_item_uuid, course_lesson_uuid, linked_node_keys, metadata, created_at, updated_at FROM hskip_users.bridgr_skill_gap_path_steps
WHERE id = $1
`

func (q *Queries) GetSkillGapPathStep(ctx context.Context, id int64) (HskipUsersBridgrSkillGapPathStep, error) {
	row := q.db.QueryRow(ctx, getSkillGapPathStep, id)
	var i HskipUsersBridgrSkillGapPathStep
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.PathUuid,
		&i.StepIndex,
		&i.Title,
		&i.Rationale,
		&i.EstimatedHours,
		&i.ResourceUri,
		&i.ResourceKind,
		&i.FounderLearningItemUuid,
		&i.CourseLessonUuid,
		&i.LinkedNodeKeys,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSkillGapPathStepsByPath = `-- name: ListSkillGapPathStepsByPath :many
SELECT uuid, id, path_uuid, step_index, title, rationale, estimated_hours, resource_uri, resource_kind, founder_learning_item_uuid, course_lesson_uuid, linked_node_keys, metadata, created_at, updated_at FROM hskip_users.bridgr_skill_gap_path_steps
WHERE path_uuid = $1
ORDER BY step_index ASC
`

func (q *Queries) ListSkillGapPathStepsByPath(ctx context.Context, pathUuid pgtype.UUID) ([]HskipUsersBridgrSkillGapPathStep, error) {
	rows, err := q.db.Query(ctx, listSkillGapPathStepsByPath, pathUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HskipUsersBridgrSkillGapPathStep
	for rows.Next() {
		var i HskipUsersBridgrSkillGapPathStep
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.PathUuid,
			&i.StepIndex,
			&i.Title,
			&i.Rationale,
			&i.EstimatedHours,
			&i.ResourceUri,
			&i.ResourceKind,
			&i.FounderLearningItemUuid,
			&i.CourseLessonUuid,
			&i.LinkedNodeKeys,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkillGapPathStep = `-- name: UpdateSkillGapPathStep :one
UPDATE hskip_users.bridgr_skill_gap_path_steps
SET resource_uri = $2,
    resource_kind = $3
WHERE id = $1
RETURNING uuid, id, path_uuid, step_index, title, rationale, estimated_hours, resource_uri, resource_kind, founder_learning_item_uuid, course_lesson_uuid, linked_node_keys, metadata, created_at, updated_at
`

type UpdateSkillGapPathStepParams struct {
	ID           int64       `db:"id"`
	ResourceUri  pgtype.Text `db:"resource_uri"`
	ResourceKind pgtype.Text `db:"resource_kind"`
}

func (q *Queries) UpdateSkillGapPathStep(ctx context.Context, arg UpdateSkillGapPathStepParams) (HskipUsersBridgrSkillGapPathStep, error) {
	row := q.db.QueryRow(ctx, updateSkillGapPathStep, arg.ID, arg.ResourceUri, arg.ResourceKind)
	var i HskipUsersBridgrSkillGapPathStep
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.PathUuid,
		&i.StepIndex,
		&i.Title,
		&i.Rationale,
		&i.EstimatedHours,
		&i.ResourceUri,
		&i.ResourceKind,
		&i.FounderLearningItemUuid,
		&i.CourseLessonUuid,
		&i.LinkedNodeKeys,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
