// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: bridgr_job_candidates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteJobCandidateByID = `-- name: DeleteJobCandidateByID :exec
DELETE FROM bridgr.job_candidates
WHERE id = $1
`

func (q *Queries) DeleteJobCandidateByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteJobCandidateByID, id)
	return err
}

const deleteJobCandidateByUUID = `-- name: DeleteJobCandidateByUUID :exec
DELETE FROM bridgr.job_candidates
WHERE uuid = $1
`

func (q *Queries) DeleteJobCandidateByUUID(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJobCandidateByUUID, uuid)
	return err
}

const getJobCandidateByID = `-- name: GetJobCandidateByID :one
SELECT uuid, id, user_id, discovery_run_uuid, source_board, source_job_id, job_url, url_hash, content_hash, title, company, location, jd_text, jd_s3_uri, fetched_at, ingestion_status, radar_payload, application_url, created_at, updated_at FROM bridgr.job_candidates
WHERE id = $1
`

func (q *Queries) GetJobCandidateByID(ctx context.Context, id int64) (BridgrJobCandidate, error) {
	row := q.db.QueryRow(ctx, getJobCandidateByID, id)
	var i BridgrJobCandidate
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.DiscoveryRunUuid,
		&i.SourceBoard,
		&i.SourceJobID,
		&i.JobUrl,
		&i.UrlHash,
		&i.ContentHash,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.JdText,
		&i.JdS3Uri,
		&i.FetchedAt,
		&i.IngestionStatus,
		&i.RadarPayload,
		&i.ApplicationUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobCandidateByUUID = `-- name: GetJobCandidateByUUID :one
SELECT uuid, id, user_id, discovery_run_uuid, source_board, source_job_id, job_url, url_hash, content_hash, title, company, location, jd_text, jd_s3_uri, fetched_at, ingestion_status, radar_payload, application_url, created_at, updated_at FROM bridgr.job_candidates
WHERE uuid = $1
`

func (q *Queries) GetJobCandidateByUUID(ctx context.Context, uuid pgtype.UUID) (BridgrJobCandidate, error) {
	row := q.db.QueryRow(ctx, getJobCandidateByUUID, uuid)
	var i BridgrJobCandidate
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.DiscoveryRunUuid,
		&i.SourceBoard,
		&i.SourceJobID,
		&i.JobUrl,
		&i.UrlHash,
		&i.ContentHash,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.JdText,
		&i.JdS3Uri,
		&i.FetchedAt,
		&i.IngestionStatus,
		&i.RadarPayload,
		&i.ApplicationUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobCandidateByUserAndURLHash = `-- name: GetJobCandidateByUserAndURLHash :one
SELECT uuid, id, user_id, discovery_run_uuid, source_board, source_job_id, job_url, url_hash, content_hash, title, company, location, jd_text, jd_s3_uri, fetched_at, ingestion_status, radar_payload, application_url, created_at, updated_at FROM bridgr.job_candidates
WHERE user_id = $1 AND url_hash = $2
`

type GetJobCandidateByUserAndURLHashParams struct {
	UserID  int32  `db:"user_id"`
	UrlHash string `db:"url_hash"`
}

func (q *Queries) GetJobCandidateByUserAndURLHash(ctx context.Context, arg GetJobCandidateByUserAndURLHashParams) (BridgrJobCandidate, error) {
	row := q.db.QueryRow(ctx, getJobCandidateByUserAndURLHash, arg.UserID, arg.UrlHash)
	var i BridgrJobCandidate
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.DiscoveryRunUuid,
		&i.SourceBoard,
		&i.SourceJobID,
		&i.JobUrl,
		&i.UrlHash,
		&i.ContentHash,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.JdText,
		&i.JdS3Uri,
		&i.FetchedAt,
		&i.IngestionStatus,
		&i.RadarPayload,
		&i.ApplicationUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertJobCandidate = `-- name: InsertJobCandidate :one

INSERT INTO bridgr.job_candidates (
    user_id,
    discovery_run_uuid,
    source_board,
    source_job_id,
    job_url,
    url_hash,
    content_hash,
    title,
    company,
    location,
    jd_text,
    jd_s3_uri,
    fetched_at,
    ingestion_status,
    radar_payload,
    application_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING uuid, id, user_id, discovery_run_uuid, source_board, source_job_id, job_url, url_hash, content_hash, title, company, location, jd_text, jd_s3_uri, fetched_at, ingestion_status, radar_payload, application_url, created_at, updated_at
`

type InsertJobCandidateParams struct {
	UserID           int32            `db:"user_id"`
	DiscoveryRunUuid pgtype.UUID      `db:"discovery_run_uuid"`
	SourceBoard      string           `db:"source_board"`
	SourceJobID      pgtype.Text      `db:"source_job_id"`
	JobUrl           string           `db:"job_url"`
	UrlHash          string           `db:"url_hash"`
	ContentHash      pgtype.Text      `db:"content_hash"`
	Title            pgtype.Text      `db:"title"`
	Company          pgtype.Text      `db:"company"`
	Location         pgtype.Text      `db:"location"`
	JdText           pgtype.Text      `db:"jd_text"`
	JdS3Uri          pgtype.Text      `db:"jd_s3_uri"`
	FetchedAt        pgtype.Timestamp `db:"fetched_at"`
	IngestionStatus  string           `db:"ingestion_status"`
	RadarPayload     []byte           `db:"radar_payload"`
	ApplicationUrl   pgtype.Text      `db:"application_url"`
}

// =============================================================================
// BRIDGR JOB DISCOVERY — JOB CANDIDATES
// Deduped postings per user. (user_id, url_hash) unique.
// =============================================================================
func (q *Queries) InsertJobCandidate(ctx context.Context, arg InsertJobCandidateParams) (BridgrJobCandidate, error) {
	row := q.db.QueryRow(ctx, insertJobCandidate,
		arg.UserID,
		arg.DiscoveryRunUuid,
		arg.SourceBoard,
		arg.SourceJobID,
		arg.JobUrl,
		arg.UrlHash,
		arg.ContentHash,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.JdText,
		arg.JdS3Uri,
		arg.FetchedAt,
		arg.IngestionStatus,
		arg.RadarPayload,
		arg.ApplicationUrl,
	)
	var i BridgrJobCandidate
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.DiscoveryRunUuid,
		&i.SourceBoard,
		&i.SourceJobID,
		&i.JobUrl,
		&i.UrlHash,
		&i.ContentHash,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.JdText,
		&i.JdS3Uri,
		&i.FetchedAt,
		&i.IngestionStatus,
		&i.RadarPayload,
		&i.ApplicationUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobCandidatesByDiscoveryRunUUID = `-- name: ListJobCandidatesByDiscoveryRunUUID :many
SELECT uuid, id, user_id, discovery_run_uuid, source_board, source_job_id, job_url, url_hash, content_hash, title, company, location, jd_text, jd_s3_uri, fetched_at, ingestion_status, radar_payload, application_url, created_at, updated_at FROM bridgr.job_candidates
WHERE discovery_run_uuid = $1
ORDER BY created_at ASC
`

func (q *Queries) ListJobCandidatesByDiscoveryRunUUID(ctx context.Context, discoveryRunUuid pgtype.UUID) ([]BridgrJobCandidate, error) {
	rows, err := q.db.Query(ctx, listJobCandidatesByDiscoveryRunUUID, discoveryRunUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrJobCandidate
	for rows.Next() {
		var i BridgrJobCandidate
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.DiscoveryRunUuid,
			&i.SourceBoard,
			&i.SourceJobID,
			&i.JobUrl,
			&i.UrlHash,
			&i.ContentHash,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.JdText,
			&i.JdS3Uri,
			&i.FetchedAt,
			&i.IngestionStatus,
			&i.RadarPayload,
			&i.ApplicationUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobCandidatesByUser = `-- name: ListJobCandidatesByUser :many
SELECT uuid, id, user_id, discovery_run_uuid, source_board, source_job_id, job_url, url_hash, content_hash, title, company, location, jd_text, jd_s3_uri, fetched_at, ingestion_status, radar_payload, application_url, created_at, updated_at FROM bridgr.job_candidates
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobCandidatesByUserParams struct {
	UserID int32 `db:"user_id"`
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListJobCandidatesByUser(ctx context.Context, arg ListJobCandidatesByUserParams) ([]BridgrJobCandidate, error) {
	rows, err := q.db.Query(ctx, listJobCandidatesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrJobCandidate
	for rows.Next() {
		var i BridgrJobCandidate
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.DiscoveryRunUuid,
			&i.SourceBoard,
			&i.SourceJobID,
			&i.JobUrl,
			&i.UrlHash,
			&i.ContentHash,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.JdText,
			&i.JdS3Uri,
			&i.FetchedAt,
			&i.IngestionStatus,
			&i.RadarPayload,
			&i.ApplicationUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobCandidatesByUserFiltered = `-- name: ListJobCandidatesByUserFiltered :many
SELECT uuid, id, user_id, discovery_run_uuid, source_board, source_job_id, job_url, url_hash, content_hash, title, company, location, jd_text, jd_s3_uri, fetched_at, ingestion_status, radar_payload, application_url, created_at, updated_at FROM bridgr.job_candidates AS c
WHERE c.user_id = $1
  AND ($2::uuid IS NULL OR c.discovery_run_uuid = $2::uuid)
  AND ($3::text IS NULL OR $3::text = '' OR c.ingestion_status = $3::text)
  AND ($4::text IS NULL OR $4::text = '' OR c.source_board = $4::text)
ORDER BY c.created_at DESC
LIMIT $6 OFFSET $5
`

type ListJobCandidatesByUserFilteredParams struct {
	UserID           int32       `db:"user_id"`
	DiscoveryRunUuid pgtype.UUID `db:"discovery_run_uuid"`
	IngestionStatus  pgtype.Text `db:"ingestion_status"`
	SourceBoard      pgtype.Text `db:"source_board"`
	Offset           int32       `db:"offset"`
	Limit            int32       `db:"limit"`
}

func (q *Queries) ListJobCandidatesByUserFiltered(ctx context.Context, arg ListJobCandidatesByUserFilteredParams) ([]BridgrJobCandidate, error) {
	rows, err := q.db.Query(ctx, listJobCandidatesByUserFiltered,
		arg.UserID,
		arg.DiscoveryRunUuid,
		arg.IngestionStatus,
		arg.SourceBoard,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrJobCandidate
	for rows.Next() {
		var i BridgrJobCandidate
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.DiscoveryRunUuid,
			&i.SourceBoard,
			&i.SourceJobID,
			&i.JobUrl,
			&i.UrlHash,
			&i.ContentHash,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.JdText,
			&i.JdS3Uri,
			&i.FetchedAt,
			&i.IngestionStatus,
			&i.RadarPayload,
			&i.ApplicationUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobCandidateByID = `-- name: UpdateJobCandidateByID :one
UPDATE bridgr.job_candidates
SET
    discovery_run_uuid = $2,
    source_board = $3,
    source_job_id = $4,
    job_url = $5,
    url_hash = $6,
    content_hash = $7,
    title = $8,
    company = $9,
    location = $10,
    jd_text = $11,
    jd_s3_uri = $12,
    fetched_at = $13,
    ingestion_status = $14,
    radar_payload = $15,
    application_url = $16
WHERE id = $1
RETURNING uuid, id, user_id, discovery_run_uuid, source_board, source_job_id, job_url, url_hash, content_hash, title, company, location, jd_text, jd_s3_uri, fetched_at, ingestion_status, radar_payload, application_url, created_at, updated_at
`

type UpdateJobCandidateByIDParams struct {
	ID               int64            `db:"id"`
	DiscoveryRunUuid pgtype.UUID      `db:"discovery_run_uuid"`
	SourceBoard      string           `db:"source_board"`
	SourceJobID      pgtype.Text      `db:"source_job_id"`
	JobUrl           string           `db:"job_url"`
	UrlHash          string           `db:"url_hash"`
	ContentHash      pgtype.Text      `db:"content_hash"`
	Title            pgtype.Text      `db:"title"`
	Company          pgtype.Text      `db:"company"`
	Location         pgtype.Text      `db:"location"`
	JdText           pgtype.Text      `db:"jd_text"`
	JdS3Uri          pgtype.Text      `db:"jd_s3_uri"`
	FetchedAt        pgtype.Timestamp `db:"fetched_at"`
	IngestionStatus  string           `db:"ingestion_status"`
	RadarPayload     []byte           `db:"radar_payload"`
	ApplicationUrl   pgtype.Text      `db:"application_url"`
}

func (q *Queries) UpdateJobCandidateByID(ctx context.Context, arg UpdateJobCandidateByIDParams) (BridgrJobCandidate, error) {
	row := q.db.QueryRow(ctx, updateJobCandidateByID,
		arg.ID,
		arg.DiscoveryRunUuid,
		arg.SourceBoard,
		arg.SourceJobID,
		arg.JobUrl,
		arg.UrlHash,
		arg.ContentHash,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.JdText,
		arg.JdS3Uri,
		arg.FetchedAt,
		arg.IngestionStatus,
		arg.RadarPayload,
		arg.ApplicationUrl,
	)
	var i BridgrJobCandidate
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.DiscoveryRunUuid,
		&i.SourceBoard,
		&i.SourceJobID,
		&i.JobUrl,
		&i.UrlHash,
		&i.ContentHash,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.JdText,
		&i.JdS3Uri,
		&i.FetchedAt,
		&i.IngestionStatus,
		&i.RadarPayload,
		&i.ApplicationUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobCandidateIngestion = `-- name: UpdateJobCandidateIngestion :one
UPDATE bridgr.job_candidates
SET
    jd_text = $2,
    jd_s3_uri = $3,
    content_hash = $4,
    fetched_at = $5,
    ingestion_status = $6,
    radar_payload = $7
WHERE id = $1
RETURNING uuid, id, user_id, discovery_run_uuid, source_board, source_job_id, job_url, url_hash, content_hash, title, company, location, jd_text, jd_s3_uri, fetched_at, ingestion_status, radar_payload, application_url, created_at, updated_at
`

type UpdateJobCandidateIngestionParams struct {
	ID              int64            `db:"id"`
	JdText          pgtype.Text      `db:"jd_text"`
	JdS3Uri         pgtype.Text      `db:"jd_s3_uri"`
	ContentHash     pgtype.Text      `db:"content_hash"`
	FetchedAt       pgtype.Timestamp `db:"fetched_at"`
	IngestionStatus string           `db:"ingestion_status"`
	RadarPayload    []byte           `db:"radar_payload"`
}

func (q *Queries) UpdateJobCandidateIngestion(ctx context.Context, arg UpdateJobCandidateIngestionParams) (BridgrJobCandidate, error) {
	row := q.db.QueryRow(ctx, updateJobCandidateIngestion,
		arg.ID,
		arg.JdText,
		arg.JdS3Uri,
		arg.ContentHash,
		arg.FetchedAt,
		arg.IngestionStatus,
		arg.RadarPayload,
	)
	var i BridgrJobCandidate
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.DiscoveryRunUuid,
		&i.SourceBoard,
		&i.SourceJobID,
		&i.JobUrl,
		&i.UrlHash,
		&i.ContentHash,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.JdText,
		&i.JdS3Uri,
		&i.FetchedAt,
		&i.IngestionStatus,
		&i.RadarPayload,
		&i.ApplicationUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertJobCandidate = `-- name: UpsertJobCandidate :one
INSERT INTO bridgr.job_candidates (
    user_id,
    discovery_run_uuid,
    source_board,
    source_job_id,
    job_url,
    url_hash,
    content_hash,
    title,
    company,
    location,
    jd_text,
    jd_s3_uri,
    fetched_at,
    ingestion_status,
    radar_payload,
    application_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
ON CONFLICT (user_id, url_hash) DO UPDATE SET
    discovery_run_uuid = COALESCE(EXCLUDED.discovery_run_uuid, bridgr.job_candidates.discovery_run_uuid),
    source_board = EXCLUDED.source_board,
    source_job_id = EXCLUDED.source_job_id,
    job_url = EXCLUDED.job_url,
    content_hash = COALESCE(EXCLUDED.content_hash, bridgr.job_candidates.content_hash),
    title = COALESCE(EXCLUDED.title, bridgr.job_candidates.title),
    company = COALESCE(EXCLUDED.company, bridgr.job_candidates.company),
    location = COALESCE(EXCLUDED.location, bridgr.job_candidates.location),
    jd_text = COALESCE(EXCLUDED.jd_text, bridgr.job_candidates.jd_text),
    jd_s3_uri = COALESCE(EXCLUDED.jd_s3_uri, bridgr.job_candidates.jd_s3_uri),
    fetched_at = COALESCE(EXCLUDED.fetched_at, bridgr.job_candidates.fetched_at),
    ingestion_status = EXCLUDED.ingestion_status,
    radar_payload = EXCLUDED.radar_payload,
    application_url = COALESCE(EXCLUDED.application_url, bridgr.job_candidates.application_url)
RETURNING uuid, id, user_id, discovery_run_uuid, source_board, source_job_id, job_url, url_hash, content_hash, title, company, location, jd_text, jd_s3_uri, fetched_at, ingestion_status, radar_payload, application_url, created_at, updated_at
`

type UpsertJobCandidateParams struct {
	UserID           int32            `db:"user_id"`
	DiscoveryRunUuid pgtype.UUID      `db:"discovery_run_uuid"`
	SourceBoard      string           `db:"source_board"`
	SourceJobID      pgtype.Text      `db:"source_job_id"`
	JobUrl           string           `db:"job_url"`
	UrlHash          string           `db:"url_hash"`
	ContentHash      pgtype.Text      `db:"content_hash"`
	Title            pgtype.Text      `db:"title"`
	Company          pgtype.Text      `db:"company"`
	Location         pgtype.Text      `db:"location"`
	JdText           pgtype.Text      `db:"jd_text"`
	JdS3Uri          pgtype.Text      `db:"jd_s3_uri"`
	FetchedAt        pgtype.Timestamp `db:"fetched_at"`
	IngestionStatus  string           `db:"ingestion_status"`
	RadarPayload     []byte           `db:"radar_payload"`
	ApplicationUrl   pgtype.Text      `db:"application_url"`
}

func (q *Queries) UpsertJobCandidate(ctx context.Context, arg UpsertJobCandidateParams) (BridgrJobCandidate, error) {
	row := q.db.QueryRow(ctx, upsertJobCandidate,
		arg.UserID,
		arg.DiscoveryRunUuid,
		arg.SourceBoard,
		arg.SourceJobID,
		arg.JobUrl,
		arg.UrlHash,
		arg.ContentHash,
		arg.Title,
		arg.Company,
		arg.Location,
		arg.JdText,
		arg.JdS3Uri,
		arg.FetchedAt,
		arg.IngestionStatus,
		arg.RadarPayload,
		arg.ApplicationUrl,
	)
	var i BridgrJobCandidate
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.DiscoveryRunUuid,
		&i.SourceBoard,
		&i.SourceJobID,
		&i.JobUrl,
		&i.UrlHash,
		&i.ContentHash,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.JdText,
		&i.JdS3Uri,
		&i.FetchedAt,
		&i.IngestionStatus,
		&i.RadarPayload,
		&i.ApplicationUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
