// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: bridgr_skill_gap_coverage.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSkillGapCoverage = `-- name: GetSkillGapCoverage :one

SELECT
    s.candidate_skills,
    s.required_skills,
    s.matched_skills,
    CASE
        WHEN s.required_skills > 0 THEN
            ROUND(100.0 * s.matched_skills::numeric / s.required_skills::numeric, 2)
        ELSE NULL::numeric
    END AS coverage_pct
FROM (
    SELECT
        COALESCE(
            (
                SELECT COUNT(*)::bigint
                FROM hskip_users.bridgr_skill_gap_nodes n
                INNER JOIN hskip_users.bridgr_skill_gap_graphs g
                    ON g.uuid = n.graph_uuid AND g.kind = 'candidate'
                WHERE g.analysis_uuid = $1
            ),
            0
        ) AS candidate_skills,
        COALESCE(
            (
                SELECT COUNT(*)::bigint
                FROM hskip_users.bridgr_skill_gap_nodes n
                INNER JOIN hskip_users.bridgr_skill_gap_graphs g
                    ON g.uuid = n.graph_uuid AND g.kind = 'role_requirement'
                WHERE g.analysis_uuid = $1
            ),
            0
        ) AS required_skills,
        COALESCE(
            (
                SELECT COUNT(DISTINCT rn.node_key)::bigint
                FROM hskip_users.bridgr_skill_gap_nodes rn
                INNER JOIN hskip_users.bridgr_skill_gap_graphs rg
                    ON rg.uuid = rn.graph_uuid AND rg.kind = 'role_requirement'
                WHERE rg.analysis_uuid = $1
                  AND EXISTS (
                      SELECT 1
                      FROM hskip_users.bridgr_skill_gap_nodes cn
                      INNER JOIN hskip_users.bridgr_skill_gap_graphs cg
                          ON cg.uuid = cn.graph_uuid AND cg.kind = 'candidate'
                      WHERE cg.analysis_uuid = $1 AND cn.node_key = rn.node_key
                  )
            ),
            0
        ) AS matched_skills
) s
`

type GetSkillGapCoverageRow struct {
	CandidateSkills interface{}    `db:"candidate_skills"`
	RequiredSkills  interface{}    `db:"required_skills"`
	MatchedSkills   interface{}    `db:"matched_skills"`
	CoveragePct     pgtype.Numeric `db:"coverage_pct"`
}

// =============================================================================
// BRIDGR SKILL GAP — COVERAGE (aggregated reads)
// Metrics derived from graphs + node overlap (not only bridgr_skill_gap_coverage rows).
// =============================================================================
func (q *Queries) GetSkillGapCoverage(ctx context.Context, analysisUuid pgtype.UUID) (GetSkillGapCoverageRow, error) {
	row := q.db.QueryRow(ctx, getSkillGapCoverage, analysisUuid)
	var i GetSkillGapCoverageRow
	err := row.Scan(
		&i.CandidateSkills,
		&i.RequiredSkills,
		&i.MatchedSkills,
		&i.CoveragePct,
	)
	return i, err
}

const getSkillGapCoverageByUser = `-- name: GetSkillGapCoverageByUser :many
SELECT
    sub.analysis_id,
    sub.analysis_uuid,
    sub.user_id,
    sub.title,
    sub.status,
    sub.created_at,
    sub.candidate_skills,
    sub.required_skills,
    sub.matched_skills,
    CASE
        WHEN sub.required_skills > 0 THEN
            ROUND(100.0 * sub.matched_skills::numeric / sub.required_skills::numeric, 2)
        ELSE NULL::numeric
    END AS coverage_pct
FROM (
    SELECT
        a.id AS analysis_id,
        a.uuid AS analysis_uuid,
        a.user_id,
        a.title,
        a.status,
        a.created_at,
        COALESCE(
            (
                SELECT COUNT(*)::bigint
                FROM hskip_users.bridgr_skill_gap_nodes n
                INNER JOIN hskip_users.bridgr_skill_gap_graphs g
                    ON g.uuid = n.graph_uuid AND g.kind = 'candidate'
                WHERE g.analysis_uuid = a.uuid
            ),
            0
        ) AS candidate_skills,
        COALESCE(
            (
                SELECT COUNT(*)::bigint
                FROM hskip_users.bridgr_skill_gap_nodes n
                INNER JOIN hskip_users.bridgr_skill_gap_graphs g
                    ON g.uuid = n.graph_uuid AND g.kind = 'role_requirement'
                WHERE g.analysis_uuid = a.uuid
            ),
            0
        ) AS required_skills,
        COALESCE(
            (
                SELECT COUNT(DISTINCT rn.node_key)::bigint
                FROM hskip_users.bridgr_skill_gap_nodes rn
                INNER JOIN hskip_users.bridgr_skill_gap_graphs rg
                    ON rg.uuid = rn.graph_uuid AND rg.kind = 'role_requirement'
                WHERE rg.analysis_uuid = a.uuid
                  AND EXISTS (
                      SELECT 1
                      FROM hskip_users.bridgr_skill_gap_nodes cn
                      INNER JOIN hskip_users.bridgr_skill_gap_graphs cg
                          ON cg.uuid = cn.graph_uuid AND cg.kind = 'candidate'
                      WHERE cg.analysis_uuid = a.uuid AND cn.node_key = rn.node_key
                  )
            ),
            0
        ) AS matched_skills
    FROM hskip_users.bridgr_skill_gap_analyses a
    WHERE a.user_id = $1
) sub
ORDER BY sub.created_at DESC
LIMIT $2 OFFSET $3
`

type GetSkillGapCoverageByUserParams struct {
	UserID int32 `db:"user_id"`
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

type GetSkillGapCoverageByUserRow struct {
	AnalysisID      int64            `db:"analysis_id"`
	AnalysisUuid    pgtype.UUID      `db:"analysis_uuid"`
	UserID          int32            `db:"user_id"`
	Title           pgtype.Text      `db:"title"`
	Status          string           `db:"status"`
	CreatedAt       pgtype.Timestamp `db:"created_at"`
	CandidateSkills interface{}      `db:"candidate_skills"`
	RequiredSkills  interface{}      `db:"required_skills"`
	MatchedSkills   interface{}      `db:"matched_skills"`
	CoveragePct     pgtype.Numeric   `db:"coverage_pct"`
}

func (q *Queries) GetSkillGapCoverageByUser(ctx context.Context, arg GetSkillGapCoverageByUserParams) ([]GetSkillGapCoverageByUserRow, error) {
	rows, err := q.db.Query(ctx, getSkillGapCoverageByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSkillGapCoverageByUserRow
	for rows.Next() {
		var i GetSkillGapCoverageByUserRow
		if err := rows.Scan(
			&i.AnalysisID,
			&i.AnalysisUuid,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.CandidateSkills,
			&i.RequiredSkills,
			&i.MatchedSkills,
			&i.CoveragePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
