// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: bridgr_skill_gap_path_step_deps.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateSkillGapPathStepDepsParams struct {
	PathUuid          pgtype.UUID `db:"path_uuid"`
	StepUuid          pgtype.UUID `db:"step_uuid"`
	DependsOnStepUuid pgtype.UUID `db:"depends_on_step_uuid"`
}

const createSkillGapPathStepDep = `-- name: CreateSkillGapPathStepDep :one

INSERT INTO bridgr.skill_gap_path_step_deps (
    path_uuid,
    step_uuid,
    depends_on_step_uuid
) VALUES ($1, $2, $3)
RETURNING uuid, id, path_uuid, step_uuid, depends_on_step_uuid, created_at, updated_at
`

type CreateSkillGapPathStepDepParams struct {
	PathUuid          pgtype.UUID `db:"path_uuid"`
	StepUuid          pgtype.UUID `db:"step_uuid"`
	DependsOnStepUuid pgtype.UUID `db:"depends_on_step_uuid"`
}

// =============================================================================
// BRIDGR SKILL GAP — PATH STEP DEPENDENCIES
// DAG edges between path steps (prerequisites).
// =============================================================================
func (q *Queries) CreateSkillGapPathStepDep(ctx context.Context, arg CreateSkillGapPathStepDepParams) (HskipUsersBridgrSkillGapPathStepDep, error) {
	row := q.db.QueryRow(ctx, createSkillGapPathStepDep, arg.PathUuid, arg.StepUuid, arg.DependsOnStepUuid)
	var i HskipUsersBridgrSkillGapPathStepDep
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.PathUuid,
		&i.StepUuid,
		&i.DependsOnStepUuid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkillGapPathStepDepsByPath = `-- name: DeleteSkillGapPathStepDepsByPath :exec
DELETE FROM bridgr.skill_gap_path_step_deps
WHERE path_uuid = $1
`

func (q *Queries) DeleteSkillGapPathStepDepsByPath(ctx context.Context, pathUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkillGapPathStepDepsByPath, pathUuid)
	return err
}

const listAllDepsByPath = `-- name: ListAllDepsByPath :many
SELECT uuid, id, path_uuid, step_uuid, depends_on_step_uuid, created_at, updated_at FROM bridgr.skill_gap_path_step_deps
WHERE path_uuid = $1
ORDER BY id ASC
`

func (q *Queries) ListAllDepsByPath(ctx context.Context, pathUuid pgtype.UUID) ([]HskipUsersBridgrSkillGapPathStepDep, error) {
	rows, err := q.db.Query(ctx, listAllDepsByPath, pathUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HskipUsersBridgrSkillGapPathStepDep
	for rows.Next() {
		var i HskipUsersBridgrSkillGapPathStepDep
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.PathUuid,
			&i.StepUuid,
			&i.DependsOnStepUuid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDependenciesByStep = `-- name: ListDependenciesByStep :many
SELECT uuid, id, path_uuid, step_uuid, depends_on_step_uuid, created_at, updated_at FROM bridgr.skill_gap_path_step_deps
WHERE path_uuid = $1 AND step_uuid = $2
ORDER BY id ASC
`

type ListDependenciesByStepParams struct {
	PathUuid pgtype.UUID `db:"path_uuid"`
	StepUuid pgtype.UUID `db:"step_uuid"`
}

// Prerequisite steps that step_uuid depends on within this path.
func (q *Queries) ListDependenciesByStep(ctx context.Context, arg ListDependenciesByStepParams) ([]HskipUsersBridgrSkillGapPathStepDep, error) {
	rows, err := q.db.Query(ctx, listDependenciesByStep, arg.PathUuid, arg.StepUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HskipUsersBridgrSkillGapPathStepDep
	for rows.Next() {
		var i HskipUsersBridgrSkillGapPathStepDep
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.PathUuid,
			&i.StepUuid,
			&i.DependsOnStepUuid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDependentsByStep = `-- name: ListDependentsByStep :many
SELECT uuid, id, path_uuid, step_uuid, depends_on_step_uuid, created_at, updated_at FROM bridgr.skill_gap_path_step_deps
WHERE path_uuid = $1 AND depends_on_step_uuid = $2
ORDER BY id ASC
`

type ListDependentsByStepParams struct {
	PathUuid          pgtype.UUID `db:"path_uuid"`
	DependsOnStepUuid pgtype.UUID `db:"depends_on_step_uuid"`
}

// Steps in this path that depend on depends_on_step_uuid.
func (q *Queries) ListDependentsByStep(ctx context.Context, arg ListDependentsByStepParams) ([]HskipUsersBridgrSkillGapPathStepDep, error) {
	rows, err := q.db.Query(ctx, listDependentsByStep, arg.PathUuid, arg.DependsOnStepUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HskipUsersBridgrSkillGapPathStepDep
	for rows.Next() {
		var i HskipUsersBridgrSkillGapPathStepDep
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.PathUuid,
			&i.StepUuid,
			&i.DependsOnStepUuid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
