// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: bridgr_job_enrichments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJobEnrichment = `-- name: CreateJobEnrichment :one

INSERT INTO bridgr.job_enrichments (
    user_id,
    job_candidate_uuid,
    status,
    required_skills,
    experience_range,
    salary_range,
    remote_policy,
    visa_sponsorship,
    company_size,
    industry,
    application_deadline,
    structured_jd,
    llm_model,
    prompt_version,
    error_detail
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING uuid, id, user_id, job_candidate_uuid, status, required_skills, experience_range, salary_range, remote_policy, visa_sponsorship, company_size, industry, application_deadline, structured_jd, llm_model, prompt_version, error_detail, created_at, updated_at
`

type CreateJobEnrichmentParams struct {
	UserID              int32            `db:"user_id"`
	JobCandidateUuid    pgtype.UUID      `db:"job_candidate_uuid"`
	Status              string           `db:"status"`
	RequiredSkills      []byte           `db:"required_skills"`
	ExperienceRange     []byte           `db:"experience_range"`
	SalaryRange         []byte           `db:"salary_range"`
	RemotePolicy        pgtype.Text      `db:"remote_policy"`
	VisaSponsorship     pgtype.Bool      `db:"visa_sponsorship"`
	CompanySize         pgtype.Text      `db:"company_size"`
	Industry            pgtype.Text      `db:"industry"`
	ApplicationDeadline pgtype.Timestamp `db:"application_deadline"`
	StructuredJd        []byte           `db:"structured_jd"`
	LlmModel            pgtype.Text      `db:"llm_model"`
	PromptVersion       pgtype.Text      `db:"prompt_version"`
	ErrorDetail         pgtype.Text      `db:"error_detail"`
}

// =============================================================================
// BRIDGR — JOB ENRICHMENTS
// Structured JD extraction per (user, job_candidate). Unique (job_candidate_uuid, user_id).
// =============================================================================
func (q *Queries) CreateJobEnrichment(ctx context.Context, arg CreateJobEnrichmentParams) (BridgrJobEnrichment, error) {
	row := q.db.QueryRow(ctx, createJobEnrichment,
		arg.UserID,
		arg.JobCandidateUuid,
		arg.Status,
		arg.RequiredSkills,
		arg.ExperienceRange,
		arg.SalaryRange,
		arg.RemotePolicy,
		arg.VisaSponsorship,
		arg.CompanySize,
		arg.Industry,
		arg.ApplicationDeadline,
		arg.StructuredJd,
		arg.LlmModel,
		arg.PromptVersion,
		arg.ErrorDetail,
	)
	var i BridgrJobEnrichment
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.Status,
		&i.RequiredSkills,
		&i.ExperienceRange,
		&i.SalaryRange,
		&i.RemotePolicy,
		&i.VisaSponsorship,
		&i.CompanySize,
		&i.Industry,
		&i.ApplicationDeadline,
		&i.StructuredJd,
		&i.LlmModel,
		&i.PromptVersion,
		&i.ErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJobEnrichmentByID = `-- name: DeleteJobEnrichmentByID :exec
DELETE FROM bridgr.job_enrichments
WHERE id = $1
`

func (q *Queries) DeleteJobEnrichmentByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteJobEnrichmentByID, id)
	return err
}

const deleteJobEnrichmentByUUID = `-- name: DeleteJobEnrichmentByUUID :exec
DELETE FROM bridgr.job_enrichments
WHERE uuid = $1
`

func (q *Queries) DeleteJobEnrichmentByUUID(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJobEnrichmentByUUID, uuid)
	return err
}

const getJobEnrichmentByID = `-- name: GetJobEnrichmentByID :one
SELECT uuid, id, user_id, job_candidate_uuid, status, required_skills, experience_range, salary_range, remote_policy, visa_sponsorship, company_size, industry, application_deadline, structured_jd, llm_model, prompt_version, error_detail, created_at, updated_at FROM bridgr.job_enrichments
WHERE id = $1
`

func (q *Queries) GetJobEnrichmentByID(ctx context.Context, id int64) (BridgrJobEnrichment, error) {
	row := q.db.QueryRow(ctx, getJobEnrichmentByID, id)
	var i BridgrJobEnrichment
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.Status,
		&i.RequiredSkills,
		&i.ExperienceRange,
		&i.SalaryRange,
		&i.RemotePolicy,
		&i.VisaSponsorship,
		&i.CompanySize,
		&i.Industry,
		&i.ApplicationDeadline,
		&i.StructuredJd,
		&i.LlmModel,
		&i.PromptVersion,
		&i.ErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobEnrichmentByUUID = `-- name: GetJobEnrichmentByUUID :one
SELECT uuid, id, user_id, job_candidate_uuid, status, required_skills, experience_range, salary_range, remote_policy, visa_sponsorship, company_size, industry, application_deadline, structured_jd, llm_model, prompt_version, error_detail, created_at, updated_at FROM bridgr.job_enrichments
WHERE uuid = $1
`

func (q *Queries) GetJobEnrichmentByUUID(ctx context.Context, uuid pgtype.UUID) (BridgrJobEnrichment, error) {
	row := q.db.QueryRow(ctx, getJobEnrichmentByUUID, uuid)
	var i BridgrJobEnrichment
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.Status,
		&i.RequiredSkills,
		&i.ExperienceRange,
		&i.SalaryRange,
		&i.RemotePolicy,
		&i.VisaSponsorship,
		&i.CompanySize,
		&i.Industry,
		&i.ApplicationDeadline,
		&i.StructuredJd,
		&i.LlmModel,
		&i.PromptVersion,
		&i.ErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobEnrichmentByUserAndCandidateUUID = `-- name: GetJobEnrichmentByUserAndCandidateUUID :one
SELECT uuid, id, user_id, job_candidate_uuid, status, required_skills, experience_range, salary_range, remote_policy, visa_sponsorship, company_size, industry, application_deadline, structured_jd, llm_model, prompt_version, error_detail, created_at, updated_at FROM bridgr.job_enrichments
WHERE user_id = $1 AND job_candidate_uuid = $2
`

type GetJobEnrichmentByUserAndCandidateUUIDParams struct {
	UserID           int32       `db:"user_id"`
	JobCandidateUuid pgtype.UUID `db:"job_candidate_uuid"`
}

func (q *Queries) GetJobEnrichmentByUserAndCandidateUUID(ctx context.Context, arg GetJobEnrichmentByUserAndCandidateUUIDParams) (BridgrJobEnrichment, error) {
	row := q.db.QueryRow(ctx, getJobEnrichmentByUserAndCandidateUUID, arg.UserID, arg.JobCandidateUuid)
	var i BridgrJobEnrichment
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.Status,
		&i.RequiredSkills,
		&i.ExperienceRange,
		&i.SalaryRange,
		&i.RemotePolicy,
		&i.VisaSponsorship,
		&i.CompanySize,
		&i.Industry,
		&i.ApplicationDeadline,
		&i.StructuredJd,
		&i.LlmModel,
		&i.PromptVersion,
		&i.ErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobEnrichmentsByUser = `-- name: ListJobEnrichmentsByUser :many
SELECT uuid, id, user_id, job_candidate_uuid, status, required_skills, experience_range, salary_range, remote_policy, visa_sponsorship, company_size, industry, application_deadline, structured_jd, llm_model, prompt_version, error_detail, created_at, updated_at FROM bridgr.job_enrichments
WHERE user_id = $1
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type ListJobEnrichmentsByUserParams struct {
	UserID int32 `db:"user_id"`
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListJobEnrichmentsByUser(ctx context.Context, arg ListJobEnrichmentsByUserParams) ([]BridgrJobEnrichment, error) {
	rows, err := q.db.Query(ctx, listJobEnrichmentsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BridgrJobEnrichment
	for rows.Next() {
		var i BridgrJobEnrichment
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.UserID,
			&i.JobCandidateUuid,
			&i.Status,
			&i.RequiredSkills,
			&i.ExperienceRange,
			&i.SalaryRange,
			&i.RemotePolicy,
			&i.VisaSponsorship,
			&i.CompanySize,
			&i.Industry,
			&i.ApplicationDeadline,
			&i.StructuredJd,
			&i.LlmModel,
			&i.PromptVersion,
			&i.ErrorDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobEnrichmentByID = `-- name: UpdateJobEnrichmentByID :one
UPDATE bridgr.job_enrichments
SET
    status = $2,
    required_skills = $3,
    experience_range = $4,
    salary_range = $5,
    remote_policy = $6,
    visa_sponsorship = $7,
    company_size = $8,
    industry = $9,
    application_deadline = $10,
    structured_jd = $11,
    llm_model = $12,
    prompt_version = $13,
    error_detail = $14
WHERE id = $1
RETURNING uuid, id, user_id, job_candidate_uuid, status, required_skills, experience_range, salary_range, remote_policy, visa_sponsorship, company_size, industry, application_deadline, structured_jd, llm_model, prompt_version, error_detail, created_at, updated_at
`

type UpdateJobEnrichmentByIDParams struct {
	ID                  int64            `db:"id"`
	Status              string           `db:"status"`
	RequiredSkills      []byte           `db:"required_skills"`
	ExperienceRange     []byte           `db:"experience_range"`
	SalaryRange         []byte           `db:"salary_range"`
	RemotePolicy        pgtype.Text      `db:"remote_policy"`
	VisaSponsorship     pgtype.Bool      `db:"visa_sponsorship"`
	CompanySize         pgtype.Text      `db:"company_size"`
	Industry            pgtype.Text      `db:"industry"`
	ApplicationDeadline pgtype.Timestamp `db:"application_deadline"`
	StructuredJd        []byte           `db:"structured_jd"`
	LlmModel            pgtype.Text      `db:"llm_model"`
	PromptVersion       pgtype.Text      `db:"prompt_version"`
	ErrorDetail         pgtype.Text      `db:"error_detail"`
}

func (q *Queries) UpdateJobEnrichmentByID(ctx context.Context, arg UpdateJobEnrichmentByIDParams) (BridgrJobEnrichment, error) {
	row := q.db.QueryRow(ctx, updateJobEnrichmentByID,
		arg.ID,
		arg.Status,
		arg.RequiredSkills,
		arg.ExperienceRange,
		arg.SalaryRange,
		arg.RemotePolicy,
		arg.VisaSponsorship,
		arg.CompanySize,
		arg.Industry,
		arg.ApplicationDeadline,
		arg.StructuredJd,
		arg.LlmModel,
		arg.PromptVersion,
		arg.ErrorDetail,
	)
	var i BridgrJobEnrichment
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.Status,
		&i.RequiredSkills,
		&i.ExperienceRange,
		&i.SalaryRange,
		&i.RemotePolicy,
		&i.VisaSponsorship,
		&i.CompanySize,
		&i.Industry,
		&i.ApplicationDeadline,
		&i.StructuredJd,
		&i.LlmModel,
		&i.PromptVersion,
		&i.ErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertJobEnrichment = `-- name: UpsertJobEnrichment :one
INSERT INTO bridgr.job_enrichments (
    user_id,
    job_candidate_uuid,
    status,
    required_skills,
    experience_range,
    salary_range,
    remote_policy,
    visa_sponsorship,
    company_size,
    industry,
    application_deadline,
    structured_jd,
    llm_model,
    prompt_version,
    error_detail
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
ON CONFLICT (job_candidate_uuid, user_id) DO UPDATE SET
    status = EXCLUDED.status,
    required_skills = EXCLUDED.required_skills,
    experience_range = EXCLUDED.experience_range,
    salary_range = EXCLUDED.salary_range,
    remote_policy = EXCLUDED.remote_policy,
    visa_sponsorship = EXCLUDED.visa_sponsorship,
    company_size = EXCLUDED.company_size,
    industry = EXCLUDED.industry,
    application_deadline = EXCLUDED.application_deadline,
    structured_jd = EXCLUDED.structured_jd,
    llm_model = EXCLUDED.llm_model,
    prompt_version = EXCLUDED.prompt_version,
    error_detail = EXCLUDED.error_detail
RETURNING uuid, id, user_id, job_candidate_uuid, status, required_skills, experience_range, salary_range, remote_policy, visa_sponsorship, company_size, industry, application_deadline, structured_jd, llm_model, prompt_version, error_detail, created_at, updated_at
`

type UpsertJobEnrichmentParams struct {
	UserID              int32            `db:"user_id"`
	JobCandidateUuid    pgtype.UUID      `db:"job_candidate_uuid"`
	Status              string           `db:"status"`
	RequiredSkills      []byte           `db:"required_skills"`
	ExperienceRange     []byte           `db:"experience_range"`
	SalaryRange         []byte           `db:"salary_range"`
	RemotePolicy        pgtype.Text      `db:"remote_policy"`
	VisaSponsorship     pgtype.Bool      `db:"visa_sponsorship"`
	CompanySize         pgtype.Text      `db:"company_size"`
	Industry            pgtype.Text      `db:"industry"`
	ApplicationDeadline pgtype.Timestamp `db:"application_deadline"`
	StructuredJd        []byte           `db:"structured_jd"`
	LlmModel            pgtype.Text      `db:"llm_model"`
	PromptVersion       pgtype.Text      `db:"prompt_version"`
	ErrorDetail         pgtype.Text      `db:"error_detail"`
}

func (q *Queries) UpsertJobEnrichment(ctx context.Context, arg UpsertJobEnrichmentParams) (BridgrJobEnrichment, error) {
	row := q.db.QueryRow(ctx, upsertJobEnrichment,
		arg.UserID,
		arg.JobCandidateUuid,
		arg.Status,
		arg.RequiredSkills,
		arg.ExperienceRange,
		arg.SalaryRange,
		arg.RemotePolicy,
		arg.VisaSponsorship,
		arg.CompanySize,
		arg.Industry,
		arg.ApplicationDeadline,
		arg.StructuredJd,
		arg.LlmModel,
		arg.PromptVersion,
		arg.ErrorDetail,
	)
	var i BridgrJobEnrichment
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.UserID,
		&i.JobCandidateUuid,
		&i.Status,
		&i.RequiredSkills,
		&i.ExperienceRange,
		&i.SalaryRange,
		&i.RemotePolicy,
		&i.VisaSponsorship,
		&i.CompanySize,
		&i.Industry,
		&i.ApplicationDeadline,
		&i.StructuredJd,
		&i.LlmModel,
		&i.PromptVersion,
		&i.ErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
