// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Bridgr: associates a skill_gap_analysis with a discovered job_candidates row.
type BridgrAnalysisJobLink struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to users.id; denormalized for listing
	UserID int32 `db:"user_id"`
	// App-enforced FK to skill_gap_analyses.uuid
	AnalysisUuid pgtype.UUID `db:"analysis_uuid"`
	// App-enforced FK to job_candidates.uuid
	JobCandidateUuid pgtype.UUID `db:"job_candidate_uuid"`
	// from_job_feed, manual, import
	LinkKind  string           `db:"link_kind"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at"`
}

// Bridgr feed: user-facing rows for high-quality job matches (denormalized for fast reads).
type BridgrFeedItem struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to users.id
	UserID int32 `db:"user_id"`
	// App-enforced FK to job_candidates.uuid
	JobCandidateUuid pgtype.UUID `db:"job_candidate_uuid"`
	// App-enforced FK to job_scores.uuid
	ScoreUuid pgtype.UUID `db:"score_uuid"`
	// Optional future link to a verification record; app-enforced when set
	VerificationUuid pgtype.UUID `db:"verification_uuid"`
	CompositeScore   float32     `db:"composite_score"`
	GapSeverity      pgtype.Text `db:"gap_severity"`
	Title            pgtype.Text `db:"title"`
	Company          pgtype.Text `db:"company"`
	Location         pgtype.Text `db:"location"`
	JobUrl           pgtype.Text `db:"job_url"`
	// Short human-readable why this job matches
	MatchSummary pgtype.Text `db:"match_summary"`
	// Short human-readable skill-gap note
	GapSummary pgtype.Text `db:"gap_summary"`
	// new, seen, saved, dismissed, applied
	FeedStatus string `db:"feed_status"`
	// When this item entered the feed
	SurfacedAt pgtype.Timestamp `db:"surfaced_at"`
	SeenAt     pgtype.Timestamp `db:"seen_at"`
	CreatedAt  pgtype.Timestamp `db:"created_at"`
	UpdatedAt  pgtype.Timestamp `db:"updated_at"`
}

// Bridgr job discovery: one row per unique posting per user (dedupe by url_hash).
type BridgrJobCandidate struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to users.id
	UserID int32 `db:"user_id"`
	// App-enforced FK to job_search_discovery_runs.uuid
	DiscoveryRunUuid pgtype.UUID `db:"discovery_run_uuid"`
	SourceBoard      string      `db:"source_board"`
	SourceJobID      pgtype.Text `db:"source_job_id"`
	JobUrl           string      `db:"job_url"`
	// Stable hash of normalized URL for deduplication
	UrlHash string `db:"url_hash"`
	// Optional hash of JD body for refresh/dedup
	ContentHash pgtype.Text `db:"content_hash"`
	Title       pgtype.Text `db:"title"`
	Company     pgtype.Text `db:"company"`
	Location    pgtype.Text `db:"location"`
	// Inline job description text when small enough
	JdText pgtype.Text `db:"jd_text"`
	// Pointer to stored JD blob when large
	JdS3Uri         pgtype.Text      `db:"jd_s3_uri"`
	FetchedAt       pgtype.Timestamp `db:"fetched_at"`
	IngestionStatus string           `db:"ingestion_status"`
	// Raw or normalized Radar response slice
	RadarPayload []byte `db:"radar_payload"`
	// Direct apply URL when distinct from job_url
	ApplicationUrl pgtype.Text      `db:"application_url"`
	CreatedAt      pgtype.Timestamp `db:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at"`
}

// Bridgr feed: LLM- or rules-based structured fields extracted from a job posting for matching.
type BridgrJobEnrichment struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to users.id
	UserID int32 `db:"user_id"`
	// App-enforced FK to job_candidates.uuid
	JobCandidateUuid pgtype.UUID `db:"job_candidate_uuid"`
	Status           string      `db:"status"`
	// JSON array of {skill, level, mandatory} or similar
	RequiredSkills []byte `db:"required_skills"`
	// JSON {min_years, max_years, seniority}
	ExperienceRange []byte `db:"experience_range"`
	// JSON {min, max, currency, period}
	SalaryRange         []byte           `db:"salary_range"`
	RemotePolicy        pgtype.Text      `db:"remote_policy"`
	VisaSponsorship     pgtype.Bool      `db:"visa_sponsorship"`
	CompanySize         pgtype.Text      `db:"company_size"`
	Industry            pgtype.Text      `db:"industry"`
	ApplicationDeadline pgtype.Timestamp `db:"application_deadline"`
	// Full normalized job description blob for scoring
	StructuredJd  []byte           `db:"structured_jd"`
	LlmModel      pgtype.Text      `db:"llm_model"`
	PromptVersion pgtype.Text      `db:"prompt_version"`
	ErrorDetail   pgtype.Text      `db:"error_detail"`
	CreatedAt     pgtype.Timestamp `db:"created_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at"`
}

// Bridgr feed: when and how to re-run discovery for a job_search_profile.
type BridgrJobHarvestSchedule struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to users.id
	UserID int32 `db:"user_id"`
	// App-enforced FK to job_search_profiles.uuid
	ProfileUuid pgtype.UUID `db:"profile_uuid"`
	Enabled     bool        `db:"enabled"`
	// Minimum interval between automated harvest runs
	CadenceMinutes int32 `db:"cadence_minutes"`
	// JSON array of board ids to rotate through on successive runs
	BoardsRotation []byte `db:"boards_rotation"`
	// When the last scheduled harvest started or completed
	LastRunAt pgtype.Timestamp `db:"last_run_at"`
	// When the scheduler should enqueue the next harvest
	NextRunAt pgtype.Timestamp `db:"next_run_at"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at"`
}

// Bridgr job discovery: notification rows for new surfaced or relevant jobs.
type BridgrJobNotification struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to users.id
	UserID int32 `db:"user_id"`
	// App-enforced FK to job_candidates.uuid
	JobCandidateUuid pgtype.UUID `db:"job_candidate_uuid"`
	// in_app, email, push
	Channel string `db:"channel"`
	// pending, sent, failed, seen, skipped
	Status string `db:"status"`
	// Title snippet, deep link hints, template vars
	Payload     []byte           `db:"payload"`
	SentAt      pgtype.Timestamp `db:"sent_at"`
	SeenAt      pgtype.Timestamp `db:"seen_at"`
	ErrorDetail pgtype.Text      `db:"error_detail"`
	CreatedAt   pgtype.Timestamp `db:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at"`
}

// Bridgr feed: per-user relevance and skill-gap scores for a discovered job.
type BridgrJobScore struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to users.id
	UserID int32 `db:"user_id"`
	// App-enforced FK to job_candidates.uuid
	JobCandidateUuid pgtype.UUID `db:"job_candidate_uuid"`
	// Optional app-enforced FK to job_enrichments.uuid used for this score
	EnrichmentUuid       pgtype.UUID `db:"enrichment_uuid"`
	SkillMatchScore      float32     `db:"skill_match_score"`
	ExperienceMatchScore float32     `db:"experience_match_score"`
	LocationMatchScore   float32     `db:"location_match_score"`
	RecencyScore         float32     `db:"recency_score"`
	BoardQualityScore    float32     `db:"board_quality_score"`
	// Weighted blend of dimension scores; primary feed sort key
	CompositeScore float32 `db:"composite_score"`
	// JSON: skills the user satisfies for this role
	MatchedSkills []byte `db:"matched_skills"`
	// JSON: required skills still missing for the user
	GapSkills []byte `db:"gap_skills"`
	// none, minor, moderate, major
	GapSeverity    pgtype.Text      `db:"gap_severity"`
	ScoringModel   pgtype.Text      `db:"scoring_model"`
	ScoringVersion pgtype.Text      `db:"scoring_version"`
	CreatedAt      pgtype.Timestamp `db:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at"`
}

// Bridgr job discovery: audit trail for one Radar-backed discovery execution.
type BridgrJobSearchDiscoveryRun struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to users.id
	UserID int32 `db:"user_id"`
	// pending, queued, running, completed, failed, cancelled
	Status string `db:"status"`
	// Resolved query/location/boards caps sent to worker/Radar
	RequestParams []byte `db:"request_params"`
	// Timings, per-board errors, debug payload
	RadarMeta         []byte           `db:"radar_meta"`
	RawCandidateCount int32            `db:"raw_candidate_count"`
	NewCandidateCount int32            `db:"new_candidate_count"`
	StartedAt         pgtype.Timestamp `db:"started_at"`
	CompletedAt       pgtype.Timestamp `db:"completed_at"`
	ErrorCode         pgtype.Text      `db:"error_code"`
	ErrorDetail       pgtype.Text      `db:"error_detail"`
	// Optional queue id for async job discovery
	SqsMessageID pgtype.Text      `db:"sqs_message_id"`
	CreatedAt    pgtype.Timestamp `db:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at"`
}

// Bridgr job discovery: one row = one Radar search slice (query, location, board, goals).
type BridgrJobSearchProfile struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to users.id
	UserID int32 `db:"user_id"`
	// Single search string passed to Radar (e.g. primary target role or fixed query).
	TargetRole string `db:"target_role"`
	// Single location string for this slice (city, remote label, etc.).
	Location string `db:"location"`
	// Single board id for this slice (e.g. linkedin, indeed).
	SourceBoard string `db:"source_board"`
	// True when the user is seeking a career change / new domain.
	CareerSwitch bool `db:"career_switch"`
	// Employer stage filter; product-defined values (e.g. startup, growth, enterprise, any).
	CompanyStage string `db:"company_stage"`
	// Allowed: up, lateral, down, any.
	SeniorityGoal string `db:"seniority_goal"`
	// Allowed: up, lateral, down, any.
	CompensationGoal string `db:"compensation_goal"`
	// Tags for required technologies in this search slice.
	SoftwareStackMustHave []string `db:"software_stack_must_have"`
	// Optional app-enforced FK to skill_gap_analyses.uuid for CV fingerprint context
	CanonicalCvAnalysisUuid pgtype.UUID      `db:"canonical_cv_analysis_uuid"`
	CreatedAt               pgtype.Timestamp `db:"created_at"`
	UpdatedAt               pgtype.Timestamp `db:"updated_at"`
}

type BridgrSchemaMigration struct {
	Version int64 `db:"version"`
	Dirty   bool  `db:"dirty"`
}

// Bridgr Skill Gap Navigator: analysis run linking user (and optional founder context) to CV/JD extraction and learning-path outputs.
type BridgrSkillGapAnalysis struct {
	Uuid               pgtype.UUID `db:"uuid"`
	ID                 int64       `db:"id"`
	UserID             int32       `db:"user_id"`
	FounderPersonaUuid pgtype.UUID `db:"founder_persona_uuid"`
	PursuitUuid        pgtype.UUID `db:"pursuit_uuid"`
	Title              pgtype.Text `db:"title"`
	// pending, extracting, graphed, pathed, completed, failed
	Status string `db:"status"`
	// Pointer to stored CV (e.g. S3); optional if inline processing only
	CvAssetUri pgtype.Text `db:"cv_asset_uri"`
	// Pointer to stored job description
	JdAssetUri pgtype.Text `db:"jd_asset_uri"`
	// Hash for dedup / idempotency
	CvFingerprint pgtype.Text `db:"cv_fingerprint"`
	// Hash for dedup / idempotency
	JdFingerprint pgtype.Text `db:"jd_fingerprint"`
	LlmModel      pgtype.Text `db:"llm_model"`
	PromptVersion pgtype.Text `db:"prompt_version"`
	// Validated structured LLM output (skills graph extraction)
	ExtractionPayload []byte `db:"extraction_payload"`
	// Rollup metrics and narrative gap summary
	GapSummary []byte `db:"gap_summary"`
	// Optional v1 DAG visualization text
	MermaidDiagram pgtype.Text `db:"mermaid_diagram"`
	ErrorCode      pgtype.Text `db:"error_code"`
	ErrorDetail    pgtype.Text `db:"error_detail"`
	// AWS SQS MessageId after successful enqueue (debugging / dedupe)
	SqsMessageID pgtype.Text      `db:"sqs_message_id"`
	CreatedAt    pgtype.Timestamp `db:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at"`
}

// Skill coverage / gap rows or summary metrics for an analysis.
type BridgrSkillGapCoverage struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to skill_gap_analyses.uuid
	AnalysisUuid pgtype.UUID `db:"analysis_uuid"`
	// role_skill: pairing row; summary: one row roll-up; aggregate: optional bucket
	CoverageKind      string      `db:"coverage_kind"`
	RoleSkillKey      pgtype.Text `db:"role_skill_key"`
	CandidateSkillKey pgtype.Text `db:"candidate_skill_key"`
	// covered, gap, partial, surplus, not_applicable, unknown
	MatchStatus string           `db:"match_status"`
	Summary     pgtype.Text      `db:"summary"`
	Metrics     []byte           `db:"metrics"`
	CreatedAt   pgtype.Timestamp `db:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at"`
}

// Directed edges between skill-gap nodes in a graph.
type BridgrSkillGapEdge struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to skill_gap_graphs.uuid
	GraphUuid pgtype.UUID `db:"graph_uuid"`
	// App-enforced FK to skill_gap_nodes.uuid
	FromNodeUuid pgtype.UUID `db:"from_node_uuid"`
	// App-enforced FK to skill_gap_nodes.uuid
	ToNodeUuid pgtype.UUID `db:"to_node_uuid"`
	// prerequisite, similarity, required_by, etc.
	Relation  string           `db:"relation"`
	Weight    pgtype.Numeric   `db:"weight"`
	Metadata  []byte           `db:"metadata"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at"`
}

// Skill graphs for Bridgr: typically two per analysis (candidate skills vs role requirements).
type BridgrSkillGapGraph struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to skill_gap_analyses.uuid
	AnalysisUuid pgtype.UUID `db:"analysis_uuid"`
	// candidate = graph from CV; role_requirement = graph from job description
	Kind string `db:"kind"`
	// Optional graph-level notes, model version, or layout hints
	Metadata  []byte           `db:"metadata"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at"`
}

// Learning plan / path for closing skill gaps from one analysis.
type BridgrSkillGapLearningPath struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to skill_gap_analyses.uuid
	AnalysisUuid pgtype.UUID `db:"analysis_uuid"`
	// Increment when regenerating path for same analysis
	PathVersion  int32            `db:"path_version"`
	Algorithm    pgtype.Text      `db:"algorithm"`
	Title        pgtype.Text      `db:"title"`
	PathMetadata []byte           `db:"path_metadata"`
	CreatedAt    pgtype.Timestamp `db:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at"`
}

// Skill/concept nodes in a skill-gap graph (candidate or role requirement).
type BridgrSkillGapNode struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to skill_gap_graphs.uuid
	GraphUuid pgtype.UUID `db:"graph_uuid"`
	// Stable key for this node within the graph (e.g. normalized skill id)
	NodeKey string `db:"node_key"`
	// Human-readable label
	DisplayName     string      `db:"display_name"`
	Description     pgtype.Text `db:"description"`
	ProficiencyHint pgtype.Text `db:"proficiency_hint"`
	// cv, jd, inferred, merged, etc.
	Source pgtype.Text `db:"source"`
	// Spans, quotes, or LLM citations supporting the node
	Evidence  []byte           `db:"evidence"`
	Metadata  []byte           `db:"metadata"`
	PositionX pgtype.Int4      `db:"position_x"`
	PositionY pgtype.Int4      `db:"position_y"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at"`
}

// One step in a generated learning path.
type BridgrSkillGapPathStep struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to skill_gap_learning_paths.uuid
	PathUuid pgtype.UUID `db:"path_uuid"`
	// Order within the path (0-based or 1-based per app convention)
	StepIndex      int32          `db:"step_index"`
	Title          string         `db:"title"`
	Rationale      pgtype.Text    `db:"rationale"`
	EstimatedHours pgtype.Numeric `db:"estimated_hours"`
	ResourceUri    pgtype.Text    `db:"resource_uri"`
	ResourceKind   pgtype.Text    `db:"resource_kind"`
	// App-enforced FK to founder_learning_items.uuid when linked
	FounderLearningItemUuid pgtype.UUID `db:"founder_learning_item_uuid"`
	// App-enforced FK to course lesson when linked
	CourseLessonUuid pgtype.UUID `db:"course_lesson_uuid"`
	// JSON array of graph node_key values this step addresses
	LinkedNodeKeys []byte           `db:"linked_node_keys"`
	Metadata       []byte           `db:"metadata"`
	CreatedAt      pgtype.Timestamp `db:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at"`
}

// Prerequisite edges between steps in a learning path (DAG).
type BridgrSkillGapPathStepDep struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to skill_gap_learning_paths.uuid
	PathUuid pgtype.UUID `db:"path_uuid"`
	// App-enforced FK to skill_gap_path_steps.uuid — dependent step
	StepUuid pgtype.UUID `db:"step_uuid"`
	// App-enforced FK to skill_gap_path_steps.uuid — must be done first
	DependsOnStepUuid pgtype.UUID      `db:"depends_on_step_uuid"`
	CreatedAt         pgtype.Timestamp `db:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at"`
}

// Bridgr/Radar: canonical list of supported job boards (CRUD via API; seeds from former supported_boards.yaml).
type BridgrSupportedJobBoard struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// Stable slug (e.g. linkedin, indeed); matches Discovery source_site / JobSpy site key
	BoardID string `db:"board_id"`
	// Human-readable label for UI
	DisplayName string `db:"display_name"`
	// Radar engine: jobspy, smartextract, crawl4ai, workday, indeed, etc.
	Engine string `db:"engine"`
	// How the board is crawled: search (query+location URL), static (fixed career pages), etc.
	SiteType string `db:"site_type"`
	// Primary region: global, us, uk, eu, …
	Region string `db:"region"`
	// When false, board is hidden from selection and not used for new crawls
	IsActive bool `db:"is_active"`
	// Engine-specific options (e.g. fetch_description, proxy hints); extensible JSON
	Config []byte `db:"config"`
	// Lower values list first in admin and user pickers
	SortOrder int32            `db:"sort_order"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at"`
}
