// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Bridgr: associates a skill_gap_analysis with a discovered job_candidates row.
type BridgrAnalysisJobLink struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to users.id; denormalized for listing
	UserID int32 `db:"user_id"`
	// App-enforced FK to skill_gap_analyses.uuid
	AnalysisUuid pgtype.UUID `db:"analysis_uuid"`
	// App-enforced FK to job_candidates.uuid
	JobCandidateUuid pgtype.UUID `db:"job_candidate_uuid"`
	// from_job_feed, manual, import
	LinkKind  string           `db:"link_kind"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at"`
}

// Bridgr job discovery: one row per unique posting per user (dedupe by url_hash).
type BridgrJobCandidate struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to users.id
	UserID int32 `db:"user_id"`
	// App-enforced FK to job_search_discovery_runs.uuid
	DiscoveryRunUuid pgtype.UUID `db:"discovery_run_uuid"`
	SourceBoard      string      `db:"source_board"`
	SourceJobID      pgtype.Text `db:"source_job_id"`
	JobUrl           string      `db:"job_url"`
	// Stable hash of normalized URL for deduplication
	UrlHash string `db:"url_hash"`
	// Optional hash of JD body for refresh/dedup
	ContentHash pgtype.Text `db:"content_hash"`
	Title       pgtype.Text `db:"title"`
	Company     pgtype.Text `db:"company"`
	Location    pgtype.Text `db:"location"`
	// Inline job description text when small enough
	JdText pgtype.Text `db:"jd_text"`
	// Pointer to stored JD blob when large
	JdS3Uri         pgtype.Text      `db:"jd_s3_uri"`
	FetchedAt       pgtype.Timestamp `db:"fetched_at"`
	IngestionStatus string           `db:"ingestion_status"`
	// Raw or normalized Radar response slice
	RadarPayload []byte `db:"radar_payload"`
	// Direct apply URL when distinct from job_url
	ApplicationUrl pgtype.Text      `db:"application_url"`
	CreatedAt      pgtype.Timestamp `db:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at"`
}

// Bridgr job discovery: notification rows for new surfaced or relevant jobs.
type BridgrJobNotification struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to users.id
	UserID int32 `db:"user_id"`
	// App-enforced FK to job_candidates.uuid
	JobCandidateUuid pgtype.UUID `db:"job_candidate_uuid"`
	// in_app, email, push
	Channel string `db:"channel"`
	// pending, sent, failed, seen, skipped
	Status string `db:"status"`
	// Title snippet, deep link hints, template vars
	Payload     []byte           `db:"payload"`
	SentAt      pgtype.Timestamp `db:"sent_at"`
	SeenAt      pgtype.Timestamp `db:"seen_at"`
	ErrorDetail pgtype.Text      `db:"error_detail"`
	CreatedAt   pgtype.Timestamp `db:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at"`
}

// Bridgr job discovery: audit trail for one Radar-backed discovery execution.
type BridgrJobSearchDiscoveryRun struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to users.id
	UserID int32 `db:"user_id"`
	// pending, running, completed, failed, cancelled
	Status string `db:"status"`
	// Resolved query/location/boards caps sent to worker/Radar
	RequestParams []byte `db:"request_params"`
	// Timings, per-board errors, debug payload
	RadarMeta         []byte           `db:"radar_meta"`
	RawCandidateCount int32            `db:"raw_candidate_count"`
	NewCandidateCount int32            `db:"new_candidate_count"`
	StartedAt         pgtype.Timestamp `db:"started_at"`
	CompletedAt       pgtype.Timestamp `db:"completed_at"`
	ErrorCode         pgtype.Text      `db:"error_code"`
	ErrorDetail       pgtype.Text      `db:"error_detail"`
	// Optional queue id for async job discovery
	SqsMessageID pgtype.Text      `db:"sqs_message_id"`
	CreatedAt    pgtype.Timestamp `db:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at"`
}

// Bridgr job discovery: user preferences for Radar search and surfacing.
type BridgrJobSearchProfile struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to users.id
	UserID int32 `db:"user_id"`
	// JSON array of role strings or objects
	TargetRoles []byte `db:"target_roles"`
	// JSON array of location descriptors (city, remote flags, etc.)
	Locations []byte `db:"locations"`
	// JSON array of board ids (e.g. linkedin, indeed)
	BoardsEnabled []byte `db:"boards_enabled"`
	// Policy blob: strict_no_skill_gaps, tiers, etc.
	Matching []byte `db:"matching"`
	// Optional app-enforced FK to skill_gap_analyses.uuid for CV fingerprint context
	CanonicalCvAnalysisUuid pgtype.UUID      `db:"canonical_cv_analysis_uuid"`
	MaxSurfacedJobs         int32            `db:"max_surfaced_jobs"`
	CreatedAt               pgtype.Timestamp `db:"created_at"`
	UpdatedAt               pgtype.Timestamp `db:"updated_at"`
}

type BridgrSchemaMigration struct {
	Version int64 `db:"version"`
	Dirty   bool  `db:"dirty"`
}

// Bridgr Skill Gap Navigator: analysis run linking user (and optional founder context) to CV/JD extraction and learning-path outputs.
type BridgrSkillGapAnalysis struct {
	Uuid               pgtype.UUID `db:"uuid"`
	ID                 int64       `db:"id"`
	UserID             int32       `db:"user_id"`
	FounderPersonaUuid pgtype.UUID `db:"founder_persona_uuid"`
	PursuitUuid        pgtype.UUID `db:"pursuit_uuid"`
	Title              pgtype.Text `db:"title"`
	// pending, extracting, graphed, pathed, completed, failed
	Status string `db:"status"`
	// Pointer to stored CV (e.g. S3); optional if inline processing only
	CvAssetUri pgtype.Text `db:"cv_asset_uri"`
	// Pointer to stored job description
	JdAssetUri pgtype.Text `db:"jd_asset_uri"`
	// Hash for dedup / idempotency
	CvFingerprint pgtype.Text `db:"cv_fingerprint"`
	// Hash for dedup / idempotency
	JdFingerprint pgtype.Text `db:"jd_fingerprint"`
	LlmModel      pgtype.Text `db:"llm_model"`
	PromptVersion pgtype.Text `db:"prompt_version"`
	// Validated structured LLM output (skills graph extraction)
	ExtractionPayload []byte `db:"extraction_payload"`
	// Rollup metrics and narrative gap summary
	GapSummary []byte `db:"gap_summary"`
	// Optional v1 DAG visualization text
	MermaidDiagram pgtype.Text `db:"mermaid_diagram"`
	ErrorCode      pgtype.Text `db:"error_code"`
	ErrorDetail    pgtype.Text `db:"error_detail"`
	// AWS SQS MessageId after successful enqueue (debugging / dedupe)
	SqsMessageID pgtype.Text      `db:"sqs_message_id"`
	CreatedAt    pgtype.Timestamp `db:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at"`
}

// Skill coverage / gap rows or summary metrics for an analysis.
type BridgrSkillGapCoverage struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to skill_gap_analyses.uuid
	AnalysisUuid pgtype.UUID `db:"analysis_uuid"`
	// role_skill: pairing row; summary: one row roll-up; aggregate: optional bucket
	CoverageKind      string      `db:"coverage_kind"`
	RoleSkillKey      pgtype.Text `db:"role_skill_key"`
	CandidateSkillKey pgtype.Text `db:"candidate_skill_key"`
	// covered, gap, partial, surplus, not_applicable, unknown
	MatchStatus string           `db:"match_status"`
	Summary     pgtype.Text      `db:"summary"`
	Metrics     []byte           `db:"metrics"`
	CreatedAt   pgtype.Timestamp `db:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at"`
}

// Directed edges between skill-gap nodes in a graph.
type BridgrSkillGapEdge struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to skill_gap_graphs.uuid
	GraphUuid pgtype.UUID `db:"graph_uuid"`
	// App-enforced FK to skill_gap_nodes.uuid
	FromNodeUuid pgtype.UUID `db:"from_node_uuid"`
	// App-enforced FK to skill_gap_nodes.uuid
	ToNodeUuid pgtype.UUID `db:"to_node_uuid"`
	// prerequisite, similarity, required_by, etc.
	Relation  string           `db:"relation"`
	Weight    pgtype.Numeric   `db:"weight"`
	Metadata  []byte           `db:"metadata"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at"`
}

// Skill graphs for Bridgr: typically two per analysis (candidate skills vs role requirements).
type BridgrSkillGapGraph struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to skill_gap_analyses.uuid
	AnalysisUuid pgtype.UUID `db:"analysis_uuid"`
	// candidate = graph from CV; role_requirement = graph from job description
	Kind string `db:"kind"`
	// Optional graph-level notes, model version, or layout hints
	Metadata  []byte           `db:"metadata"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at"`
}

// Learning plan / path for closing skill gaps from one analysis.
type BridgrSkillGapLearningPath struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to skill_gap_analyses.uuid
	AnalysisUuid pgtype.UUID `db:"analysis_uuid"`
	// Increment when regenerating path for same analysis
	PathVersion  int32            `db:"path_version"`
	Algorithm    pgtype.Text      `db:"algorithm"`
	Title        pgtype.Text      `db:"title"`
	PathMetadata []byte           `db:"path_metadata"`
	CreatedAt    pgtype.Timestamp `db:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at"`
}

// Skill/concept nodes in a skill-gap graph (candidate or role requirement).
type BridgrSkillGapNode struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to skill_gap_graphs.uuid
	GraphUuid pgtype.UUID `db:"graph_uuid"`
	// Stable key for this node within the graph (e.g. normalized skill id)
	NodeKey string `db:"node_key"`
	// Human-readable label
	DisplayName     string      `db:"display_name"`
	Description     pgtype.Text `db:"description"`
	ProficiencyHint pgtype.Text `db:"proficiency_hint"`
	// cv, jd, inferred, merged, etc.
	Source pgtype.Text `db:"source"`
	// Spans, quotes, or LLM citations supporting the node
	Evidence  []byte           `db:"evidence"`
	Metadata  []byte           `db:"metadata"`
	PositionX pgtype.Int4      `db:"position_x"`
	PositionY pgtype.Int4      `db:"position_y"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at"`
}

// One step in a generated learning path.
type BridgrSkillGapPathStep struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to skill_gap_learning_paths.uuid
	PathUuid pgtype.UUID `db:"path_uuid"`
	// Order within the path (0-based or 1-based per app convention)
	StepIndex      int32          `db:"step_index"`
	Title          string         `db:"title"`
	Rationale      pgtype.Text    `db:"rationale"`
	EstimatedHours pgtype.Numeric `db:"estimated_hours"`
	ResourceUri    pgtype.Text    `db:"resource_uri"`
	ResourceKind   pgtype.Text    `db:"resource_kind"`
	// App-enforced FK to founder_learning_items.uuid when linked
	FounderLearningItemUuid pgtype.UUID `db:"founder_learning_item_uuid"`
	// App-enforced FK to course lesson when linked
	CourseLessonUuid pgtype.UUID `db:"course_lesson_uuid"`
	// JSON array of graph node_key values this step addresses
	LinkedNodeKeys []byte           `db:"linked_node_keys"`
	Metadata       []byte           `db:"metadata"`
	CreatedAt      pgtype.Timestamp `db:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at"`
}

// Prerequisite edges between steps in a learning path (DAG).
type BridgrSkillGapPathStepDep struct {
	Uuid pgtype.UUID `db:"uuid"`
	ID   int64       `db:"id"`
	// App-enforced FK to skill_gap_learning_paths.uuid
	PathUuid pgtype.UUID `db:"path_uuid"`
	// App-enforced FK to skill_gap_path_steps.uuid — dependent step
	StepUuid pgtype.UUID `db:"step_uuid"`
	// App-enforced FK to skill_gap_path_steps.uuid — must be done first
	DependsOnStepUuid pgtype.UUID      `db:"depends_on_step_uuid"`
	CreatedAt         pgtype.Timestamp `db:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at"`
}
