// Package bridgr provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package bridgr

import (
	"fmt"
	"net/http"

	. "github.com/Kanishkmittal55/bridgr-api/pkg/types"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Generate a presigned URL for file upload
	// (POST /v1/autograph/upload-url)
	V1PostGenerateUploadUrl(w http.ResponseWriter, r *http.Request, params V1PostGenerateUploadUrlParams)
	// Create skill-gap analysis
	// (POST /v1/bridgr/analyses)
	V1PostBridgrAnalyses(w http.ResponseWriter, r *http.Request, params V1PostBridgrAnalysesParams)
	// Delete analysis by UUID
	// (DELETE /v1/bridgr/analyses/{analysisUUID})
	V1DeleteBridgrAnalysis(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1DeleteBridgrAnalysisParams)
	// Get analysis by UUID
	// (GET /v1/bridgr/analyses/{analysisUUID})
	V1GetBridgrAnalysis(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1GetBridgrAnalysisParams)
	// Get browser-readable URL for the analysis CV asset
	// (GET /v1/bridgr/analyses/{analysisUUID}/assets/cv/read-url)
	V1GetBridgrAnalysisCvAssetReadUrl(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1GetBridgrAnalysisCvAssetReadUrlParams)
	// Get browser-readable URL for the analysis job description asset
	// (GET /v1/bridgr/analyses/{analysisUUID}/assets/jd/read-url)
	V1GetBridgrAnalysisJdAssetReadUrl(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1GetBridgrAnalysisJdAssetReadUrlParams)
	// Coverage snapshot for analysis
	// (GET /v1/bridgr/analyses/{analysisUUID}/coverage)
	V1GetBridgrAnalysisCoverage(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1GetBridgrAnalysisCoverageParams)
	// Delete all graphs for analysis
	// (DELETE /v1/bridgr/analyses/{analysisUUID}/graphs)
	V1DeleteBridgrAnalysisGraphs(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1DeleteBridgrAnalysisGraphsParams)
	// List graphs for analysis
	// (GET /v1/bridgr/analyses/{analysisUUID}/graphs)
	V1GetBridgrAnalysisGraphs(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1GetBridgrAnalysisGraphsParams)
	// Create skill graph for analysis
	// (POST /v1/bridgr/analyses/{analysisUUID}/graphs)
	V1PostBridgrAnalysisGraphs(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1PostBridgrAnalysisGraphsParams)
	// Get graph by analysis and kind
	// (GET /v1/bridgr/analyses/{analysisUUID}/graphs/{kind})
	V1GetBridgrAnalysisGraphByKind(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, kind BridgrSkillGapGraphKind, params V1GetBridgrAnalysisGraphByKindParams)
	// Delete all learning path versions for analysis
	// (DELETE /v1/bridgr/analyses/{analysisUUID}/learning-path)
	V1DeleteBridgrAnalysisLearningPath(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1DeleteBridgrAnalysisLearningPathParams)
	// Latest learning path for analysis
	// (GET /v1/bridgr/analyses/{analysisUUID}/learning-path)
	V1GetBridgrAnalysisLearningPath(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1GetBridgrAnalysisLearningPathParams)
	// Create learning path for analysis
	// (POST /v1/bridgr/analyses/{analysisUUID}/learning-path)
	V1PostBridgrAnalysisLearningPath(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1PostBridgrAnalysisLearningPathParams)
	// Matched skills (role nodes that exist on candidate graph)
	// (GET /v1/bridgr/analyses/{analysisUUID}/nodes/matched)
	V1GetBridgrAnalysisNodesMatched(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1GetBridgrAnalysisNodesMatchedParams)
	// Skill gaps (required role skills missing from candidate)
	// (GET /v1/bridgr/analyses/{analysisUUID}/nodes/unmatched)
	V1GetBridgrAnalysisNodesUnmatched(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1GetBridgrAnalysisNodesUnmatchedParams)
	// Update analysis pipeline status
	// (PATCH /v1/bridgr/analyses/{analysisUUID}/status)
	V1PatchBridgrAnalysisStatus(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1PatchBridgrAnalysisStatusParams)
	// List edges for graph
	// (GET /v1/bridgr/graphs/{graphUUID}/edges)
	V1GetBridgrGraphEdges(w http.ResponseWriter, r *http.Request, graphUUID openapi_types.UUID, params V1GetBridgrGraphEdgesParams)
	// Create directed edge in graph
	// (POST /v1/bridgr/graphs/{graphUUID}/edges)
	V1PostBridgrGraphEdges(w http.ResponseWriter, r *http.Request, graphUUID openapi_types.UUID, params V1PostBridgrGraphEdgesParams)
	// List nodes for graph
	// (GET /v1/bridgr/graphs/{graphUUID}/nodes)
	V1GetBridgrGraphNodes(w http.ResponseWriter, r *http.Request, graphUUID openapi_types.UUID, params V1GetBridgrGraphNodesParams)
	// Create graph node
	// (POST /v1/bridgr/graphs/{graphUUID}/nodes)
	V1PostBridgrGraphNodes(w http.ResponseWriter, r *http.Request, graphUUID openapi_types.UUID, params V1PostBridgrGraphNodesParams)
	// Get node by graph and node_key
	// (GET /v1/bridgr/graphs/{graphUUID}/nodes/by-key/{nodeKey})
	V1GetBridgrGraphNodeByKey(w http.ResponseWriter, r *http.Request, graphUUID openapi_types.UUID, nodeKey string, params V1GetBridgrGraphNodeByKeyParams)
	// Get job candidate by UUID
	// (GET /v1/bridgr/job-candidates/{candidateUUID})
	V1GetBridgrJobCandidate(w http.ResponseWriter, r *http.Request, candidateUUID openapi_types.UUID, params V1GetBridgrJobCandidateParams)
	// Get one discovery run by UUID
	// (GET /v1/bridgr/job-discovery/runs/{runUUID})
	V1GetBridgrJobDiscoveryRun(w http.ResponseWriter, r *http.Request, runUUID openapi_types.UUID, params V1GetBridgrJobDiscoveryRunParams)
	// Update notification (mark seen or status)
	// (PATCH /v1/bridgr/job-notifications/{notificationUUID})
	V1PatchBridgrJobNotification(w http.ResponseWriter, r *http.Request, notificationUUID openapi_types.UUID, params V1PatchBridgrJobNotificationParams)
	// List ordered path steps
	// (GET /v1/bridgr/paths/{pathUUID}/steps)
	V1GetBridgrPathSteps(w http.ResponseWriter, r *http.Request, pathUUID openapi_types.UUID, params V1GetBridgrPathStepsParams)
	// Bridgr liveness
	// (GET /v1/bridgr/ping)
	V1GetBridgrPing(w http.ResponseWriter, r *http.Request)
	// List skill-gap analyses for a user
	// (GET /v1/bridgr/users/{userID}/analyses)
	V1GetBridgrUserAnalyses(w http.ResponseWriter, r *http.Request, userID int32, params V1GetBridgrUserAnalysesParams)
	// List analyses with coverage for a user
	// (GET /v1/bridgr/users/{userID}/coverage)
	V1GetBridgrUserCoverage(w http.ResponseWriter, r *http.Request, userID int32, params V1GetBridgrUserCoverageParams)
	// List job candidates for user
	// (GET /v1/bridgr/users/{userID}/job-candidates)
	V1GetBridgrUserJobCandidates(w http.ResponseWriter, r *http.Request, userID int32, params V1GetBridgrUserJobCandidatesParams)
	// List job discovery runs for user (newest first)
	// (GET /v1/bridgr/users/{userID}/job-discovery/runs)
	V1GetBridgrUserJobDiscoveryRuns(w http.ResponseWriter, r *http.Request, userID int32, params V1GetBridgrUserJobDiscoveryRunsParams)
	// Start a job discovery run (async via queue when configured)
	// (POST /v1/bridgr/users/{userID}/job-discovery/runs)
	V1PostBridgrUserJobDiscoveryRuns(w http.ResponseWriter, r *http.Request, userID int32, params V1PostBridgrUserJobDiscoveryRunsParams)
	// Cancel an in-progress job discovery run (signals Radar CancelCrawl when configured)
	// (POST /v1/bridgr/users/{userID}/job-discovery/runs/{runUUID}/cancel)
	V1PostBridgrUserJobDiscoveryRunCancel(w http.ResponseWriter, r *http.Request, userID int32, runUUID openapi_types.UUID, params V1PostBridgrUserJobDiscoveryRunCancelParams)
	// List job notifications for user
	// (GET /v1/bridgr/users/{userID}/job-notifications)
	V1GetBridgrUserJobNotifications(w http.ResponseWriter, r *http.Request, userID int32, params V1GetBridgrUserJobNotificationsParams)
	// Get job search profile for user
	// (GET /v1/bridgr/users/{userID}/job-search-profile)
	V1GetBridgrUserJobSearchProfile(w http.ResponseWriter, r *http.Request, userID int32, params V1GetBridgrUserJobSearchProfileParams)
	// Create or update job search profile
	// (PUT /v1/bridgr/users/{userID}/job-search-profile)
	V1PutBridgrUserJobSearchProfile(w http.ResponseWriter, r *http.Request, userID int32, params V1PutBridgrUserJobSearchProfileParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Generate a presigned URL for file upload
// (POST /v1/autograph/upload-url)
func (_ Unimplemented) V1PostGenerateUploadUrl(w http.ResponseWriter, r *http.Request, params V1PostGenerateUploadUrlParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create skill-gap analysis
// (POST /v1/bridgr/analyses)
func (_ Unimplemented) V1PostBridgrAnalyses(w http.ResponseWriter, r *http.Request, params V1PostBridgrAnalysesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete analysis by UUID
// (DELETE /v1/bridgr/analyses/{analysisUUID})
func (_ Unimplemented) V1DeleteBridgrAnalysis(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1DeleteBridgrAnalysisParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get analysis by UUID
// (GET /v1/bridgr/analyses/{analysisUUID})
func (_ Unimplemented) V1GetBridgrAnalysis(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1GetBridgrAnalysisParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get browser-readable URL for the analysis CV asset
// (GET /v1/bridgr/analyses/{analysisUUID}/assets/cv/read-url)
func (_ Unimplemented) V1GetBridgrAnalysisCvAssetReadUrl(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1GetBridgrAnalysisCvAssetReadUrlParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get browser-readable URL for the analysis job description asset
// (GET /v1/bridgr/analyses/{analysisUUID}/assets/jd/read-url)
func (_ Unimplemented) V1GetBridgrAnalysisJdAssetReadUrl(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1GetBridgrAnalysisJdAssetReadUrlParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Coverage snapshot for analysis
// (GET /v1/bridgr/analyses/{analysisUUID}/coverage)
func (_ Unimplemented) V1GetBridgrAnalysisCoverage(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1GetBridgrAnalysisCoverageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete all graphs for analysis
// (DELETE /v1/bridgr/analyses/{analysisUUID}/graphs)
func (_ Unimplemented) V1DeleteBridgrAnalysisGraphs(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1DeleteBridgrAnalysisGraphsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List graphs for analysis
// (GET /v1/bridgr/analyses/{analysisUUID}/graphs)
func (_ Unimplemented) V1GetBridgrAnalysisGraphs(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1GetBridgrAnalysisGraphsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create skill graph for analysis
// (POST /v1/bridgr/analyses/{analysisUUID}/graphs)
func (_ Unimplemented) V1PostBridgrAnalysisGraphs(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1PostBridgrAnalysisGraphsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get graph by analysis and kind
// (GET /v1/bridgr/analyses/{analysisUUID}/graphs/{kind})
func (_ Unimplemented) V1GetBridgrAnalysisGraphByKind(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, kind BridgrSkillGapGraphKind, params V1GetBridgrAnalysisGraphByKindParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete all learning path versions for analysis
// (DELETE /v1/bridgr/analyses/{analysisUUID}/learning-path)
func (_ Unimplemented) V1DeleteBridgrAnalysisLearningPath(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1DeleteBridgrAnalysisLearningPathParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Latest learning path for analysis
// (GET /v1/bridgr/analyses/{analysisUUID}/learning-path)
func (_ Unimplemented) V1GetBridgrAnalysisLearningPath(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1GetBridgrAnalysisLearningPathParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create learning path for analysis
// (POST /v1/bridgr/analyses/{analysisUUID}/learning-path)
func (_ Unimplemented) V1PostBridgrAnalysisLearningPath(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1PostBridgrAnalysisLearningPathParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Matched skills (role nodes that exist on candidate graph)
// (GET /v1/bridgr/analyses/{analysisUUID}/nodes/matched)
func (_ Unimplemented) V1GetBridgrAnalysisNodesMatched(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1GetBridgrAnalysisNodesMatchedParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Skill gaps (required role skills missing from candidate)
// (GET /v1/bridgr/analyses/{analysisUUID}/nodes/unmatched)
func (_ Unimplemented) V1GetBridgrAnalysisNodesUnmatched(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1GetBridgrAnalysisNodesUnmatchedParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update analysis pipeline status
// (PATCH /v1/bridgr/analyses/{analysisUUID}/status)
func (_ Unimplemented) V1PatchBridgrAnalysisStatus(w http.ResponseWriter, r *http.Request, analysisUUID openapi_types.UUID, params V1PatchBridgrAnalysisStatusParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List edges for graph
// (GET /v1/bridgr/graphs/{graphUUID}/edges)
func (_ Unimplemented) V1GetBridgrGraphEdges(w http.ResponseWriter, r *http.Request, graphUUID openapi_types.UUID, params V1GetBridgrGraphEdgesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create directed edge in graph
// (POST /v1/bridgr/graphs/{graphUUID}/edges)
func (_ Unimplemented) V1PostBridgrGraphEdges(w http.ResponseWriter, r *http.Request, graphUUID openapi_types.UUID, params V1PostBridgrGraphEdgesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List nodes for graph
// (GET /v1/bridgr/graphs/{graphUUID}/nodes)
func (_ Unimplemented) V1GetBridgrGraphNodes(w http.ResponseWriter, r *http.Request, graphUUID openapi_types.UUID, params V1GetBridgrGraphNodesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create graph node
// (POST /v1/bridgr/graphs/{graphUUID}/nodes)
func (_ Unimplemented) V1PostBridgrGraphNodes(w http.ResponseWriter, r *http.Request, graphUUID openapi_types.UUID, params V1PostBridgrGraphNodesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get node by graph and node_key
// (GET /v1/bridgr/graphs/{graphUUID}/nodes/by-key/{nodeKey})
func (_ Unimplemented) V1GetBridgrGraphNodeByKey(w http.ResponseWriter, r *http.Request, graphUUID openapi_types.UUID, nodeKey string, params V1GetBridgrGraphNodeByKeyParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get job candidate by UUID
// (GET /v1/bridgr/job-candidates/{candidateUUID})
func (_ Unimplemented) V1GetBridgrJobCandidate(w http.ResponseWriter, r *http.Request, candidateUUID openapi_types.UUID, params V1GetBridgrJobCandidateParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get one discovery run by UUID
// (GET /v1/bridgr/job-discovery/runs/{runUUID})
func (_ Unimplemented) V1GetBridgrJobDiscoveryRun(w http.ResponseWriter, r *http.Request, runUUID openapi_types.UUID, params V1GetBridgrJobDiscoveryRunParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update notification (mark seen or status)
// (PATCH /v1/bridgr/job-notifications/{notificationUUID})
func (_ Unimplemented) V1PatchBridgrJobNotification(w http.ResponseWriter, r *http.Request, notificationUUID openapi_types.UUID, params V1PatchBridgrJobNotificationParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List ordered path steps
// (GET /v1/bridgr/paths/{pathUUID}/steps)
func (_ Unimplemented) V1GetBridgrPathSteps(w http.ResponseWriter, r *http.Request, pathUUID openapi_types.UUID, params V1GetBridgrPathStepsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Bridgr liveness
// (GET /v1/bridgr/ping)
func (_ Unimplemented) V1GetBridgrPing(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List skill-gap analyses for a user
// (GET /v1/bridgr/users/{userID}/analyses)
func (_ Unimplemented) V1GetBridgrUserAnalyses(w http.ResponseWriter, r *http.Request, userID int32, params V1GetBridgrUserAnalysesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List analyses with coverage for a user
// (GET /v1/bridgr/users/{userID}/coverage)
func (_ Unimplemented) V1GetBridgrUserCoverage(w http.ResponseWriter, r *http.Request, userID int32, params V1GetBridgrUserCoverageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List job candidates for user
// (GET /v1/bridgr/users/{userID}/job-candidates)
func (_ Unimplemented) V1GetBridgrUserJobCandidates(w http.ResponseWriter, r *http.Request, userID int32, params V1GetBridgrUserJobCandidatesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List job discovery runs for user (newest first)
// (GET /v1/bridgr/users/{userID}/job-discovery/runs)
func (_ Unimplemented) V1GetBridgrUserJobDiscoveryRuns(w http.ResponseWriter, r *http.Request, userID int32, params V1GetBridgrUserJobDiscoveryRunsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Start a job discovery run (async via queue when configured)
// (POST /v1/bridgr/users/{userID}/job-discovery/runs)
func (_ Unimplemented) V1PostBridgrUserJobDiscoveryRuns(w http.ResponseWriter, r *http.Request, userID int32, params V1PostBridgrUserJobDiscoveryRunsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel an in-progress job discovery run (signals Radar CancelCrawl when configured)
// (POST /v1/bridgr/users/{userID}/job-discovery/runs/{runUUID}/cancel)
func (_ Unimplemented) V1PostBridgrUserJobDiscoveryRunCancel(w http.ResponseWriter, r *http.Request, userID int32, runUUID openapi_types.UUID, params V1PostBridgrUserJobDiscoveryRunCancelParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List job notifications for user
// (GET /v1/bridgr/users/{userID}/job-notifications)
func (_ Unimplemented) V1GetBridgrUserJobNotifications(w http.ResponseWriter, r *http.Request, userID int32, params V1GetBridgrUserJobNotificationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get job search profile for user
// (GET /v1/bridgr/users/{userID}/job-search-profile)
func (_ Unimplemented) V1GetBridgrUserJobSearchProfile(w http.ResponseWriter, r *http.Request, userID int32, params V1GetBridgrUserJobSearchProfileParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create or update job search profile
// (PUT /v1/bridgr/users/{userID}/job-search-profile)
func (_ Unimplemented) V1PutBridgrUserJobSearchProfile(w http.ResponseWriter, r *http.Request, userID int32, params V1PutBridgrUserJobSearchProfileParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// V1PostGenerateUploadUrl operation middleware
func (siw *ServerInterfaceWrapper) V1PostGenerateUploadUrl(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params V1PostGenerateUploadUrlParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1PostGenerateUploadUrl(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1PostBridgrAnalyses operation middleware
func (siw *ServerInterfaceWrapper) V1PostBridgrAnalyses(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params V1PostBridgrAnalysesParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1PostBridgrAnalyses(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1DeleteBridgrAnalysis operation middleware
func (siw *ServerInterfaceWrapper) V1DeleteBridgrAnalysis(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "analysisUUID" -------------
	var analysisUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "analysisUUID", runtime.ParamLocationPath, chi.URLParam(r, "analysisUUID"), &analysisUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1DeleteBridgrAnalysisParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1DeleteBridgrAnalysis(w, r, analysisUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrAnalysis operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrAnalysis(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "analysisUUID" -------------
	var analysisUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "analysisUUID", runtime.ParamLocationPath, chi.URLParam(r, "analysisUUID"), &analysisUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrAnalysisParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrAnalysis(w, r, analysisUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrAnalysisCvAssetReadUrl operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrAnalysisCvAssetReadUrl(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "analysisUUID" -------------
	var analysisUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "analysisUUID", runtime.ParamLocationPath, chi.URLParam(r, "analysisUUID"), &analysisUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrAnalysisCvAssetReadUrlParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrAnalysisCvAssetReadUrl(w, r, analysisUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrAnalysisJdAssetReadUrl operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrAnalysisJdAssetReadUrl(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "analysisUUID" -------------
	var analysisUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "analysisUUID", runtime.ParamLocationPath, chi.URLParam(r, "analysisUUID"), &analysisUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrAnalysisJdAssetReadUrlParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrAnalysisJdAssetReadUrl(w, r, analysisUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrAnalysisCoverage operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrAnalysisCoverage(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "analysisUUID" -------------
	var analysisUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "analysisUUID", runtime.ParamLocationPath, chi.URLParam(r, "analysisUUID"), &analysisUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrAnalysisCoverageParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrAnalysisCoverage(w, r, analysisUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1DeleteBridgrAnalysisGraphs operation middleware
func (siw *ServerInterfaceWrapper) V1DeleteBridgrAnalysisGraphs(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "analysisUUID" -------------
	var analysisUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "analysisUUID", runtime.ParamLocationPath, chi.URLParam(r, "analysisUUID"), &analysisUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1DeleteBridgrAnalysisGraphsParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1DeleteBridgrAnalysisGraphs(w, r, analysisUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrAnalysisGraphs operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrAnalysisGraphs(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "analysisUUID" -------------
	var analysisUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "analysisUUID", runtime.ParamLocationPath, chi.URLParam(r, "analysisUUID"), &analysisUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrAnalysisGraphsParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrAnalysisGraphs(w, r, analysisUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1PostBridgrAnalysisGraphs operation middleware
func (siw *ServerInterfaceWrapper) V1PostBridgrAnalysisGraphs(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "analysisUUID" -------------
	var analysisUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "analysisUUID", runtime.ParamLocationPath, chi.URLParam(r, "analysisUUID"), &analysisUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1PostBridgrAnalysisGraphsParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1PostBridgrAnalysisGraphs(w, r, analysisUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrAnalysisGraphByKind operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrAnalysisGraphByKind(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "analysisUUID" -------------
	var analysisUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "analysisUUID", runtime.ParamLocationPath, chi.URLParam(r, "analysisUUID"), &analysisUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisUUID", Err: err})
		return
	}

	// ------------- Path parameter "kind" -------------
	var kind BridgrSkillGapGraphKind

	err = runtime.BindStyledParameterWithLocation("simple", false, "kind", runtime.ParamLocationPath, chi.URLParam(r, "kind"), &kind)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "kind", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrAnalysisGraphByKindParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrAnalysisGraphByKind(w, r, analysisUUID, kind, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1DeleteBridgrAnalysisLearningPath operation middleware
func (siw *ServerInterfaceWrapper) V1DeleteBridgrAnalysisLearningPath(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "analysisUUID" -------------
	var analysisUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "analysisUUID", runtime.ParamLocationPath, chi.URLParam(r, "analysisUUID"), &analysisUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1DeleteBridgrAnalysisLearningPathParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1DeleteBridgrAnalysisLearningPath(w, r, analysisUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrAnalysisLearningPath operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrAnalysisLearningPath(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "analysisUUID" -------------
	var analysisUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "analysisUUID", runtime.ParamLocationPath, chi.URLParam(r, "analysisUUID"), &analysisUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrAnalysisLearningPathParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrAnalysisLearningPath(w, r, analysisUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1PostBridgrAnalysisLearningPath operation middleware
func (siw *ServerInterfaceWrapper) V1PostBridgrAnalysisLearningPath(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "analysisUUID" -------------
	var analysisUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "analysisUUID", runtime.ParamLocationPath, chi.URLParam(r, "analysisUUID"), &analysisUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1PostBridgrAnalysisLearningPathParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1PostBridgrAnalysisLearningPath(w, r, analysisUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrAnalysisNodesMatched operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrAnalysisNodesMatched(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "analysisUUID" -------------
	var analysisUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "analysisUUID", runtime.ParamLocationPath, chi.URLParam(r, "analysisUUID"), &analysisUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrAnalysisNodesMatchedParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrAnalysisNodesMatched(w, r, analysisUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrAnalysisNodesUnmatched operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrAnalysisNodesUnmatched(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "analysisUUID" -------------
	var analysisUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "analysisUUID", runtime.ParamLocationPath, chi.URLParam(r, "analysisUUID"), &analysisUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrAnalysisNodesUnmatchedParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrAnalysisNodesUnmatched(w, r, analysisUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1PatchBridgrAnalysisStatus operation middleware
func (siw *ServerInterfaceWrapper) V1PatchBridgrAnalysisStatus(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "analysisUUID" -------------
	var analysisUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "analysisUUID", runtime.ParamLocationPath, chi.URLParam(r, "analysisUUID"), &analysisUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1PatchBridgrAnalysisStatusParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1PatchBridgrAnalysisStatus(w, r, analysisUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrGraphEdges operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrGraphEdges(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "graphUUID" -------------
	var graphUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "graphUUID", runtime.ParamLocationPath, chi.URLParam(r, "graphUUID"), &graphUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "graphUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrGraphEdgesParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrGraphEdges(w, r, graphUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1PostBridgrGraphEdges operation middleware
func (siw *ServerInterfaceWrapper) V1PostBridgrGraphEdges(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "graphUUID" -------------
	var graphUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "graphUUID", runtime.ParamLocationPath, chi.URLParam(r, "graphUUID"), &graphUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "graphUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1PostBridgrGraphEdgesParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1PostBridgrGraphEdges(w, r, graphUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrGraphNodes operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrGraphNodes(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "graphUUID" -------------
	var graphUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "graphUUID", runtime.ParamLocationPath, chi.URLParam(r, "graphUUID"), &graphUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "graphUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrGraphNodesParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrGraphNodes(w, r, graphUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1PostBridgrGraphNodes operation middleware
func (siw *ServerInterfaceWrapper) V1PostBridgrGraphNodes(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "graphUUID" -------------
	var graphUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "graphUUID", runtime.ParamLocationPath, chi.URLParam(r, "graphUUID"), &graphUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "graphUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1PostBridgrGraphNodesParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1PostBridgrGraphNodes(w, r, graphUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrGraphNodeByKey operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrGraphNodeByKey(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "graphUUID" -------------
	var graphUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "graphUUID", runtime.ParamLocationPath, chi.URLParam(r, "graphUUID"), &graphUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "graphUUID", Err: err})
		return
	}

	// ------------- Path parameter "nodeKey" -------------
	var nodeKey string

	err = runtime.BindStyledParameterWithLocation("simple", false, "nodeKey", runtime.ParamLocationPath, chi.URLParam(r, "nodeKey"), &nodeKey)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "nodeKey", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrGraphNodeByKeyParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrGraphNodeByKey(w, r, graphUUID, nodeKey, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrJobCandidate operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrJobCandidate(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "candidateUUID" -------------
	var candidateUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "candidateUUID", runtime.ParamLocationPath, chi.URLParam(r, "candidateUUID"), &candidateUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "candidateUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrJobCandidateParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrJobCandidate(w, r, candidateUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrJobDiscoveryRun operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrJobDiscoveryRun(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "runUUID" -------------
	var runUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "runUUID", runtime.ParamLocationPath, chi.URLParam(r, "runUUID"), &runUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrJobDiscoveryRunParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrJobDiscoveryRun(w, r, runUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1PatchBridgrJobNotification operation middleware
func (siw *ServerInterfaceWrapper) V1PatchBridgrJobNotification(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "notificationUUID" -------------
	var notificationUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "notificationUUID", runtime.ParamLocationPath, chi.URLParam(r, "notificationUUID"), &notificationUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "notificationUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1PatchBridgrJobNotificationParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1PatchBridgrJobNotification(w, r, notificationUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrPathSteps operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrPathSteps(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "pathUUID" -------------
	var pathUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "pathUUID", runtime.ParamLocationPath, chi.URLParam(r, "pathUUID"), &pathUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pathUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrPathStepsParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrPathSteps(w, r, pathUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrPing operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrPing(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrPing(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrUserAnalyses operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrUserAnalyses(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "userID", runtime.ParamLocationPath, chi.URLParam(r, "userID"), &userID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrUserAnalysesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrUserAnalyses(w, r, userID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrUserCoverage operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrUserCoverage(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "userID", runtime.ParamLocationPath, chi.URLParam(r, "userID"), &userID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrUserCoverageParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrUserCoverage(w, r, userID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrUserJobCandidates operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrUserJobCandidates(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "userID", runtime.ParamLocationPath, chi.URLParam(r, "userID"), &userID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrUserJobCandidatesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "discovery_run_uuid" -------------

	err = runtime.BindQueryParameter("form", true, false, "discovery_run_uuid", r.URL.Query(), &params.DiscoveryRunUuid)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "discovery_run_uuid", Err: err})
		return
	}

	// ------------- Optional query parameter "ingestion_status" -------------

	err = runtime.BindQueryParameter("form", true, false, "ingestion_status", r.URL.Query(), &params.IngestionStatus)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ingestion_status", Err: err})
		return
	}

	// ------------- Optional query parameter "source_board" -------------

	err = runtime.BindQueryParameter("form", true, false, "source_board", r.URL.Query(), &params.SourceBoard)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source_board", Err: err})
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrUserJobCandidates(w, r, userID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrUserJobDiscoveryRuns operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrUserJobDiscoveryRuns(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "userID", runtime.ParamLocationPath, chi.URLParam(r, "userID"), &userID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrUserJobDiscoveryRunsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrUserJobDiscoveryRuns(w, r, userID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1PostBridgrUserJobDiscoveryRuns operation middleware
func (siw *ServerInterfaceWrapper) V1PostBridgrUserJobDiscoveryRuns(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "userID", runtime.ParamLocationPath, chi.URLParam(r, "userID"), &userID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1PostBridgrUserJobDiscoveryRunsParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1PostBridgrUserJobDiscoveryRuns(w, r, userID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1PostBridgrUserJobDiscoveryRunCancel operation middleware
func (siw *ServerInterfaceWrapper) V1PostBridgrUserJobDiscoveryRunCancel(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "userID", runtime.ParamLocationPath, chi.URLParam(r, "userID"), &userID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	// ------------- Path parameter "runUUID" -------------
	var runUUID openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "runUUID", runtime.ParamLocationPath, chi.URLParam(r, "runUUID"), &runUUID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runUUID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1PostBridgrUserJobDiscoveryRunCancelParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1PostBridgrUserJobDiscoveryRunCancel(w, r, userID, runUUID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrUserJobNotifications operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrUserJobNotifications(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "userID", runtime.ParamLocationPath, chi.URLParam(r, "userID"), &userID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrUserJobNotificationsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrUserJobNotifications(w, r, userID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetBridgrUserJobSearchProfile operation middleware
func (siw *ServerInterfaceWrapper) V1GetBridgrUserJobSearchProfile(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "userID", runtime.ParamLocationPath, chi.URLParam(r, "userID"), &userID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetBridgrUserJobSearchProfileParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetBridgrUserJobSearchProfile(w, r, userID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1PutBridgrUserJobSearchProfile operation middleware
func (siw *ServerInterfaceWrapper) V1PutBridgrUserJobSearchProfile(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "userID", runtime.ParamLocationPath, chi.URLParam(r, "userID"), &userID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params V1PutBridgrUserJobSearchProfileParams

	headers := r.Header

	// ------------- Required header parameter "X-API-KEY" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-API-KEY")]; found {
		var XAPIKEY string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-API-KEY", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-API-KEY", runtime.ParamLocationHeader, valueList[0], &XAPIKEY)
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-API-KEY", Err: err})
			return
		}

		params.XAPIKEY = XAPIKEY

	} else {
		err := fmt.Errorf("Header parameter X-API-KEY is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-API-KEY", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1PutBridgrUserJobSearchProfile(w, r, userID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/autograph/upload-url", wrapper.V1PostGenerateUploadUrl)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/bridgr/analyses", wrapper.V1PostBridgrAnalyses)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/bridgr/analyses/{analysisUUID}", wrapper.V1DeleteBridgrAnalysis)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/analyses/{analysisUUID}", wrapper.V1GetBridgrAnalysis)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/analyses/{analysisUUID}/assets/cv/read-url", wrapper.V1GetBridgrAnalysisCvAssetReadUrl)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/analyses/{analysisUUID}/assets/jd/read-url", wrapper.V1GetBridgrAnalysisJdAssetReadUrl)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/analyses/{analysisUUID}/coverage", wrapper.V1GetBridgrAnalysisCoverage)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/bridgr/analyses/{analysisUUID}/graphs", wrapper.V1DeleteBridgrAnalysisGraphs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/analyses/{analysisUUID}/graphs", wrapper.V1GetBridgrAnalysisGraphs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/bridgr/analyses/{analysisUUID}/graphs", wrapper.V1PostBridgrAnalysisGraphs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/analyses/{analysisUUID}/graphs/{kind}", wrapper.V1GetBridgrAnalysisGraphByKind)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/bridgr/analyses/{analysisUUID}/learning-path", wrapper.V1DeleteBridgrAnalysisLearningPath)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/analyses/{analysisUUID}/learning-path", wrapper.V1GetBridgrAnalysisLearningPath)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/bridgr/analyses/{analysisUUID}/learning-path", wrapper.V1PostBridgrAnalysisLearningPath)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/analyses/{analysisUUID}/nodes/matched", wrapper.V1GetBridgrAnalysisNodesMatched)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/analyses/{analysisUUID}/nodes/unmatched", wrapper.V1GetBridgrAnalysisNodesUnmatched)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/bridgr/analyses/{analysisUUID}/status", wrapper.V1PatchBridgrAnalysisStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/graphs/{graphUUID}/edges", wrapper.V1GetBridgrGraphEdges)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/bridgr/graphs/{graphUUID}/edges", wrapper.V1PostBridgrGraphEdges)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/graphs/{graphUUID}/nodes", wrapper.V1GetBridgrGraphNodes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/bridgr/graphs/{graphUUID}/nodes", wrapper.V1PostBridgrGraphNodes)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/graphs/{graphUUID}/nodes/by-key/{nodeKey}", wrapper.V1GetBridgrGraphNodeByKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/job-candidates/{candidateUUID}", wrapper.V1GetBridgrJobCandidate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/job-discovery/runs/{runUUID}", wrapper.V1GetBridgrJobDiscoveryRun)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/bridgr/job-notifications/{notificationUUID}", wrapper.V1PatchBridgrJobNotification)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/paths/{pathUUID}/steps", wrapper.V1GetBridgrPathSteps)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/ping", wrapper.V1GetBridgrPing)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/users/{userID}/analyses", wrapper.V1GetBridgrUserAnalyses)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/users/{userID}/coverage", wrapper.V1GetBridgrUserCoverage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/users/{userID}/job-candidates", wrapper.V1GetBridgrUserJobCandidates)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/users/{userID}/job-discovery/runs", wrapper.V1GetBridgrUserJobDiscoveryRuns)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/bridgr/users/{userID}/job-discovery/runs", wrapper.V1PostBridgrUserJobDiscoveryRuns)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/bridgr/users/{userID}/job-discovery/runs/{runUUID}/cancel", wrapper.V1PostBridgrUserJobDiscoveryRunCancel)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/users/{userID}/job-notifications", wrapper.V1GetBridgrUserJobNotifications)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/bridgr/users/{userID}/job-search-profile", wrapper.V1GetBridgrUserJobSearchProfile)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/v1/bridgr/users/{userID}/job-search-profile", wrapper.V1PutBridgrUserJobSearchProfile)
	})

	return r
}
