// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package types

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BridgrSkillGapAnalysisStatus.
const (
	BridgrSkillGapPending BridgrSkillGapAnalysisStatus = "pending"
	Completed             BridgrSkillGapAnalysisStatus = "completed"
	Extracting            BridgrSkillGapAnalysisStatus = "extracting"
	Failed                BridgrSkillGapAnalysisStatus = "failed"
	Graphed               BridgrSkillGapAnalysisStatus = "graphed"
	Pathed                BridgrSkillGapAnalysisStatus = "pathed"
)

// Defines values for BridgrSkillGapGraphKind.
const (
	Candidate       BridgrSkillGapGraphKind = "candidate"
	RoleRequirement BridgrSkillGapGraphKind = "role_requirement"
)

// BridgrPingResponse defines model for BridgrPingResponse.
type BridgrPingResponse struct {
	Product string `json:"product"`
	Status  string `json:"status"`
}

// BridgrSkillGapAnalysis One CV/JD skill-gap analysis run
type BridgrSkillGapAnalysis struct {
	CreatedAt          time.Time               `json:"created_at"`
	CvAssetUri         *string                 `json:"cv_asset_uri"`
	CvFingerprint      *string                 `json:"cv_fingerprint"`
	ErrorCode          *string                 `json:"error_code"`
	ErrorDetail        *string                 `json:"error_detail"`
	ExtractionPayload  *map[string]interface{} `json:"extraction_payload"`
	FounderPersonaUuid *openapi_types.UUID     `json:"founder_persona_uuid"`
	GapSummary         *map[string]interface{} `json:"gap_summary"`
	Id                 int64                   `json:"id"`
	JdAssetUri         *string                 `json:"jd_asset_uri"`
	JdFingerprint      *string                 `json:"jd_fingerprint"`
	LlmModel           *string                 `json:"llm_model"`
	MermaidDiagram     *string                 `json:"mermaid_diagram"`
	PromptVersion      *string                 `json:"prompt_version"`
	PursuitUuid        *openapi_types.UUID     `json:"pursuit_uuid"`
	SqsMessageId       *string                 `json:"sqs_message_id"`

	// Status Pipeline state aligned with async worker steps
	Status    BridgrSkillGapAnalysisStatus `json:"status"`
	Title     *string                      `json:"title"`
	UpdatedAt time.Time                    `json:"updated_at"`
	UserId    int32                        `json:"user_id"`
	Uuid      openapi_types.UUID           `json:"uuid"`
}

// BridgrSkillGapAnalysisListResponse defines model for BridgrSkillGapAnalysisListResponse.
type BridgrSkillGapAnalysisListResponse struct {
	Analyses []BridgrSkillGapAnalysis `json:"analyses"`
}

// BridgrSkillGapAnalysisStatus Pipeline state aligned with async worker steps
type BridgrSkillGapAnalysisStatus string

// BridgrSkillGapCoverageSnapshot Aggregated coverage for an analysis (derived from graph overlap)
type BridgrSkillGapCoverageSnapshot struct {
	CandidateSkills *interface{} `json:"candidate_skills"`
	CoveragePct     *float32     `json:"coverage_pct"`
	MatchedSkills   *interface{} `json:"matched_skills"`
	RequiredSkills  *interface{} `json:"required_skills"`
}

// BridgrSkillGapEdge defines model for BridgrSkillGapEdge.
type BridgrSkillGapEdge struct {
	CreatedAt    time.Time               `json:"created_at"`
	FromNodeUuid openapi_types.UUID      `json:"from_node_uuid"`
	GraphUuid    openapi_types.UUID      `json:"graph_uuid"`
	Id           int64                   `json:"id"`
	Metadata     *map[string]interface{} `json:"metadata"`
	Relation     string                  `json:"relation"`
	ToNodeUuid   openapi_types.UUID      `json:"to_node_uuid"`
	UpdatedAt    time.Time               `json:"updated_at"`
	Uuid         openapi_types.UUID      `json:"uuid"`
	Weight       *float32                `json:"weight"`
}

// BridgrSkillGapEdgeListResponse defines model for BridgrSkillGapEdgeListResponse.
type BridgrSkillGapEdgeListResponse struct {
	Edges []BridgrSkillGapEdge `json:"edges"`
}

// BridgrSkillGapGraph defines model for BridgrSkillGapGraph.
type BridgrSkillGapGraph struct {
	AnalysisUuid openapi_types.UUID `json:"analysis_uuid"`
	CreatedAt    time.Time          `json:"created_at"`
	Id           int64              `json:"id"`

	// Kind candidate = skills from CV; role_requirement = skills from JD
	Kind      BridgrSkillGapGraphKind `json:"kind"`
	Metadata  *map[string]interface{} `json:"metadata"`
	UpdatedAt time.Time               `json:"updated_at"`
	Uuid      openapi_types.UUID      `json:"uuid"`
}

// BridgrSkillGapGraphKind candidate = skills from CV; role_requirement = skills from JD
type BridgrSkillGapGraphKind string

// BridgrSkillGapGraphListResponse defines model for BridgrSkillGapGraphListResponse.
type BridgrSkillGapGraphListResponse struct {
	Graphs []BridgrSkillGapGraph `json:"graphs"`
}

// BridgrSkillGapLearningPath defines model for BridgrSkillGapLearningPath.
type BridgrSkillGapLearningPath struct {
	Algorithm    *string                 `json:"algorithm"`
	AnalysisUuid openapi_types.UUID      `json:"analysis_uuid"`
	CreatedAt    time.Time               `json:"created_at"`
	Id           int64                   `json:"id"`
	PathMetadata *map[string]interface{} `json:"path_metadata"`
	PathVersion  int32                   `json:"path_version"`
	Title        *string                 `json:"title"`
	UpdatedAt    time.Time               `json:"updated_at"`
	Uuid         openapi_types.UUID      `json:"uuid"`
}

// BridgrSkillGapNode defines model for BridgrSkillGapNode.
type BridgrSkillGapNode struct {
	CreatedAt       time.Time               `json:"created_at"`
	Description     *string                 `json:"description"`
	DisplayName     string                  `json:"display_name"`
	Evidence        *map[string]interface{} `json:"evidence"`
	GraphUuid       openapi_types.UUID      `json:"graph_uuid"`
	Id              int64                   `json:"id"`
	Metadata        *map[string]interface{} `json:"metadata"`
	NodeKey         string                  `json:"node_key"`
	PositionX       *int32                  `json:"position_x"`
	PositionY       *int32                  `json:"position_y"`
	ProficiencyHint *string                 `json:"proficiency_hint"`
	Source          *string                 `json:"source"`
	UpdatedAt       time.Time               `json:"updated_at"`
	Uuid            openapi_types.UUID      `json:"uuid"`
}

// BridgrSkillGapNodeListResponse defines model for BridgrSkillGapNodeListResponse.
type BridgrSkillGapNodeListResponse struct {
	Nodes []BridgrSkillGapNode `json:"nodes"`
}

// BridgrSkillGapPathStep defines model for BridgrSkillGapPathStep.
type BridgrSkillGapPathStep struct {
	CourseLessonUuid        *openapi_types.UUID     `json:"course_lesson_uuid"`
	CreatedAt               time.Time               `json:"created_at"`
	EstimatedHours          *float32                `json:"estimated_hours"`
	FounderLearningItemUuid *openapi_types.UUID     `json:"founder_learning_item_uuid"`
	Id                      int64                   `json:"id"`
	LinkedNodeKeys          *[]string               `json:"linked_node_keys"`
	Metadata                *map[string]interface{} `json:"metadata"`
	PathUuid                openapi_types.UUID      `json:"path_uuid"`
	Rationale               *string                 `json:"rationale"`
	ResourceKind            *string                 `json:"resource_kind"`
	ResourceUri             *string                 `json:"resource_uri"`
	StepIndex               int32                   `json:"step_index"`
	Title                   string                  `json:"title"`
	UpdatedAt               time.Time               `json:"updated_at"`
	Uuid                    openapi_types.UUID      `json:"uuid"`
}

// BridgrSkillGapPathStepListResponse defines model for BridgrSkillGapPathStepListResponse.
type BridgrSkillGapPathStepListResponse struct {
	Steps []BridgrSkillGapPathStep `json:"steps"`
}

// BridgrSkillGapUserCoverageListResponse defines model for BridgrSkillGapUserCoverageListResponse.
type BridgrSkillGapUserCoverageListResponse struct {
	Items []BridgrSkillGapUserCoverageRow `json:"items"`
}

// BridgrSkillGapUserCoverageRow Per-analysis coverage summary for dashboard lists (matches aggregated SQL read)
type BridgrSkillGapUserCoverageRow struct {
	AnalysisId      *int64              `json:"analysis_id,omitempty"`
	AnalysisUuid    *openapi_types.UUID `json:"analysis_uuid,omitempty"`
	CandidateSkills *int64              `json:"candidate_skills"`
	CoveragePct     *float32            `json:"coverage_pct"`
	CreatedAt       *time.Time          `json:"created_at,omitempty"`
	MatchedSkills   *int64              `json:"matched_skills"`
	RequiredSkills  *int64              `json:"required_skills"`

	// Status Pipeline state aligned with async worker steps
	Status *BridgrSkillGapAnalysisStatus `json:"status,omitempty"`
	Title  *string                       `json:"title"`
	UserId *int32                        `json:"user_id,omitempty"`
}

// CreateBridgrSkillGapAnalysisRequest defines model for CreateBridgrSkillGapAnalysisRequest.
type CreateBridgrSkillGapAnalysisRequest struct {
	CvAssetUri         *string             `json:"cv_asset_uri"`
	CvFingerprint      *string             `json:"cv_fingerprint"`
	FounderPersonaUuid *openapi_types.UUID `json:"founder_persona_uuid"`
	JdAssetUri         *string             `json:"jd_asset_uri"`
	JdFingerprint      *string             `json:"jd_fingerprint"`
	LlmModel           *string             `json:"llm_model"`
	PromptVersion      *string             `json:"prompt_version"`
	PursuitUuid        *openapi_types.UUID `json:"pursuit_uuid"`
	Title              *string             `json:"title"`
	UserId             int32               `json:"user_id"`
}

// CreateBridgrSkillGapEdgeRequest defines model for CreateBridgrSkillGapEdgeRequest.
type CreateBridgrSkillGapEdgeRequest struct {
	FromNodeUuid openapi_types.UUID      `json:"from_node_uuid"`
	Metadata     *map[string]interface{} `json:"metadata"`
	Relation     string                  `json:"relation"`
	ToNodeUuid   openapi_types.UUID      `json:"to_node_uuid"`
	Weight       *float32                `json:"weight"`
}

// CreateBridgrSkillGapGraphRequest defines model for CreateBridgrSkillGapGraphRequest.
type CreateBridgrSkillGapGraphRequest struct {
	// Kind candidate = skills from CV; role_requirement = skills from JD
	Kind     BridgrSkillGapGraphKind `json:"kind"`
	Metadata *map[string]interface{} `json:"metadata"`
}

// CreateBridgrSkillGapLearningPathRequest defines model for CreateBridgrSkillGapLearningPathRequest.
type CreateBridgrSkillGapLearningPathRequest struct {
	Algorithm    *string                 `json:"algorithm"`
	PathMetadata *map[string]interface{} `json:"path_metadata"`
	PathVersion  *int32                  `json:"path_version"`
	Title        *string                 `json:"title"`
}

// CreateBridgrSkillGapNodeRequest defines model for CreateBridgrSkillGapNodeRequest.
type CreateBridgrSkillGapNodeRequest struct {
	Description     *string                 `json:"description"`
	DisplayName     string                  `json:"display_name"`
	Evidence        *map[string]interface{} `json:"evidence"`
	Metadata        *map[string]interface{} `json:"metadata"`
	NodeKey         string                  `json:"node_key"`
	PositionX       *int32                  `json:"position_x"`
	PositionY       *int32                  `json:"position_y"`
	ProficiencyHint *string                 `json:"proficiency_hint"`
	Source          *string                 `json:"source"`
}

// PresignedUploadRequest defines model for PresignedUploadRequest.
type PresignedUploadRequest struct {
	// ContentType MIME type of the file. If not provided, will be inferred from filename extension.
	ContentType *string `json:"content_type,omitempty"`

	// Filename Name of the file to be uploaded (used to generate S3 key).
	Filename string `json:"filename"`

	// UserId The ID of the user requesting the upload URL.
	UserId int64 `json:"user_id"`
}

// PresignedUploadResponse defines model for PresignedUploadResponse.
type PresignedUploadResponse struct {
	// ExpiresAt When the presigned URL expires.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// S3Key The S3 object key where the file will be stored.
	S3Key *string `json:"s3_key,omitempty"`

	// S3Uri The S3 URI to use with scraper/start endpoint (input_file_url).
	S3Uri *string `json:"s3_uri,omitempty"`

	// UploadUrl Presigned URL for uploading the file via HTTP PUT.
	UploadUrl *string `json:"upload_url,omitempty"`
}

// UpdateBridgrSkillGapAnalysisStatusRequest defines model for UpdateBridgrSkillGapAnalysisStatusRequest.
type UpdateBridgrSkillGapAnalysisStatusRequest struct {
	// Status Pipeline state aligned with async worker steps
	Status BridgrSkillGapAnalysisStatus `json:"status"`
}

// V1PostGenerateUploadUrlParams defines parameters for V1PostGenerateUploadUrl.
type V1PostGenerateUploadUrlParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PostBridgrAnalysesParams defines parameters for V1PostBridgrAnalyses.
type V1PostBridgrAnalysesParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1DeleteBridgrAnalysisParams defines parameters for V1DeleteBridgrAnalysis.
type V1DeleteBridgrAnalysisParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrAnalysisParams defines parameters for V1GetBridgrAnalysis.
type V1GetBridgrAnalysisParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrAnalysisCoverageParams defines parameters for V1GetBridgrAnalysisCoverage.
type V1GetBridgrAnalysisCoverageParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1DeleteBridgrAnalysisGraphsParams defines parameters for V1DeleteBridgrAnalysisGraphs.
type V1DeleteBridgrAnalysisGraphsParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrAnalysisGraphsParams defines parameters for V1GetBridgrAnalysisGraphs.
type V1GetBridgrAnalysisGraphsParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PostBridgrAnalysisGraphsParams defines parameters for V1PostBridgrAnalysisGraphs.
type V1PostBridgrAnalysisGraphsParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrAnalysisGraphByKindParams defines parameters for V1GetBridgrAnalysisGraphByKind.
type V1GetBridgrAnalysisGraphByKindParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1DeleteBridgrAnalysisLearningPathParams defines parameters for V1DeleteBridgrAnalysisLearningPath.
type V1DeleteBridgrAnalysisLearningPathParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrAnalysisLearningPathParams defines parameters for V1GetBridgrAnalysisLearningPath.
type V1GetBridgrAnalysisLearningPathParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PostBridgrAnalysisLearningPathParams defines parameters for V1PostBridgrAnalysisLearningPath.
type V1PostBridgrAnalysisLearningPathParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrAnalysisNodesMatchedParams defines parameters for V1GetBridgrAnalysisNodesMatched.
type V1GetBridgrAnalysisNodesMatchedParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrAnalysisNodesUnmatchedParams defines parameters for V1GetBridgrAnalysisNodesUnmatched.
type V1GetBridgrAnalysisNodesUnmatchedParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PatchBridgrAnalysisStatusParams defines parameters for V1PatchBridgrAnalysisStatus.
type V1PatchBridgrAnalysisStatusParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrGraphEdgesParams defines parameters for V1GetBridgrGraphEdges.
type V1GetBridgrGraphEdgesParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PostBridgrGraphEdgesParams defines parameters for V1PostBridgrGraphEdges.
type V1PostBridgrGraphEdgesParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrGraphNodesParams defines parameters for V1GetBridgrGraphNodes.
type V1GetBridgrGraphNodesParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PostBridgrGraphNodesParams defines parameters for V1PostBridgrGraphNodes.
type V1PostBridgrGraphNodesParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrGraphNodeByKeyParams defines parameters for V1GetBridgrGraphNodeByKey.
type V1GetBridgrGraphNodeByKeyParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrPathStepsParams defines parameters for V1GetBridgrPathSteps.
type V1GetBridgrPathStepsParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrUserAnalysesParams defines parameters for V1GetBridgrUserAnalyses.
type V1GetBridgrUserAnalysesParams struct {
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrUserCoverageParams defines parameters for V1GetBridgrUserCoverage.
type V1GetBridgrUserCoverageParams struct {
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PostGenerateUploadUrlJSONRequestBody defines body for V1PostGenerateUploadUrl for application/json ContentType.
type V1PostGenerateUploadUrlJSONRequestBody = PresignedUploadRequest

// V1PostBridgrAnalysesJSONRequestBody defines body for V1PostBridgrAnalyses for application/json ContentType.
type V1PostBridgrAnalysesJSONRequestBody = CreateBridgrSkillGapAnalysisRequest

// V1PostBridgrAnalysisGraphsJSONRequestBody defines body for V1PostBridgrAnalysisGraphs for application/json ContentType.
type V1PostBridgrAnalysisGraphsJSONRequestBody = CreateBridgrSkillGapGraphRequest

// V1PostBridgrAnalysisLearningPathJSONRequestBody defines body for V1PostBridgrAnalysisLearningPath for application/json ContentType.
type V1PostBridgrAnalysisLearningPathJSONRequestBody = CreateBridgrSkillGapLearningPathRequest

// V1PatchBridgrAnalysisStatusJSONRequestBody defines body for V1PatchBridgrAnalysisStatus for application/json ContentType.
type V1PatchBridgrAnalysisStatusJSONRequestBody = UpdateBridgrSkillGapAnalysisStatusRequest

// V1PostBridgrGraphEdgesJSONRequestBody defines body for V1PostBridgrGraphEdges for application/json ContentType.
type V1PostBridgrGraphEdgesJSONRequestBody = CreateBridgrSkillGapEdgeRequest

// V1PostBridgrGraphNodesJSONRequestBody defines body for V1PostBridgrGraphNodes for application/json ContentType.
type V1PostBridgrGraphNodesJSONRequestBody = CreateBridgrSkillGapNodeRequest
