// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package types

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BridgrAnalysisAssetReadUrlResponseAccess.
const (
	Direct    BridgrAnalysisAssetReadUrlResponseAccess = "direct"
	Presigned BridgrAnalysisAssetReadUrlResponseAccess = "presigned"
)

// Defines values for BridgrJobSearchProfileCompanyStage.
const (
	BridgrJobSearchProfileCompanyStageAny        BridgrJobSearchProfileCompanyStage = "any"
	BridgrJobSearchProfileCompanyStageEnterprise BridgrJobSearchProfileCompanyStage = "enterprise"
	BridgrJobSearchProfileCompanyStageGrowth     BridgrJobSearchProfileCompanyStage = "growth"
	BridgrJobSearchProfileCompanyStageStartup    BridgrJobSearchProfileCompanyStage = "startup"
)

// Defines values for BridgrJobSearchProfileCompensationGoal.
const (
	BridgrJobSearchProfileCompensationGoalAny     BridgrJobSearchProfileCompensationGoal = "any"
	BridgrJobSearchProfileCompensationGoalDown    BridgrJobSearchProfileCompensationGoal = "down"
	BridgrJobSearchProfileCompensationGoalLateral BridgrJobSearchProfileCompensationGoal = "lateral"
	BridgrJobSearchProfileCompensationGoalUp      BridgrJobSearchProfileCompensationGoal = "up"
)

// Defines values for BridgrJobSearchProfileSeniorityGoal.
const (
	BridgrJobSearchProfileSeniorityGoalAny     BridgrJobSearchProfileSeniorityGoal = "any"
	BridgrJobSearchProfileSeniorityGoalDown    BridgrJobSearchProfileSeniorityGoal = "down"
	BridgrJobSearchProfileSeniorityGoalLateral BridgrJobSearchProfileSeniorityGoal = "lateral"
	BridgrJobSearchProfileSeniorityGoalUp      BridgrJobSearchProfileSeniorityGoal = "up"
)

// Defines values for BridgrJobSearchProfileSourceBoard.
const (
	BridgrJobSearchProfileSourceBoardGlassdoor BridgrJobSearchProfileSourceBoard = "glassdoor"
	BridgrJobSearchProfileSourceBoardIndeed    BridgrJobSearchProfileSourceBoard = "indeed"
	BridgrJobSearchProfileSourceBoardLinkedin  BridgrJobSearchProfileSourceBoard = "linkedin"
)

// Defines values for BridgrSkillGapAnalysisStatus.
const (
	BridgrSkillGapPending BridgrSkillGapAnalysisStatus = "pending"
	Completed             BridgrSkillGapAnalysisStatus = "completed"
	Extracting            BridgrSkillGapAnalysisStatus = "extracting"
	Failed                BridgrSkillGapAnalysisStatus = "failed"
	Graphed               BridgrSkillGapAnalysisStatus = "graphed"
	Pathed                BridgrSkillGapAnalysisStatus = "pathed"
)

// Defines values for BridgrSkillGapGraphKind.
const (
	Candidate       BridgrSkillGapGraphKind = "candidate"
	RoleRequirement BridgrSkillGapGraphKind = "role_requirement"
)

// Defines values for UpsertBridgrJobSearchProfileRequestCompanyStage.
const (
	UpsertBridgrJobSearchProfileRequestCompanyStageAny        UpsertBridgrJobSearchProfileRequestCompanyStage = "any"
	UpsertBridgrJobSearchProfileRequestCompanyStageEnterprise UpsertBridgrJobSearchProfileRequestCompanyStage = "enterprise"
	UpsertBridgrJobSearchProfileRequestCompanyStageGrowth     UpsertBridgrJobSearchProfileRequestCompanyStage = "growth"
	UpsertBridgrJobSearchProfileRequestCompanyStageStartup    UpsertBridgrJobSearchProfileRequestCompanyStage = "startup"
)

// Defines values for UpsertBridgrJobSearchProfileRequestCompensationGoal.
const (
	UpsertBridgrJobSearchProfileRequestCompensationGoalAny     UpsertBridgrJobSearchProfileRequestCompensationGoal = "any"
	UpsertBridgrJobSearchProfileRequestCompensationGoalDown    UpsertBridgrJobSearchProfileRequestCompensationGoal = "down"
	UpsertBridgrJobSearchProfileRequestCompensationGoalLateral UpsertBridgrJobSearchProfileRequestCompensationGoal = "lateral"
	UpsertBridgrJobSearchProfileRequestCompensationGoalUp      UpsertBridgrJobSearchProfileRequestCompensationGoal = "up"
)

// Defines values for UpsertBridgrJobSearchProfileRequestSeniorityGoal.
const (
	UpsertBridgrJobSearchProfileRequestSeniorityGoalAny     UpsertBridgrJobSearchProfileRequestSeniorityGoal = "any"
	UpsertBridgrJobSearchProfileRequestSeniorityGoalDown    UpsertBridgrJobSearchProfileRequestSeniorityGoal = "down"
	UpsertBridgrJobSearchProfileRequestSeniorityGoalLateral UpsertBridgrJobSearchProfileRequestSeniorityGoal = "lateral"
	UpsertBridgrJobSearchProfileRequestSeniorityGoalUp      UpsertBridgrJobSearchProfileRequestSeniorityGoal = "up"
)

// Defines values for UpsertBridgrJobSearchProfileRequestSourceBoard.
const (
	UpsertBridgrJobSearchProfileRequestSourceBoardGlassdoor UpsertBridgrJobSearchProfileRequestSourceBoard = "glassdoor"
	UpsertBridgrJobSearchProfileRequestSourceBoardIndeed    UpsertBridgrJobSearchProfileRequestSourceBoard = "indeed"
	UpsertBridgrJobSearchProfileRequestSourceBoardLinkedin  UpsertBridgrJobSearchProfileRequestSourceBoard = "linkedin"
)

// BridgrAnalysisAssetReadUrlResponse URL usable in the browser to display the CV or JD asset.
// `presigned` = temporary S3/MinIO signed GET URL; `direct` = public or same-origin HTTPS URL (no signing).
type BridgrAnalysisAssetReadUrlResponse struct {
	Access BridgrAnalysisAssetReadUrlResponseAccess `json:"access"`

	// AssetUri Original stored URI from the analysis row (s3:// or https://).
	AssetUri *string `json:"asset_uri,omitempty"`

	// ContentType Hint for rendering (e.g. application/pdf).
	ContentType *string `json:"content_type,omitempty"`

	// ExpiresAt Set when access is presigned; omit for direct URLs.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Url Open in iframe/new tab or pass to a PDF viewer.
	Url string `json:"url"`
}

// BridgrAnalysisAssetReadUrlResponseAccess defines model for BridgrAnalysisAssetReadUrlResponse.Access.
type BridgrAnalysisAssetReadUrlResponseAccess string

// BridgrJobCandidate defines model for BridgrJobCandidate.
type BridgrJobCandidate struct {
	ApplicationUrl   *string                 `json:"application_url"`
	Company          *string                 `json:"company"`
	ContentHash      *string                 `json:"content_hash"`
	CreatedAt        time.Time               `json:"created_at"`
	DiscoveryRunUuid *openapi_types.UUID     `json:"discovery_run_uuid"`
	FetchedAt        *time.Time              `json:"fetched_at"`
	Id               int64                   `json:"id"`
	IngestionStatus  string                  `json:"ingestion_status"`
	JdS3Uri          *string                 `json:"jd_s3_uri"`
	JdText           *string                 `json:"jd_text"`
	JobUrl           string                  `json:"job_url"`
	Location         *string                 `json:"location"`
	RadarPayload     *map[string]interface{} `json:"radar_payload"`
	SourceBoard      *string                 `json:"source_board,omitempty"`
	SourceJobId      *string                 `json:"source_job_id"`
	Title            *string                 `json:"title"`
	UpdatedAt        time.Time               `json:"updated_at"`
	UrlHash          string                  `json:"url_hash"`
	UserId           int32                   `json:"user_id"`
	Uuid             openapi_types.UUID      `json:"uuid"`
}

// BridgrJobCandidateListResponse defines model for BridgrJobCandidateListResponse.
type BridgrJobCandidateListResponse struct {
	Candidates []BridgrJobCandidate `json:"candidates"`
}

// BridgrJobNotification defines model for BridgrJobNotification.
type BridgrJobNotification struct {
	Channel          string                  `json:"channel"`
	CreatedAt        time.Time               `json:"created_at"`
	ErrorDetail      *string                 `json:"error_detail"`
	Id               int64                   `json:"id"`
	JobCandidateUuid openapi_types.UUID      `json:"job_candidate_uuid"`
	Payload          *map[string]interface{} `json:"payload"`
	SeenAt           *time.Time              `json:"seen_at"`
	SentAt           *time.Time              `json:"sent_at"`
	Status           string                  `json:"status"`
	UpdatedAt        time.Time               `json:"updated_at"`
	UserId           int32                   `json:"user_id"`
	Uuid             openapi_types.UUID      `json:"uuid"`
}

// BridgrJobNotificationListResponse defines model for BridgrJobNotificationListResponse.
type BridgrJobNotificationListResponse struct {
	Notifications []BridgrJobNotification `json:"notifications"`
}

// BridgrJobSearchDiscoveryRun defines model for BridgrJobSearchDiscoveryRun.
type BridgrJobSearchDiscoveryRun struct {
	CompletedAt       *time.Time              `json:"completed_at"`
	CreatedAt         time.Time               `json:"created_at"`
	ErrorCode         *string                 `json:"error_code"`
	ErrorDetail       *string                 `json:"error_detail"`
	Id                int64                   `json:"id"`
	NewCandidateCount int32                   `json:"new_candidate_count"`
	RadarMeta         *map[string]interface{} `json:"radar_meta"`
	RawCandidateCount int32                   `json:"raw_candidate_count"`
	RequestParams     *map[string]interface{} `json:"request_params"`
	SqsMessageId      *string                 `json:"sqs_message_id"`
	StartedAt         *time.Time              `json:"started_at"`

	// Status pending, queued, running, completed, failed, cancelled
	Status    string             `json:"status"`
	UpdatedAt time.Time          `json:"updated_at"`
	UserId    int32              `json:"user_id"`
	Uuid      openapi_types.UUID `json:"uuid"`
}

// BridgrJobSearchDiscoveryRunListResponse defines model for BridgrJobSearchDiscoveryRunListResponse.
type BridgrJobSearchDiscoveryRunListResponse struct {
	Runs []BridgrJobSearchDiscoveryRun `json:"runs"`
}

// BridgrJobSearchProfile One canonical Radar search slice per row (bridgr.job_search_profiles).
type BridgrJobSearchProfile struct {
	CanonicalCvAnalysisUuid *openapi_types.UUID `json:"canonical_cv_analysis_uuid"`

	// CareerSwitch True when seeking a career change / new domain
	CareerSwitch bool `json:"career_switch"`

	// CompanyStage Employer company stage filter
	CompanyStage BridgrJobSearchProfileCompanyStage `json:"company_stage"`

	// CompensationGoal Compensation direction for this slice
	CompensationGoal BridgrJobSearchProfileCompensationGoal `json:"compensation_goal"`
	CreatedAt        time.Time                              `json:"created_at"`
	Id               int64                                  `json:"id"`
	Location         string                                 `json:"location"`

	// SeniorityGoal Seniority direction for this slice
	SeniorityGoal BridgrJobSearchProfileSeniorityGoal `json:"seniority_goal"`

	// SoftwareStackMustHave Technology tags that must appear in listings for this slice
	SoftwareStackMustHave []string `json:"software_stack_must_have"`

	// SourceBoard Job board id for this search slice (Radar source)
	SourceBoard BridgrJobSearchProfileSourceBoard `json:"source_board"`

	// TargetRole Primary role or search phrase for this slice
	TargetRole string             `json:"target_role"`
	UpdatedAt  time.Time          `json:"updated_at"`
	UserId     int32              `json:"user_id"`
	Uuid       openapi_types.UUID `json:"uuid"`
}

// BridgrJobSearchProfileCompanyStage Employer company stage filter
type BridgrJobSearchProfileCompanyStage string

// BridgrJobSearchProfileCompensationGoal Compensation direction for this slice
type BridgrJobSearchProfileCompensationGoal string

// BridgrJobSearchProfileSeniorityGoal Seniority direction for this slice
type BridgrJobSearchProfileSeniorityGoal string

// BridgrJobSearchProfileSourceBoard Job board id for this search slice (Radar source)
type BridgrJobSearchProfileSourceBoard string

// BridgrJobSearchProfileListResponse defines model for BridgrJobSearchProfileListResponse.
type BridgrJobSearchProfileListResponse struct {
	Items []BridgrJobSearchProfile `json:"items"`
}

// BridgrPingResponse defines model for BridgrPingResponse.
type BridgrPingResponse struct {
	Product string `json:"product"`
	Status  string `json:"status"`
}

// BridgrSkillGapAnalysis One CV/JD skill-gap analysis run
type BridgrSkillGapAnalysis struct {
	CreatedAt          time.Time               `json:"created_at"`
	CvAssetUri         *string                 `json:"cv_asset_uri"`
	CvFingerprint      *string                 `json:"cv_fingerprint"`
	ErrorCode          *string                 `json:"error_code"`
	ErrorDetail        *string                 `json:"error_detail"`
	ExtractionPayload  *map[string]interface{} `json:"extraction_payload"`
	FounderPersonaUuid *openapi_types.UUID     `json:"founder_persona_uuid"`
	GapSummary         *map[string]interface{} `json:"gap_summary"`
	Id                 int64                   `json:"id"`
	JdAssetUri         *string                 `json:"jd_asset_uri"`
	JdFingerprint      *string                 `json:"jd_fingerprint"`
	LlmModel           *string                 `json:"llm_model"`
	MermaidDiagram     *string                 `json:"mermaid_diagram"`
	PromptVersion      *string                 `json:"prompt_version"`
	PursuitUuid        *openapi_types.UUID     `json:"pursuit_uuid"`
	SqsMessageId       *string                 `json:"sqs_message_id"`

	// Status Pipeline state aligned with async worker steps
	Status    BridgrSkillGapAnalysisStatus `json:"status"`
	Title     *string                      `json:"title"`
	UpdatedAt time.Time                    `json:"updated_at"`
	UserId    int32                        `json:"user_id"`
	Uuid      openapi_types.UUID           `json:"uuid"`
}

// BridgrSkillGapAnalysisListResponse defines model for BridgrSkillGapAnalysisListResponse.
type BridgrSkillGapAnalysisListResponse struct {
	Analyses []BridgrSkillGapAnalysis `json:"analyses"`
}

// BridgrSkillGapAnalysisStatus Pipeline state aligned with async worker steps
type BridgrSkillGapAnalysisStatus string

// BridgrSkillGapCoverageSnapshot Aggregated coverage for an analysis (derived from graph overlap)
type BridgrSkillGapCoverageSnapshot struct {
	CandidateSkills *interface{} `json:"candidate_skills"`
	CoveragePct     *float32     `json:"coverage_pct"`
	MatchedSkills   *interface{} `json:"matched_skills"`
	RequiredSkills  *interface{} `json:"required_skills"`
}

// BridgrSkillGapEdge defines model for BridgrSkillGapEdge.
type BridgrSkillGapEdge struct {
	CreatedAt    time.Time               `json:"created_at"`
	FromNodeUuid openapi_types.UUID      `json:"from_node_uuid"`
	GraphUuid    openapi_types.UUID      `json:"graph_uuid"`
	Id           int64                   `json:"id"`
	Metadata     *map[string]interface{} `json:"metadata"`
	Relation     string                  `json:"relation"`
	ToNodeUuid   openapi_types.UUID      `json:"to_node_uuid"`
	UpdatedAt    time.Time               `json:"updated_at"`
	Uuid         openapi_types.UUID      `json:"uuid"`
	Weight       *float32                `json:"weight"`
}

// BridgrSkillGapEdgeListResponse defines model for BridgrSkillGapEdgeListResponse.
type BridgrSkillGapEdgeListResponse struct {
	Edges []BridgrSkillGapEdge `json:"edges"`
}

// BridgrSkillGapGraph defines model for BridgrSkillGapGraph.
type BridgrSkillGapGraph struct {
	AnalysisUuid openapi_types.UUID `json:"analysis_uuid"`
	CreatedAt    time.Time          `json:"created_at"`
	Id           int64              `json:"id"`

	// Kind candidate = skills from CV; role_requirement = skills from JD
	Kind      BridgrSkillGapGraphKind `json:"kind"`
	Metadata  *map[string]interface{} `json:"metadata"`
	UpdatedAt time.Time               `json:"updated_at"`
	Uuid      openapi_types.UUID      `json:"uuid"`
}

// BridgrSkillGapGraphKind candidate = skills from CV; role_requirement = skills from JD
type BridgrSkillGapGraphKind string

// BridgrSkillGapGraphListResponse defines model for BridgrSkillGapGraphListResponse.
type BridgrSkillGapGraphListResponse struct {
	Graphs []BridgrSkillGapGraph `json:"graphs"`
}

// BridgrSkillGapLearningPath defines model for BridgrSkillGapLearningPath.
type BridgrSkillGapLearningPath struct {
	Algorithm    *string                 `json:"algorithm"`
	AnalysisUuid openapi_types.UUID      `json:"analysis_uuid"`
	CreatedAt    time.Time               `json:"created_at"`
	Id           int64                   `json:"id"`
	PathMetadata *map[string]interface{} `json:"path_metadata"`
	PathVersion  int32                   `json:"path_version"`
	Title        *string                 `json:"title"`
	UpdatedAt    time.Time               `json:"updated_at"`
	Uuid         openapi_types.UUID      `json:"uuid"`
}

// BridgrSkillGapNode defines model for BridgrSkillGapNode.
type BridgrSkillGapNode struct {
	CreatedAt       time.Time               `json:"created_at"`
	Description     *string                 `json:"description"`
	DisplayName     string                  `json:"display_name"`
	Evidence        *map[string]interface{} `json:"evidence"`
	GraphUuid       openapi_types.UUID      `json:"graph_uuid"`
	Id              int64                   `json:"id"`
	Metadata        *map[string]interface{} `json:"metadata"`
	NodeKey         string                  `json:"node_key"`
	PositionX       *int32                  `json:"position_x"`
	PositionY       *int32                  `json:"position_y"`
	ProficiencyHint *string                 `json:"proficiency_hint"`
	Source          *string                 `json:"source"`
	UpdatedAt       time.Time               `json:"updated_at"`
	Uuid            openapi_types.UUID      `json:"uuid"`
}

// BridgrSkillGapNodeListResponse defines model for BridgrSkillGapNodeListResponse.
type BridgrSkillGapNodeListResponse struct {
	Nodes []BridgrSkillGapNode `json:"nodes"`
}

// BridgrSkillGapPathStep defines model for BridgrSkillGapPathStep.
type BridgrSkillGapPathStep struct {
	CourseLessonUuid        *openapi_types.UUID     `json:"course_lesson_uuid"`
	CreatedAt               time.Time               `json:"created_at"`
	EstimatedHours          *float32                `json:"estimated_hours"`
	FounderLearningItemUuid *openapi_types.UUID     `json:"founder_learning_item_uuid"`
	Id                      int64                   `json:"id"`
	LinkedNodeKeys          *[]string               `json:"linked_node_keys"`
	Metadata                *map[string]interface{} `json:"metadata"`
	PathUuid                openapi_types.UUID      `json:"path_uuid"`
	Rationale               *string                 `json:"rationale"`
	ResourceKind            *string                 `json:"resource_kind"`
	ResourceUri             *string                 `json:"resource_uri"`
	StepIndex               int32                   `json:"step_index"`
	Title                   string                  `json:"title"`
	UpdatedAt               time.Time               `json:"updated_at"`
	Uuid                    openapi_types.UUID      `json:"uuid"`
}

// BridgrSkillGapPathStepListResponse defines model for BridgrSkillGapPathStepListResponse.
type BridgrSkillGapPathStepListResponse struct {
	Steps []BridgrSkillGapPathStep `json:"steps"`
}

// BridgrSkillGapUserCoverageListResponse defines model for BridgrSkillGapUserCoverageListResponse.
type BridgrSkillGapUserCoverageListResponse struct {
	Items []BridgrSkillGapUserCoverageRow `json:"items"`
}

// BridgrSkillGapUserCoverageRow Per-analysis coverage summary for dashboard lists (matches aggregated SQL read)
type BridgrSkillGapUserCoverageRow struct {
	AnalysisId      *int64              `json:"analysis_id,omitempty"`
	AnalysisUuid    *openapi_types.UUID `json:"analysis_uuid,omitempty"`
	CandidateSkills *int64              `json:"candidate_skills"`
	CoveragePct     *float32            `json:"coverage_pct"`
	CreatedAt       *time.Time          `json:"created_at,omitempty"`
	MatchedSkills   *int64              `json:"matched_skills"`
	RequiredSkills  *int64              `json:"required_skills"`

	// Status Pipeline state aligned with async worker steps
	Status *BridgrSkillGapAnalysisStatus `json:"status,omitempty"`
	Title  *string                       `json:"title"`
	UserId *int32                        `json:"user_id,omitempty"`
}

// CreateBridgrJobSearchDiscoveryRunRequest Start a discovery run for one job search profile (same enqueue path as the worker scheduler).
// When the user has more than one profile, job_search_profile_uuid is required.
type CreateBridgrJobSearchDiscoveryRunRequest struct {
	// JobSearchProfileUuid Profile to run; required if the user has multiple job search profiles
	JobSearchProfileUuid *openapi_types.UUID `json:"job_search_profile_uuid"`

	// RequestParams Optional overrides merged into request_params after profile fields
	RequestParams *map[string]interface{} `json:"request_params"`
}

// CreateBridgrJobSearchProfileRequest Create or update a job search profile. Omitted keys leave existing DB values unchanged on update;
// on create, server defaults apply for missing columns (e.g. indeed, any goals, empty stack).
type CreateBridgrJobSearchProfileRequest = UpsertBridgrJobSearchProfileRequest

// CreateBridgrSkillGapAnalysisRequest defines model for CreateBridgrSkillGapAnalysisRequest.
type CreateBridgrSkillGapAnalysisRequest struct {
	CvAssetUri         *string             `json:"cv_asset_uri"`
	CvFingerprint      *string             `json:"cv_fingerprint"`
	FounderPersonaUuid *openapi_types.UUID `json:"founder_persona_uuid"`
	JdAssetUri         *string             `json:"jd_asset_uri"`
	JdFingerprint      *string             `json:"jd_fingerprint"`

	// JobCandidateUuid When set, insert bridgr.analysis_job_link after the analysis is created
	JobCandidateUuid *openapi_types.UUID `json:"job_candidate_uuid"`
	LlmModel         *string             `json:"llm_model"`
	PromptVersion    *string             `json:"prompt_version"`
	PursuitUuid      *openapi_types.UUID `json:"pursuit_uuid"`
	Title            *string             `json:"title"`
	UserId           int32               `json:"user_id"`
}

// CreateBridgrSkillGapEdgeRequest defines model for CreateBridgrSkillGapEdgeRequest.
type CreateBridgrSkillGapEdgeRequest struct {
	FromNodeUuid openapi_types.UUID      `json:"from_node_uuid"`
	Metadata     *map[string]interface{} `json:"metadata"`
	Relation     string                  `json:"relation"`
	ToNodeUuid   openapi_types.UUID      `json:"to_node_uuid"`
	Weight       *float32                `json:"weight"`
}

// CreateBridgrSkillGapGraphRequest defines model for CreateBridgrSkillGapGraphRequest.
type CreateBridgrSkillGapGraphRequest struct {
	// Kind candidate = skills from CV; role_requirement = skills from JD
	Kind     BridgrSkillGapGraphKind `json:"kind"`
	Metadata *map[string]interface{} `json:"metadata"`
}

// CreateBridgrSkillGapLearningPathRequest defines model for CreateBridgrSkillGapLearningPathRequest.
type CreateBridgrSkillGapLearningPathRequest struct {
	Algorithm    *string                 `json:"algorithm"`
	PathMetadata *map[string]interface{} `json:"path_metadata"`
	PathVersion  *int32                  `json:"path_version"`
	Title        *string                 `json:"title"`
}

// CreateBridgrSkillGapNodeRequest defines model for CreateBridgrSkillGapNodeRequest.
type CreateBridgrSkillGapNodeRequest struct {
	Description     *string                 `json:"description"`
	DisplayName     string                  `json:"display_name"`
	Evidence        *map[string]interface{} `json:"evidence"`
	Metadata        *map[string]interface{} `json:"metadata"`
	NodeKey         string                  `json:"node_key"`
	PositionX       *int32                  `json:"position_x"`
	PositionY       *int32                  `json:"position_y"`
	ProficiencyHint *string                 `json:"proficiency_hint"`
	Source          *string                 `json:"source"`
}

// PatchBridgrJobNotificationRequest At least one field should be set
type PatchBridgrJobNotificationRequest struct {
	ErrorDetail *string `json:"error_detail"`

	// MarkSeen When true, sets status to seen and seen_at to now
	MarkSeen *bool `json:"mark_seen"`

	// Status e.g. pending, sent, failed, seen, skipped
	Status *string `json:"status"`
}

// PresignedUploadRequest defines model for PresignedUploadRequest.
type PresignedUploadRequest struct {
	// ContentType MIME type of the file. If not provided, will be inferred from filename extension.
	ContentType *string `json:"content_type,omitempty"`

	// Filename Name of the file to be uploaded (used to generate S3 key).
	Filename string `json:"filename"`

	// UserId The ID of the user requesting the upload URL.
	UserId int64 `json:"user_id"`
}

// PresignedUploadResponse defines model for PresignedUploadResponse.
type PresignedUploadResponse struct {
	// ExpiresAt When the presigned URL expires.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// S3Key The S3 object key where the file will be stored.
	S3Key *string `json:"s3_key,omitempty"`

	// S3Uri The S3 URI to use with scraper/start endpoint (input_file_url).
	S3Uri *string `json:"s3_uri,omitempty"`

	// UploadUrl Presigned URL for uploading the file via HTTP PUT.
	UploadUrl *string `json:"upload_url,omitempty"`
}

// UpdateBridgrSkillGapAnalysisStatusRequest defines model for UpdateBridgrSkillGapAnalysisStatusRequest.
type UpdateBridgrSkillGapAnalysisStatusRequest struct {
	// Status Pipeline state aligned with async worker steps
	Status BridgrSkillGapAnalysisStatus `json:"status"`
}

// UpsertBridgrJobSearchProfileRequest Create or update a job search profile. Omitted keys leave existing DB values unchanged on update;
// on create, server defaults apply for missing columns (e.g. indeed, any goals, empty stack).
type UpsertBridgrJobSearchProfileRequest struct {
	CanonicalCvAnalysisUuid *openapi_types.UUID `json:"canonical_cv_analysis_uuid"`
	CareerSwitch            *bool               `json:"career_switch"`

	// CompanyStage Employer company stage filter
	CompanyStage *UpsertBridgrJobSearchProfileRequestCompanyStage `json:"company_stage"`

	// CompensationGoal Compensation direction for this slice
	CompensationGoal *UpsertBridgrJobSearchProfileRequestCompensationGoal `json:"compensation_goal"`
	Location         *string                                              `json:"location"`

	// SeniorityGoal Seniority direction for this slice
	SeniorityGoal         *UpsertBridgrJobSearchProfileRequestSeniorityGoal `json:"seniority_goal"`
	SoftwareStackMustHave *[]string                                         `json:"software_stack_must_have"`

	// SourceBoard Job board id for this search slice
	SourceBoard *UpsertBridgrJobSearchProfileRequestSourceBoard `json:"source_board"`
	TargetRole  *string                                         `json:"target_role"`
}

// UpsertBridgrJobSearchProfileRequestCompanyStage Employer company stage filter
type UpsertBridgrJobSearchProfileRequestCompanyStage string

// UpsertBridgrJobSearchProfileRequestCompensationGoal Compensation direction for this slice
type UpsertBridgrJobSearchProfileRequestCompensationGoal string

// UpsertBridgrJobSearchProfileRequestSeniorityGoal Seniority direction for this slice
type UpsertBridgrJobSearchProfileRequestSeniorityGoal string

// UpsertBridgrJobSearchProfileRequestSourceBoard Job board id for this search slice
type UpsertBridgrJobSearchProfileRequestSourceBoard string

// V1PostGenerateUploadUrlParams defines parameters for V1PostGenerateUploadUrl.
type V1PostGenerateUploadUrlParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PostBridgrAnalysesParams defines parameters for V1PostBridgrAnalyses.
type V1PostBridgrAnalysesParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1DeleteBridgrAnalysisParams defines parameters for V1DeleteBridgrAnalysis.
type V1DeleteBridgrAnalysisParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrAnalysisParams defines parameters for V1GetBridgrAnalysis.
type V1GetBridgrAnalysisParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrAnalysisCvAssetReadUrlParams defines parameters for V1GetBridgrAnalysisCvAssetReadUrl.
type V1GetBridgrAnalysisCvAssetReadUrlParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrAnalysisJdAssetReadUrlParams defines parameters for V1GetBridgrAnalysisJdAssetReadUrl.
type V1GetBridgrAnalysisJdAssetReadUrlParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrAnalysisCoverageParams defines parameters for V1GetBridgrAnalysisCoverage.
type V1GetBridgrAnalysisCoverageParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1DeleteBridgrAnalysisGraphsParams defines parameters for V1DeleteBridgrAnalysisGraphs.
type V1DeleteBridgrAnalysisGraphsParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrAnalysisGraphsParams defines parameters for V1GetBridgrAnalysisGraphs.
type V1GetBridgrAnalysisGraphsParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PostBridgrAnalysisGraphsParams defines parameters for V1PostBridgrAnalysisGraphs.
type V1PostBridgrAnalysisGraphsParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrAnalysisGraphByKindParams defines parameters for V1GetBridgrAnalysisGraphByKind.
type V1GetBridgrAnalysisGraphByKindParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1DeleteBridgrAnalysisLearningPathParams defines parameters for V1DeleteBridgrAnalysisLearningPath.
type V1DeleteBridgrAnalysisLearningPathParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrAnalysisLearningPathParams defines parameters for V1GetBridgrAnalysisLearningPath.
type V1GetBridgrAnalysisLearningPathParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PostBridgrAnalysisLearningPathParams defines parameters for V1PostBridgrAnalysisLearningPath.
type V1PostBridgrAnalysisLearningPathParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrAnalysisNodesMatchedParams defines parameters for V1GetBridgrAnalysisNodesMatched.
type V1GetBridgrAnalysisNodesMatchedParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrAnalysisNodesUnmatchedParams defines parameters for V1GetBridgrAnalysisNodesUnmatched.
type V1GetBridgrAnalysisNodesUnmatchedParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PatchBridgrAnalysisStatusParams defines parameters for V1PatchBridgrAnalysisStatus.
type V1PatchBridgrAnalysisStatusParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrGraphEdgesParams defines parameters for V1GetBridgrGraphEdges.
type V1GetBridgrGraphEdgesParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PostBridgrGraphEdgesParams defines parameters for V1PostBridgrGraphEdges.
type V1PostBridgrGraphEdgesParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrGraphNodesParams defines parameters for V1GetBridgrGraphNodes.
type V1GetBridgrGraphNodesParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PostBridgrGraphNodesParams defines parameters for V1PostBridgrGraphNodes.
type V1PostBridgrGraphNodesParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrGraphNodeByKeyParams defines parameters for V1GetBridgrGraphNodeByKey.
type V1GetBridgrGraphNodeByKeyParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrJobCandidateParams defines parameters for V1GetBridgrJobCandidate.
type V1GetBridgrJobCandidateParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrJobDiscoveryRunParams defines parameters for V1GetBridgrJobDiscoveryRun.
type V1GetBridgrJobDiscoveryRunParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PatchBridgrJobNotificationParams defines parameters for V1PatchBridgrJobNotification.
type V1PatchBridgrJobNotificationParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrPathStepsParams defines parameters for V1GetBridgrPathSteps.
type V1GetBridgrPathStepsParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrUserAnalysesParams defines parameters for V1GetBridgrUserAnalyses.
type V1GetBridgrUserAnalysesParams struct {
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrUserCoverageParams defines parameters for V1GetBridgrUserCoverage.
type V1GetBridgrUserCoverageParams struct {
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrUserJobCandidatesParams defines parameters for V1GetBridgrUserJobCandidates.
type V1GetBridgrUserJobCandidatesParams struct {
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// DiscoveryRunUuid Filter by discovery run
	DiscoveryRunUuid *openapi_types.UUID `form:"discovery_run_uuid,omitempty" json:"discovery_run_uuid,omitempty"`
	IngestionStatus  *string             `form:"ingestion_status,omitempty" json:"ingestion_status,omitempty"`
	SourceBoard      *string             `form:"source_board,omitempty" json:"source_board,omitempty"`

	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrUserJobDiscoveryRunsParams defines parameters for V1GetBridgrUserJobDiscoveryRuns.
type V1GetBridgrUserJobDiscoveryRunsParams struct {
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PostBridgrUserJobDiscoveryRunsParams defines parameters for V1PostBridgrUserJobDiscoveryRuns.
type V1PostBridgrUserJobDiscoveryRunsParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PostBridgrUserJobDiscoveryRunCancelParams defines parameters for V1PostBridgrUserJobDiscoveryRunCancel.
type V1PostBridgrUserJobDiscoveryRunCancelParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrUserJobNotificationsParams defines parameters for V1GetBridgrUserJobNotifications.
type V1GetBridgrUserJobNotificationsParams struct {
	Limit  *int32 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`

	// Since Return rows with created_at strictly after this timestamp (RFC3339)
	Since  *time.Time `form:"since,omitempty" json:"since,omitempty"`
	Status *string    `form:"status,omitempty" json:"status,omitempty"`

	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1ListBridgrUserJobSearchProfilesParams defines parameters for V1ListBridgrUserJobSearchProfiles.
type V1ListBridgrUserJobSearchProfilesParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1CreateBridgrUserJobSearchProfileParams defines parameters for V1CreateBridgrUserJobSearchProfile.
type V1CreateBridgrUserJobSearchProfileParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1DeleteBridgrUserJobSearchProfileParams defines parameters for V1DeleteBridgrUserJobSearchProfile.
type V1DeleteBridgrUserJobSearchProfileParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1GetBridgrUserJobSearchProfileByUUIDParams defines parameters for V1GetBridgrUserJobSearchProfileByUUID.
type V1GetBridgrUserJobSearchProfileByUUIDParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PutBridgrUserJobSearchProfileByUUIDParams defines parameters for V1PutBridgrUserJobSearchProfileByUUID.
type V1PutBridgrUserJobSearchProfileByUUIDParams struct {
	// XAPIKEY API Key of the service making the request
	XAPIKEY string `json:"X-API-KEY"`
}

// V1PostGenerateUploadUrlJSONRequestBody defines body for V1PostGenerateUploadUrl for application/json ContentType.
type V1PostGenerateUploadUrlJSONRequestBody = PresignedUploadRequest

// V1PostBridgrAnalysesJSONRequestBody defines body for V1PostBridgrAnalyses for application/json ContentType.
type V1PostBridgrAnalysesJSONRequestBody = CreateBridgrSkillGapAnalysisRequest

// V1PostBridgrAnalysisGraphsJSONRequestBody defines body for V1PostBridgrAnalysisGraphs for application/json ContentType.
type V1PostBridgrAnalysisGraphsJSONRequestBody = CreateBridgrSkillGapGraphRequest

// V1PostBridgrAnalysisLearningPathJSONRequestBody defines body for V1PostBridgrAnalysisLearningPath for application/json ContentType.
type V1PostBridgrAnalysisLearningPathJSONRequestBody = CreateBridgrSkillGapLearningPathRequest

// V1PatchBridgrAnalysisStatusJSONRequestBody defines body for V1PatchBridgrAnalysisStatus for application/json ContentType.
type V1PatchBridgrAnalysisStatusJSONRequestBody = UpdateBridgrSkillGapAnalysisStatusRequest

// V1PostBridgrGraphEdgesJSONRequestBody defines body for V1PostBridgrGraphEdges for application/json ContentType.
type V1PostBridgrGraphEdgesJSONRequestBody = CreateBridgrSkillGapEdgeRequest

// V1PostBridgrGraphNodesJSONRequestBody defines body for V1PostBridgrGraphNodes for application/json ContentType.
type V1PostBridgrGraphNodesJSONRequestBody = CreateBridgrSkillGapNodeRequest

// V1PatchBridgrJobNotificationJSONRequestBody defines body for V1PatchBridgrJobNotification for application/json ContentType.
type V1PatchBridgrJobNotificationJSONRequestBody = PatchBridgrJobNotificationRequest

// V1PostBridgrUserJobDiscoveryRunsJSONRequestBody defines body for V1PostBridgrUserJobDiscoveryRuns for application/json ContentType.
type V1PostBridgrUserJobDiscoveryRunsJSONRequestBody = CreateBridgrJobSearchDiscoveryRunRequest

// V1CreateBridgrUserJobSearchProfileJSONRequestBody defines body for V1CreateBridgrUserJobSearchProfile for application/json ContentType.
type V1CreateBridgrUserJobSearchProfileJSONRequestBody = CreateBridgrJobSearchProfileRequest

// V1PutBridgrUserJobSearchProfileByUUIDJSONRequestBody defines body for V1PutBridgrUserJobSearchProfileByUUID for application/json ContentType.
type V1PutBridgrUserJobSearchProfileByUUIDJSONRequestBody = UpsertBridgrJobSearchProfileRequest
